app/package.json
app/src/locale/gettext.po
app/webpack.config.js
cadasta/config/settings/production.py
provision/roles/cadasta/application/templates/settings.j2
provision/roles/cadasta/install/tasks/main.yml
provision/roles/cadasta/production/tasks/main.yml
provision/roles/webserver/production/templates/uwsgi.ini

Remove the extra entry points for running the development server and replace them with command line switches in the command for "npm start".  This means we're left with a single index.jsx entry point in the Webpack configuration, which is almost certainly what we want.

Better Webpack configuration

---

.gitignore
.travis.yml
README.md
Vagrantfile
app/src/js/account/components/Login.jsx
app/src/js/account/components/Profile.jsx
app/src/js/account/components/RegistrationForm.jsx
app/src/locale/gettext.po
app/webpack.config.js
cadasta/accounts/tests/factories.py
functional_tests/accounts/test_login.py
functional_tests/accounts/test_profile.py
functional_tests/accounts/test_registration.py
functional_tests/base.py
functional_tests/pages/Login.py
functional_tests/pages/Profile.py
functional_tests/pages/Registration.py
functional_tests/pages/base.py
functional_tests/run.py
provision/roles/cadasta/application/tasks/main.yml
provision/roles/cadasta/production/tasks/main.yml
provision/roles/testing/tasks/main.yml
provision/roles/webserver/development/templates/nginx-development
provision/vagrant.yml
requirements/dev.txt

* Move Webpack setup into development VM
* Functional test support: Selenium + PhantomJS
* Functional testing infrastructure: test runner and "pages" pattern
* Functional tests for: login, registration, user profile editing
* Functional tests on Travis (doesn't work yet)
See documentation at:
- https://github.com/Cadasta/cadasta-platform/wiki/Running-functional-tests
- https://github.com/Cadasta/cadasta-platform/wiki/Writing-functional-tests

Functional testing

---

cadasta/config/permissions/data-collector.json
cadasta/config/permissions/default.json
cadasta/config/permissions/org-admin.json
cadasta/config/permissions/project-manager.json
cadasta/config/permissions/project-user.json
cadasta/config/permissions/superuser.json

Covers organisations, projects and users.  This goes with the information on the wiki page at https://github.com/Cadasta/cadasta-platform/wiki/Permissioning-policies and is intended to cover at least the first part of https://github.com/Cadasta/cadasta-platform/issues/8 -- there will be more permissions-related stuff as we implement new features.

First cut at permissions policies

---

cadasta/core/serializers.py
cadasta/core/tests/test_serializer.py
cadasta/organization/serializers.py

`FieldSelectorSerializer` is a serializer mixin that enables selecting fields for serialization, by adding the `field` keyword argument during initialization. 
Example:
```python
from core.serializers import FieldSelectorSerializer
from rest_framework.serializers import ModelSerializer
class OrganizationSerializer(FieldSelectorSerializer, ModelSerializer):
class Meta:
model = Organization
fields = ('id', 'name', 'description',)
org = Organization.objects.create(name='Org', description='some org')
serializer = OrganizationSerializer(org, fields=('id', 'name'))
serializer.data  # {'id': 123, 'name': 'Org'}
```
Also removes `organzation.serializers.UserOrganizationSerializer` because it's not needed any longer.

Implements FieldSelectorSerializer

---

cadasta/core/factories.py
cadasta/core/management/commands/loadfixtures.py

Adding single sets of data is not perfect, but it works. Let me know if this fixes all the pep8 stuff, I don't really trust my linter...

cleaned up test data

---

cadasta/core/mixins.py
cadasta/organization/messages.py
cadasta/organization/models.py
cadasta/organization/tests/test_urls_default.py
cadasta/organization/tests/test_views_default.py
cadasta/organization/urls/default/organizations.py
cadasta/organization/views/api.py
cadasta/organization/views/default.py
cadasta/organization/views/mixins.py
cadasta/templates/organization/organization_dashboard.html
requirements/common.txt

- Use custom LoginPermissionRequiredMixin based on django-tutelary's LoginPermissionRequiredMixin
- Add unarchive view
- Moved mixins.py into directory views
- Moved all permission related messages into messages.py, models and views read from there, so messages will be consistent
- Tests for authorized, unauthorized, unauthenticated users, both for GET and POST

Add permissions to organization default views

---

MANIFEST.in
cadasta/accounts/models.py
cadasta/accounts/tests/test_forms.py
cadasta/accounts/tests/test_serializers.py
cadasta/accounts/tests/test_views_api.py
cadasta/core/fixtures.py
cadasta/organization/forms.py
cadasta/organization/models.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_models.py
cadasta/organization/tests/test_serializers.py
cadasta/organization/tests/test_views_api_organizations.py
cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/tests/test_views_api_users.py
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py
cadasta/organization/views/mixins.py
functional_tests/organizations/test_member.py
functional_tests/organizations/test_organization.py
functional_tests/organizations/test_organizations.py
functional_tests/users/test_activation.py
functional_tests/users/test_page_access.py
functional_tests/users/test_page_list.py
requirements/common.txt
requirements/dev.txt
runtests.py
setup.py
tox.ini

- Add default policy to new users
- Bump django-tutelary dependency for better queryset filtering
- Avoid using "default" as a policy name in tests
- Make creator of organization an org admin
- DRY tox and setup dependency configuration
- Fix up policy creation in functional tests

Bugs: new users default policy; org creation

---

.travis.yml

Since we're using `tox` for testing on Travis now, we don't need to install Python packages outside of the `tox` virtual environments.  We just need to install `tox` and set it running.  This shaves a few minutes off the test times.  The major remaining contributor to setup time is the SASS compiler: this downloads a source distribution of `libsass` and builds it for every run, which takes a lot of time.  I had a desultory try at doing something about this, by prebuilding a wheel and storing it locally in the `cadasta-platform` repo, but I wasn't able to get it working because of Python interpreter version funnies.  (To be fair, I spent about 10 minutes on it before getting bored with it, so it might still be an option.  I'll take a look next week.)

Remove redundant setup in .travis.yml

---

.travis.yml
provision/roles/testing/files/squid.conf
provision/roles/testing/handlers/main.yml
provision/roles/testing/tasks/main.yml

For both VM and Travis, install Squid web cache with configuration to prevent re-requesting of OSM map tiles -- this was causing functional tests to fail intermittently, probably because of request throttling by the OSM tile servers.
(I'm not absolutely 100% sure that this will fix *all* the problems we've had with functional tests, but it seems to have made a substantial difference both locally and on Travis, so I think it deals with most of the problem.)

Squid setup for functional testing

---

cadasta/core/static/js/contacts.js
cadasta/organization/fields.py
cadasta/organization/forms.py
cadasta/organization/tests/test_fields.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_validators.py
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/tests/test_widgets.py
cadasta/organization/validators.py
cadasta/organization/widgets.py
cadasta/templates/organization/organization_form.html
cadasta/templates/organization/project_add_details.html
cadasta/templates/organization/project_edit_details.html
functional_tests/base.py
functional_tests/pages/OrganizationList.py

- Adds `organzation.fields.ContactsFields`, which uses Django formsets to display and validate contacts
- `organzation.forms.ContactsForm` is used by the formset for individual contacts
- `organization.widgets.ContactsWidget` provides corresponding UI components

Contacts form for organizations and projects

---

cadasta/templates/allauth/account/password_change.html
cadasta/templates/allauth/account/signup.html
cadasta/templates/allauth/account/snippets/already_logged_in.html

Portion of design updates - text changes...

Text changes on account pages

---

cadasta/core/fixtures.py
cadasta/core/tests/test_fixtures.py
cadasta/core/tests/test_views_default.py
cadasta/core/views/default.py
cadasta/organization/models.py
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/views/default.py
cadasta/templates/organization/organization_dashboard.html
cadasta/templates/organization/organization_list.html

- Dashboard only displays projects the user has view access to.
- Organization dashboard only displays private projects if user is a member of that organization.
- Organization list view only shows number of public projects, unless the user is a member of a specific organization, in which case it shows the real amount.
- Added fixtures for private projects.

Fixes #196: Private projects only visible to organization members 

---

cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/views/default.py
cadasta/templates/organization/organization_dashboard.html
cadasta/templates/organization/organization_members.html
cadasta/templates/organization/organization_members_add.html
cadasta/templates/organization/organization_members_edit.html
cadasta/templates/organization/organization_wrapper.html

Replaced variable context['object'] with context['organization'] where appropriate for consistence across templates

Added wrapper to organization templates

---

provision/roles/testing/tasks/main.yml

Ubuntu 14.04 upgrade of Firefox to 47.0 broke Selenium: the new
Mozilla WebDriver for Firefox isn't yet released and the old one doesn't
work with the new version of Firefox.  Downgrading temporarily.

Downgrade to Firefox 46 for functional testing

---

functional_tests/base.py

Kinda a silly pull request, but I cleaned up the comment a little to remove the reference to PhantomJS.

remove reference to PhantomJS

---

cadasta/templates/organization/project_edit_details.html
cadasta/templates/organization/project_edit_geometry.html
cadasta/templates/organization/project_edit_permissions.html
cadasta/templates/resources/edit.html
cadasta/templates/resources/project_add_existing.html
cadasta/templates/resources/project_add_new.html

Forms were not visible because the content block for main content inside `project_wrapper.html` was changed. I changed the name in all affected templates and adapted all templates according to the new layout.

Fixes #240 + #247 -- Adapt templates to new project wrapper

---

cadasta/core/static/js/dataTables.conditionalPaging.js
cadasta/templates/core/base.html

Hides "Previous" and "Next" buttons when there's only one page of data to display in all datatables.  Item count is still displayed, so you see something like "Showing 1 to 3 of 3 entries" to confirm that you're seeing all the entries on a single page.

Add conditional paging for datatables

---

cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py
functional_tests/organizations/test_organization_member_list.py

This PR contains the following changes:
- Modified the add org member form to check if the user is already a member of the org
- Added a unit test for this check
- Modified a functional test for this check

Fixes #263

---

cadasta/templates/organization/organization_wrapper.html

There were a couple of places in the templates where we have a link to add a new member to the org, but the `href` was empty. This PR fixes that.

Add missing URL in menu item

---

cadasta/config/urls.py
cadasta/organization/urls/api/organizations.py
cadasta/party/tests/test_urls_api.py
cadasta/party/urls/api/parties.py
cadasta/spatial/tests/test_urls_api.py
cadasta/spatial/urls/api/spatial.py

- Move the spatial unit API URL patterns from organization/urls/api/organizations.py to config/urls.py to be consistent with the other record URLs
- Add unit tests for the records API URLs

Add records API URL unit tests

---

cadasta/accounts/forms.py
cadasta/accounts/serializers.py
cadasta/accounts/tests/test_forms.py
cadasta/accounts/tests/test_serializers.py
cadasta/config/settings/default.py
cadasta/organization/forms.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_serializers.py

Added validation in the organization, project, and user forms and serializers to prevent names and usernames equal to “Add” or “New”.

Fixes #285

---

cadasta/templates/organization/organization_dashboard.html
cadasta/templates/organization/organization_members.html
cadasta/templates/organization/organization_members_edit.html
cadasta/templates/organization/project_add_details.html
cadasta/templates/organization/project_add_extents.html
cadasta/templates/organization/project_add_permissions.html
cadasta/templates/organization/project_add_wrapper.html
cadasta/templates/organization/project_dashboard.html
cadasta/templates/organization/project_edit_details.html
cadasta/templates/organization/project_edit_geometry.html
cadasta/templates/organization/project_edit_permissions.html
cadasta/templates/organization/project_wrapper.html
cadasta/templates/party/party_list.html
cadasta/templates/resources/edit.html
cadasta/templates/resources/project_add_existing.html
cadasta/templates/resources/project_add_new.html
cadasta/templates/resources/project_detail.html
cadasta/templates/resources/project_list.html
cadasta/templates/resources/table.html
cadasta/templates/resources/table_add_lib.html
cadasta/templates/resources/table_sm.html
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_delete.html
cadasta/templates/spatial/location_detail.html
cadasta/templates/spatial/location_edit.html
cadasta/templates/spatial/location_form.html
cadasta/templates/spatial/location_map.html
cadasta/templates/spatial/relationship_add.html
cadasta/templates/spatial/resources_add.html
cadasta/templates/spatial/resources_new.html

Completes #198, #301, #306.
Updates page titles.
Adds cursor to clickable rows.
Updates "entities associated" header to "connections".
--------------------------------------------
New project wizard page titles
Project area titles work
Resources title - removed project titles
Resources & Map page title
Add relationships and resources to location titles
Change title to test tests
Page title changes
Project dashboard title - remove duplicate
Add records API URL unit tests
Update small table

Organization page titles

---

cadasta/config/settings/default.py
cadasta/config/settings/dev.py
cadasta/config/settings/production.py
cadasta/config/settings/travis.py
cadasta/config/urls/default.py
cadasta/config/urls/dev.py
cadasta/config/urls/production.py

- Separates URL config into `dev` and `production` config, mainly because we can now include the correct URL config for dev and production from _django-buckets_
- Removes `ROOT_URLCONF` from default settings and adds specific `ROOT_URLCONF` to production, travis and dev configs

Test + production URL configs

---

cadasta/organization/views/default.py
cadasta/templates/organization/project_dashboard.html

Adds rudimentary statistics (number of locations, parties, and resources) to the project overview page if there are any locations, parties, or resources in the project. Otherwise, the starter text is displayed.
Note that this does not yet implement the nice iconified statistics in the [Project Overview wireframe](https://drive.google.com/file/d/0BzpiEtMtHC3rWU5tQzZTeUFfTG8/view), nor display any data errors/warnings. This can be a future enhancement.

Fixes #319

---

cadasta/config/permissions/data-collector.json
cadasta/config/permissions/org-admin.json
cadasta/config/permissions/org-member.json
cadasta/config/permissions/project-manager.json
cadasta/config/permissions/superuser.json
cadasta/party/models.py
cadasta/party/tests/test_models.py
cadasta/party/views/api.py
cadasta/party/views/mixins.py
cadasta/spatial/models.py
cadasta/spatial/tests/test_models.py
cadasta/spatial/views/api.py
cadasta/spatial/views/mixins.py
requirements/common.txt

@oliverroick and @wonderchook Could you review the permissions policies (in `cadasta/config/permissions`) to check that they tally with what you think different classes of user should be able to do?  I had to update a number of things, and I think it's now consistent and sensible, but it would be good for someone else to take a look.
By the way, you can get a full list of all the actions that are registered with tutelary by doing the following in the VM:
```
cd /vagrant/cadasta
./manage.py shell
from tutelary.engine import Action
print('\n'.join(sorted([str(a) for a in Action.registered])))
```
I've also had to comment out one method in the party relationships stuff to get the test coverage to 100%,  just because there's no UI to test that stuff against yet, so there's no way to exercise …

Fix permissions policies and tests (fixes #303)

---

cadasta/core/models.py
cadasta/organization/forms.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_serializers.py
cadasta/organization/views/default.py

- Add `allow_unicode=True` option to all `slugify()` calls
- Add a few unit tests to check that this option is being applied

Fix #327: Allow Unicode slugs

---

cadasta/organization/tests/test_downloads.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/party/tests/test_views_default.py
cadasta/questionnaires/tests/test_attr_schemas.py
cadasta/questionnaires/tests/test_managers.py
cadasta/questionnaires/tests/test_serializers.py
cadasta/questionnaires/tests/test_views_api.py
cadasta/resources/forms.py
cadasta/resources/models.py
cadasta/resources/tests/factories.py
cadasta/resources/tests/test_forms.py
cadasta/resources/tests/test_managers.py
cadasta/resources/tests/test_mixins.py
cadasta/resources/tests/test_models.py
cadasta/resources/tests/test_serializers.py
cadasta/resources/tests/test_views_api.py
cadasta/resources/tests/test_views_default.py
cadasta/spatial/tests/test_views_default.py
cadasta/templates/resources/form.html
requirements/common.txt

Upgrades django-buckets to 0.1.10, which fixes S3 upload

Fixes #347

---

cadasta/accounts/load.py
cadasta/accounts/models.py
cadasta/config/permissions/data-collector.json
cadasta/core/fixtures.py
cadasta/core/tests/test_views_default.py
cadasta/core/views/default.py
cadasta/core/views/generic.py
cadasta/core/views/mixins.py
cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/tests/test_views_default_users.py
cadasta/organization/views/default.py
cadasta/organization/views/mixins.py
cadasta/templates/core/base.html
functional_tests/base.py
functional_tests/pages/Dashboard.py
functional_tests/projects/test_project_list_contents.py
functional_tests/users/test_page_access.py
requirements/common.txt

This required adding a "superuser check" mixin to many of the view classes.  That turned up a problem in django-tutelary that meant that the superuser checks added in the mixin slowed the platform down a lot.
The tutelary bug was fixed and the tutelary version bumped here to take account of that.

Fix for #205: "Users" menu visibility

---

cadasta/core/models.py
cadasta/core/tests/test_models.py
cadasta/core/util.py
cadasta/organization/forms.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_serializers.py
cadasta/organization/views/default.py

Slugs are only allowed to have the maximum length specified in the `SlugField` field, with uniqueness maintained at the same time as the length constraint.

Fix #328: Slug length control with custom slugify

---

cadasta/party/forms.py
cadasta/party/tests/test_forms.py
cadasta/party/tests/test_views_default.py
cadasta/party/views/default.py
cadasta/spatial/forms.py
cadasta/spatial/tests/test_forms.py
cadasta/spatial/tests/test_views_default.py
cadasta/spatial/views/default.py
cadasta/templates/party/party_detail.html
cadasta/templates/party/party_form.html
cadasta/templates/party/relationship_detail.html
cadasta/templates/party/relationship_edit.html
cadasta/templates/spatial/location_detail.html
cadasta/templates/spatial/location_form.html
cadasta/templates/spatial/relationship_add.html
requirements/common.txt

- Adapts forms and templates for spatial units, parties and tenure relationships
- Upgrade jsonattrs dependency to version 0.1.1

Adds JOSN  attributes to UI

---

cadasta/organization/forms.py
cadasta/resources/forms.py
requirements/common.txt

- Upgrades django-buckets to 0.1.11, which introduces client-side file type validation
- Adapts questionnaire and resources forms by add `accepted_types` to the file upload widget

Fixes #374 -- Check mime type of uploaded file

---

cadasta/spatial/views/default.py
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_map.html

- If the project extent exists, add it to the add location page map and fit it to the map view (fixes #276)
- Apply Leaflet workaround to ensure locations fit into the map view (fixes #377)

Fixes #276 and #377

---

cadasta/core/management/commands/loadeverything.py
cadasta/core/management/commands/loadsite.py
cadasta/core/tests/test_management_commands.py
provision/roles/cadasta/application/tasks/main.yml

added `loadeverything` command which runs:
```
loadsite
loadcountries
loadpolicies
loadfixtures(delete=false)
```
It can be run after dropping the database and migrating.

Fixes #387: new command to replace default site object

---

cadasta/core/mixins.py
cadasta/core/tests/test_mixins.py

The following case leads to a redirect loop:
- The user is not authenticated. 
- The user tries to access a page that requires authentication.
- The server redirects to the login page.
- The user authenticates themselves and is redirected to the original page.
- The user does have the required permissions on the original page and is redirected to the referrer, in this case the login page.
- Because the user is now authenticated, the login page again redirects to the original page. The redirect loop is entered.
This PR solves this issue by checking if the referrer is the login page and if a user is authenticated. The redirect as adapted based on the page the user tried to access:
- If the page is below the project dashboard level, the redirect points to the project dashboard.
- If the page …

Fixes #369 — Fixes permission denied redirects

---

cadasta/config/wsgi.py

Attempt to fix these Unicode errors by explicitly setting the locale in the Python WSGI startup script.

Fix the Unicode!

---

cadasta/templates/organization/project_add_wrapper.html
functional_tests/pages/ProjectAdd.py
requirements/common.txt

- Bumps django-buckets to 0.1.13, which adds UI improvements for file uploads
- Changes submit `input` to `button` so it can be disabled while file upload is ongoing

Improve upload handling of resources

---

functional_tests/pages/ProjectList.py

Geometry drawing in add project tests is not robust to changes in the
aspect ratio of the map widget.  The test data is randomised, leading to
random test failures.  Just disabling the relevant failing part of the
test for now.

Quick fix for functional test

---

cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py

This PR fixes #414, which also contains the explanation of the root cause of the bug. Changes:
- Removes unnecessary `slugify()` call in the `ProjectAddWizard.done()` method
- Adds a unit test to catch the bug and confirm the bug fix

Fix #414: Remove unnecessary slugify() call

---

cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py

The error occurs when an invalid form is submitted, and the template tries to render error messages of all form fields. This fails because of a bug inside `ContactsForm.full_clean()`. `self._errors' is not set when the contact record is removed. 
This PR fixes the issue by ensuring `self._errors` is set in all cases.

Fixes #315 -- Set _errors when contact is removed

---

provision/roles/testing/files/squid.conf

This might fix some of these intermittent timeouts we've been seeing in the functional tests on Travis.

More aggressive Squid caching for external URLs

---

cadasta/config/urls/default.py
requirements/common.txt

Fixed by switching to drfdocs-cadasta, which includes a fix for nested URLs.

Fix #134: DRF docs and API versions

---

cadasta/config/settings/dev_debug.py
cadasta/runserver
requirements/dev.txt

Fixes issue 489.  You can now do "./runserver --debug", and the Django debug toolbar will be loaded, giving you performance information on every page view.  (I'll document this in the development newsletter when it's merged.)

Add support for Django debug toolbar

---

cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py
cadasta/organization/views/mixins.py
cadasta/templates/organization/organization_dashboard.html
cadasta/templates/organization/organization_wrapper.html
cadasta/templates/organization/project_wrapper.html
functional_tests/base.py
functional_tests/organizations/test_organization.py

Fix 183: project page ellipsis menu visibility
Fix 184: add project organisation filtering
Fix 185: display of project add button
(Some of the code added here will be cleaned up and rationalised as part of #485.)

Fix user-based UI element visibility issues

---

cadasta/core/static/js/map_utils.js
cadasta/templates/spatial/location_wrapper.html

- Make the project extent not look like a link on the map
- Make the current location not link to itself on the map
Here's how the second point looks like:

Fix #406 and #325

---

ansible.cfg
provision/roles/cadasta/application/tasks/main.yml
provision/roles/cadasta/development/tasks/main.yml
tox.ini

Use --find-links option to preferentially pull PIP packages from the
wheelhouse in the cadasta-wheelhouse S3 bucket (maintained by the code
in the Cadasta/wheelhouse repo).
For the moment, keeping the requirements files consistent between the
main repo and the wheelhouse repo has to be done manually, but this is
not a problem because PIP is conservative, in the sense that if it
doesn't find a package in the wheelhouse it will just download it via
the main package index.

Set up to use wheelhouse for PIP packages

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

This PR adds two templates that will be shown when contributors open new issues or pull requests. 
It would be great if a native speaker can check the wording.
@amplifi — Can you please check the PR template and let me know if we should collect any more information that is of value for Ops

Add templates for new issues and pull requests

---

cadasta/config/settings/test.py
cadasta/core/tests/util.py
cadasta/organization/tests/test_downloads.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/party/tests/test_views_default.py
cadasta/pytest.ini
cadasta/questionnaires/tests/test_attr_schemas.py
cadasta/questionnaires/tests/test_managers.py
cadasta/questionnaires/tests/test_serializers.py
cadasta/questionnaires/tests/test_views_api.py
cadasta/resources/forms.py
cadasta/resources/models.py
cadasta/resources/tests/factories.py
cadasta/resources/tests/test_fields.py
cadasta/resources/tests/test_forms.py
cadasta/resources/tests/test_managers.py
cadasta/resources/tests/test_mixins.py
cadasta/resources/tests/test_models.py
cadasta/resources/tests/test_serializers.py
cadasta/resources/tests/test_views_api.py
cadasta/resources/tests/test_views_default.py
cadasta/resources/tests/test_widgets.py
cadasta/resources/tests/utils.py
cadasta/spatial/tests/test_views_default.py
cadasta/xforms/tests/test_serializers.py
cadasta/xforms/tests/test_views_api.py
requirements/common.txt
runtests.py

- Bump django-buckets to 0.1.15
- Ensures that all necessary directories are created at run time (Fixes #434).
- Make S3UploadWidget default for S3FileFields
- Makes file handling consistent across all tests. Two pytest fixtures are added that create directories and delete files after before and after tests if necessary.
- Adds new test settings. Test settings adopt all dev settings; only the `MEDIA_ROOT` location is overwritten, so tests use a directory different from the dev server. Files uploaded to the dev server will not be removed anymore.
- Removes explicit `file` field declaration from `resources.forms`.
- Adds accepted types to resource models.
PR can be merged immediately.
Low risk. Nothing I am aware of.
- @oliverroick will document the use of the new pytest fixtures for file …

Improved handling of resource files

---

cadasta/core/static/css/main.css
cadasta/core/static/css/main.scss
cadasta/core/static/css/single.scss
cadasta/party/views/default.py
cadasta/resources/tests/test_views_default.py
cadasta/resources/views/default.py
cadasta/resources/views/mixins.py
cadasta/spatial/views/default.py
cadasta/templates/party/party_detail.html
cadasta/templates/party/relationship_detail.html
cadasta/templates/party/relationship_resources_add.html
cadasta/templates/party/relationship_resources_new.html
cadasta/templates/party/resources_add.html
cadasta/templates/party/resources_new.html
cadasta/templates/resources/modal_add_lib.html
cadasta/templates/resources/modal_upload.html
cadasta/templates/resources/project_add_existing.html
cadasta/templates/resources/project_add_new.html
cadasta/templates/resources/project_list.html
cadasta/templates/spatial/location_detail.html
cadasta/templates/spatial/resources_add.html
cadasta/templates/spatial/resources_new.html

- Make adding resources to projects, locations, parties, and relationships use modals consistently:
- Add two new templates: **resources/modal_add_lib.html** and **resources/modal_upload.html**
- Use these two new templates as a template for the 8 resource-adding/uploading templates
- Add a tab bar to these modals to switch between adding a resource from the library or uploading a new resource
- Resolve #295:
- Remove the tab bar mentioned above from the upload resource modals if there are no resources in the library
- The changes above are facilitated by adding a `project_has_resources` context variable to all affected views, where the attribute is true if there are any resources belonging under the project
- Update the view unit tests to reflect the new context variable
- Resolve #407: …

Resolve #295 and #407: Improve the UI/UX in adding/uploading resources

---

.travis.yml
cadasta/config/settings/default.py
cadasta/config/settings/dev.py
cadasta/config/settings/travis.py
provision/roles/cadasta/application/tasks/main.yml

Change the URL for the OSM tile server in the default settings to be an HTTPS URL instead of HTTP.  Add code to the development and Travis settings to make these environments still use HTTP URLs for OSM tiles.  (Rationale: @amplifi has now set up HTTPS on our production and production-like environments, and loading OSM tiles from the HTTP servers thus triggers a "page has insecure content" warning in the browser.  This change fixes that.  However, in development and staging, we use the Squid web cache to make sure that we only hit the OSM servers once for each tile that we need.  This is particularly important during functional testing, because we experienced multiple intermittent errors in the past because of throttling of requests on the OSM end.  Caching HTTPS requests appears to be …

Make OSM tile access be over HTTPS

---

.travis.yml
cadasta/organization/download/base.py
cadasta/organization/download/shape.py
cadasta/organization/download/xls.py
cadasta/organization/forms.py
cadasta/organization/tests/test_downloads.py
cadasta/organization/tests/test_forms.py
cadasta/templates/organization/download/shp_readme.txt
cadasta/templates/organization/project_download.html
provision/roles/cadasta/application/tasks/main.yml
requirements/common.txt

- Implements #323 
- Add GDAL/OGR installation via Ansible
- Introduces `organization.download.shape.ShapeExporter`, which exports project data to shapefile format.
- Introduces `organization.download.base.Exporter` class for common export functionality. Both `organization.download.shape.ShapeExporter` and `organization.download.xls.XLSExporter` extend this class.
- Adds shape export option to forms and templates
This PR can be merged immediately. We should, however, check the following:
None/low risk.
- The installation of GDAL/OGR alongside PostGIS 2.1 can be problematic. I added the necessary steps to the Ansible playbook. We should test if GDAL/OGR installs correctly on our AWS instances before we roll out shape file export to production (/cc @amplifi)

Add SHP download

---

cadasta/core/form_mixins.py
cadasta/organization/forms.py
cadasta/organization/views/default.py
cadasta/organization/views/mixins.py

Refactor in-view permissions checking used for control of UI element visibility.
- Introduce permissions checking mixins for views to determine whether the requesting user is an administrator of a particular organization, or is allowed to create projects (either in a particular organization or in any organization).
- Introduce a superuser checking mixin for forms (in `core/form_mixins.py`).
Fixes #485
Any time.
Low to no risk.
None.

Refactor permissions checks (fixes #485)

---

cadasta/organization/views/default.py
cadasta/organization/views/mixins.py
cadasta/party/views/default.py
cadasta/resources/views/default.py
cadasta/spatial/views/default.py

Add mixins to some project views to ensure that the ellipsis menu remains visible on all the pages where it's appropriate.
Fixes #520
No risks.
No follow-up actions.

Fix #520: ellipsis menu visibility

---

cadasta/organization/forms.py
cadasta/organization/migrations/0002_unique_org_project_names.py
cadasta/organization/models.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_serializers.py
cadasta/organization/views/default.py
functional_tests/pages/Project.py
functional_tests/pages/ProjectAdd.py
functional_tests/projects/test_project_add.py
functional_tests/projects/test_project_add_duplicate.py

- Resolve #324:
- Add `unique=True` to the `name` field of the `Organization` model
- Add a `unique_together` constraint for the `organization` and `name` fields of the `Project` model 
- Generate the migration script for the above data model changes, and then modify the script to add two `RunPython` operations to deduplicate existing data, if any, in the database, one for organization names and the other for project names. The deduplication is based on the `SlugModel` algorithm. This migration script was manually tested by running it against the development environment database with the following test data:
- Two organizations with the same name; expected change is that one of the organizations will have " 1" appended to its name
- Two projects in the same organization with the same …

Resolve #324: Prevent duplicate org and project names

---

cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py

- Fix #528:
- Include missing `contacts` argument in the `Project.objects.create()` call in `ProjectAddWizard.done()`
- Modify 3 unit tests to catch this bug and confirm that it has been fixed
Anytime.
None.

Fix #528: Include contacts when adding a project

---

cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py
cadasta/templates/organization/project_add_details.html
functional_tests/pages/ProjectAdd.py
functional_tests/projects/test_project_add.py

- Add code to save form data when "Previous" button is pressed in add project wizard to ensure that field values are saved whatever steps the user takes through the wizard.  (By default, the form wizard that we are using only saves form data when transitioning between forms in the "normal" direction.  Special actions need to be taken if data is to be saved when switching back to a previous form.)
Fixes #530
None.
None.

Fix #530: add project wizard data preservation

---

provision/roles/testing/tasks/main.yml

We need to install Firefox in the development VM for functional testing.  I've been having problems with the main Firefox FTP site this morning, so I uploaded a copy of the relevant install bundle to our `cadasta-miscellaneous` S3 bucket and updated the provisioning scripts to get the bundle from there.
Any time.
No risks.
None.

Firefox for testing from S3 bucket

---

cadasta/core/static/css/main.css
cadasta/core/static/css/wizard.scss
cadasta/templates/organization/project_add_details.html
cadasta/templates/organization/project_add_permissions.html

- Reorder "Previous" and "Next" buttons on project add wizard pages to make "Next" button be the default submit button for the forms.
- Add CSS to make the "Previous" button appear to the left of the "Next" button.
Any time.
No risks.
None.

Fix #525: "Next" button is default in wizard steps

---

cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py
functional_tests/organizations/test_organization_list.py

- Fix #463: 
- Fix the “Item 0 in the array did not validate: ” error message by overriding the default `item_invalid` error message of `SimpleArrayField` with an empty string.
- Fix the erroneous error when entering a URL like “cadasta.org” by removing the unnecessary `to_list()` and `clean_urls()` methods in `OrganizationForm`. `URLField` can handle URLs like these and coerce them into valid HTTP URLs.
- Add unit tests to check for the above bugs and to confirm that they are fixed
- Add other unit tests related to URLs
- Fix 1 functional test
- Perform some DRYing of the affected unit tests
Anytime.
None.

Fix #463: Make URL errors more meaningful

---

functional_tests/pages/Login.py
functional_tests/projects/test_project_add.py
functional_tests/users/test_page_access.py

This is an attempt to make the functional tests on Travis a bit more reliable.  I believe that the reason things have been failing intermittently, almost exclusively on the login page, was because we were using the presence of an alert to indicate that the login was successful.  Since the "OK" alerts now disappear on a timer, it's possible for the login to work, and the alert to appear and disappear before Selenium gets around to checking it.  The test then times out.
I've changed the post-login check to look for permanent page features instead: for most pages, this is the `dashboard-map` DIV, but it's possible to override this in the `login` method of `LoginPage` (which is needed for cases with post-login redirections).
Immediately.
None: it can't make anything worse!
Bask in the glow of …

Try to make functional tests more reliable

---

cadasta/core/static/css/main.css
cadasta/core/static/css/main.scss
cadasta/spatial/tests/test_widgets.py
cadasta/spatial/widgets.py
cadasta/templates/spatial/relationship_add.html

- Resolve #441:
- Use [Select2](https://select2.github.io/) to convert the table of selectable parties used in creating a new tenure relationship into a searchable select box. Select2 was used instead of [Selectize](https://selectize.github.io/selectize.js/) that was suggested by @clash99 because Select2 has its CSS and JS files hosted on a [CDN](https://cdnjs.com/about). Both support the features that we might want in a party selection widget and it's easy to switch to Selectize if that is desired.
- Update the `SelectPartyWidget` widget to output `<select>` instead of `<table>`.
- Update the `NewEntityWidget` widget to show the "Add party" button as a button instead of as a link, and to make the button text translatable.
- Update the **relationship_add.html** template to load Select2 …

Resolve #441: Improve relationship party selection widget

---

cadasta/templates/organization/organization_dashboard.html

- Resolve #510 by adding some overview text for an organization which has no public projects yet to a user who is not an org admin.
- Made all text on the **organization_dashboard.html** template translatable. (Well, it was just one text.)
Anytime.
None.
No actions needed.

Resolve #510: Improve messaging on orgs with no projects

---

provision/roles/webserver/production/templates/nginx-production

Forces redirect from http to https for all platform and API URLs, as per #551 
-
Anytime -- provisioning template update only; no impact to current platform code
-
None
-
None; change has already been deployed to staging, demo, & production envs
-

Update template to force SSL for all platform and API URLs

---

cadasta/templates/organization/project_edit_geometry.html
cadasta/templates/organization/project_wrapper.html

- Resolve #596:
- Replace user-facing "location" text with "boundary" when referring to the project boundary.
- (I've checked and there are no user-facing texts that use "extent" to refer to the project boundary.)
- Make one user-facing text translatable
During Sprint 7 code freeze.
None.

Resolve #596: Use "boundary" instead of "location"

---

cadasta/templates/core/base.html

This embeds player for inline manual that will only be effective on demo.cadasta.org
As soon as possible - we need it for this sprint release.
I don't see any errors occurring on my host site so I don't think it should affect anything although there will be no benefits outside of the demo site.
- I will be creating tutorials in inlinemanual.com and once complete, should be able to publish from within there.  
- We should leverage people tracking and analytics options within inlinemanual.
- Consider using a standalone player download.  Spoke with @amplifi and with upbeat we will be able to track differences in page load times and focus on issues as they arise.

Embedded player for demo site

---

requirements/common.txt

Update `django-jsonattrs` version to 0.1.8.  (May help to fix a couple of attributes problems, like https://github.com/Cadasta/cadasta-platform/issues/592).
Any time.
Low to none.
Retest outstanding attribute-related issues.

Update django-jsonattrs to version 0.1.8

---

cadasta/resources/tests/test_views_default.py
cadasta/resources/views/default.py
cadasta/templates/resources/edit.html

- Fix #594:
- Change the edit resource form's cancel button URL to use the `get_success_url()` URL of the same view.
- Add 2 unit tests and update the unit test framework.
- Remove the unnecessary extra error messages that appear. (I don't think the edit resource form has any non-field-specific errors.)
Before Sprint 7 release.
None.

Fix #594: Correct edit resource cancel button URL

---

cadasta/spatial/forms.py
requirements/common.txt

Bump the version of django-jsonattr to 0.1.9, which removes the length restriction of attribute character fields in forms.  This fixes #557.
Right away.
Shouldn't be any, though it's not particularly well tested, obviously.
Make sure everything still works.

Bump django-jsonattr version

---

cadasta/accounts/load.py
cadasta/accounts/management/commands/loadpolicies.py
cadasta/core/management/commands/loadstatic.py
cadasta/core/tests/factories.py
cadasta/core/tests/util.py
cadasta/geography/management/commands/loadcountries.py
cadasta/party/management/commands/loadtenurereltypes.py
cadasta/party/models.py
provision/aws-deploy.yml
provision/roles/data/tasks/main.yml
requirements/common.txt

- Reinstate commented code in `loadstatic` management command.
- Add a `--force` flag to the `loadstatic` management command.  If static data database entities already exist, `loadstatic` will not make any changes unless this flag is supplied.
- Bump `django-jsonattrs` version to 0.1.10 to pick up version with `force` flag in attribute type loading.
- Reinstate `data` provisioning role for development only to ensure that newly created development VMs have the appropriate static data loaded.
Any time.
Low to none, but reviewer (@amplifi) should check that the Ansible provisioning steps that will run during deployment and redeployment will produce the expected results.  In particular, the `loadstatic` command is now *not* run from the `aws-deploy.yml` Ansible playbook, so static data …

Tidy up provisioning and loadstatic thing

---

cadasta/organization/serializers.py
cadasta/organization/tests/test_serializers.py
cadasta/organization/tests/test_views_api_organizations.py
cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/views/api.py

- Fix #603 (deleting a user from an organization also deleted the user): delete the relevant `OrganizationRole` object instead of the user object (also for `ProjectRole`).
- Fix #608 (all new organization users were set up as admins): correct the incompatibility in `EntityUserSerializer` caused by some models using roles that are strings (`ProjectRole`) and some using boolean roles (`OrganizationRole`) -- just convert string values of "`false`" or "`False`" to boolean `False`. 
Any time.
None.
None.

Fix organization users API issues

---

cadasta/config/settings/production.py

Updates settings template with configuration for email notifications. Emails to platform-admin@cadasta.org are triggered on unhandled exceptions and xform submission errors using Django's native AdminEmailHandler.
Anytime
None; already in place on demo and prod environments. Provisioning template update only.
None

Add email notifications for unhandled exceptions and xform submission errors

---

cadasta/accounts/load.py
cadasta/accounts/management/commands/loadpolicies.py
cadasta/config/permissions/default.json
cadasta/core/management/commands/loadstatic.py
cadasta/core/tests/factories.py
cadasta/core/tests/test_management_commands.py
cadasta/spatial/tests/test_views_api_spatial_units.py
cadasta/spatial/tests/test_views_default.py
cadasta/spatial/views/api.py
cadasta/spatial/views/default.py
tox.ini

- Fix #590.
- Add the `spatial.list` permission for all public projects to the `default.json` policy file.
- Add the capabilty to force reloading of tutelary policies from JSON documents to the `loadstatic` command.  Running `./manage.py loadstatic --update-policies` will update the policies stored in the database from the JSON policy files.  (A server restart is needed after this to pick up the new policies from the database.)
- Update spatial unit list API to use correct permissions: the user must have the `spatial.list` permission on the project and must be able to view the project (so must have the `project.view` or `project.view_private` permission, depending on whether the project is public or private).
- Update tests to take account of the fact that anonymous users can now list …

Fix #590: spatial unit visibility

---

cadasta/organization/forms.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_views_api_organizations.py
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/views/api.py
cadasta/organization/views/default.py
cadasta/templates/organization/organization_members_edit.html
functional_tests/organizations/test_organization_member.py
functional_tests/pages/OrganizationMember.py

- Fixes #548
- Org admins can no longer delete themselves from their organization (UI or API)
- Org admins can no longer change their own permission in the organization (UI or API)
- Org admins will now have to be deleted/demoted by a superuser or another admin in the organization.
Whenever.
- None
- Some changes to the API, so the documentation of errors needs to be updated, but not sure if it's worth it until the great API clean-up.

Admin users can no longer delete/demote themselves

---

cadasta/core/static/css/main.css
cadasta/core/static/css/main.scss
cadasta/core/static/js/rel_new_item.js
cadasta/spatial/forms.py
cadasta/spatial/tests/test_views_default.py
cadasta/spatial/views/default.py
cadasta/spatial/widgets.py
cadasta/templates/spatial/relationship_add.html

- Resolve #612:
- In the `TenureRelationshipAdd` view, provide initial `new_entity` `kwargs['initial']` data for the unbound `TenureRelationshipForm` based on whether the project has parties or not.
- Add the conditional `hidden` class in the **spatial/relationship_add.html** template for the `select-party` sub-form based on this initial `new_entity` data. This hides the party picker and the “Add party” button if there are no parties yet.
- Improve `TenureRelationshipForm`:
- Make `new_entity` the first field because the required-ness of the other fields depend on `new_entity`. This enables us to properly use `self.cleaned_data.get('new_entity', None)` instead of `self.data.get('new_entity', None)`.
- To help resolve #445, add a blank first choice in the party picker widget, and wrap the …

Resolve #612: Don’t show party picker if there are no parties

---

cadasta/config/settings/default.py

The live API endpoints provided by the DRF Docs tool that live at `/api/v1/docs` need to provide a way of setting up HTTP headers to provide an authentication token (by setting an `Authorization` header to say `Token <token-value>`).  This is because of some default settings in the DRF Docs setup.  This PR changes those settings to force DRF Docs to provide a way of setting headers for all the live API endpoints. 
I believe that this can be merged at any time, but I'd like for @linzjax and @oliverroick to take a look at it first.
Low to none.
None.

Force DRF Docs to provide Headers input

---

cadasta/core/static/css/main.css
cadasta/core/static/css/main.scss
cadasta/templates/core/base.html
cadasta/templates/organization/project_add_details.html
cadasta/templates/organization/project_add_permissions.html
cadasta/templates/organization/project_edit_details.html

- Add instruction text and links to sample forms for questionnaire section of project add and edit forms.
- Whenever convenient, for sprint 8.
- None foreseen.
- As sample forms are updated, upload to cadasta-resources s3 bucket and make name generic to replace current form.
----------------------------------------------------------------------------------------------------------
Questionnaire text added
Edit page, also contained width for wizard to not be fluid
Updated links
Updated label
Removed link target

Changes for adding new project details questionnaire

---

cadasta/core/static/css/main.css
cadasta/core/static/css/main.scss
cadasta/party/forms.py
cadasta/party/tests/test_forms.py
cadasta/spatial/forms.py
cadasta/spatial/tests/test_forms.py

- Adjust min-width size css for reg buttons in header
- When convenient, for sprint 8
- Once released to staging, qa in mobile safari browser

Safari fix for header menu in small screens

---

cadasta/config/permissions/org-admin.json
cadasta/config/permissions/project-manager.json
cadasta/organization/forms.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py
cadasta/questionnaires/managers.py
cadasta/questionnaires/tests/test_managers.py
cadasta/questionnaires/tests/test_views_api.py
cadasta/spatial/views/default.py
cadasta/templates/organization/project_add_details.html

Fixes #272 
Errors in parsing XLSForms are now handled as validation errors in the project creation wizard. This PR also fixes inconsistencies in spelling of `questionnaire` throughout the platform.
Immediately
None
Policies will need to be updated the next time the platform is deployed by running:
`./manage.py loadstatic --update-policies`

Fixing #272

---

cadasta/config/urls/default.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_urls_api.py
cadasta/organization/tests/test_views_api_organizations.py
cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/urls/api/organizations.py
cadasta/organization/views/api.py
cadasta/organization/views/mixins.py
cadasta/party/serializers.py
cadasta/party/tests/test_serializers.py
cadasta/party/tests/test_views_api_parties.py
cadasta/questionnaires/tests/test_urls_api.py
cadasta/questionnaires/tests/test_views_api.py
cadasta/questionnaires/views/api.py
cadasta/spatial/serializers.py

This PR adds some tidying to the API; fixes #447. 
- Change questionnaire URL patterns and corresponding view to use project slug instead of project ID to identify project. 
- Make `PartySerializer` consistent with all other entity serializers; the project is now provided via the serializer context
- Change organization URL patters to use `organization` keyword instead of `slug` to be consistent with all other endpoints.
- Introduce `NestedProjectSerializer`, which replaces `ProjectSpatialUnitSerializer` and is also applied to `PartySerializer`
- Remove serialization of `relationships` for `PartySerializer` and `SpatialUnitSerializer`.
Anytime
None.
None.

API cleanup

---

.eslintrc
cadasta/config/settings/default.py
cadasta/resources/models.py
cadasta/resources/tests/files/invalidgpx.xml
cadasta/resources/tests/test_models.py

- Add _audio/mp3_ and _audio/mpeg_ to _MIME_LOOKUPS_ in default settings
- Tighten up mime-type checking for GPX uploads
- Add exception handling for _GDALExceptions_
- Updated tests
- Add _.eslintrc_ which was removed in previous commit
Immediately
None
None required

Fixes #669, #670 and #671

---

cadasta/core/serializers.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/views/api.py

There are two parts to this:
1. The test is a bit funny, because it didn't create any projects.  When there are no objects to test permissions against, tutelary pretends that there's a `None` object, and that gives a 403.  When there are project instances around, the permissions checking works and you get a 200 and a project list as the result.  I've split the test into "no projects" and "has projects" cases.
2. The `users` field appearing in the project list results came from a problem with the `DetailSerializer` class.  This serializer mixin is intended to remove specific fields from model instance serialization results in "non-detail" views.  For a view that returns a list of objects of a model class that has a `DetailSerializer` mixin, detail-only fields (specified by a `Meta` option) …

Fix #642: anonymous users can view full project list

---

cadasta/templates/allauth/account/password_reset_done.html
cadasta/templates/allauth/account/verification_sent.html
cadasta/templates/allauth/account/verified_email_required.html

- Insert link to email into "contact us" phrases.
See https://github.com/Cadasta/cadasta-platform/issues/631
Anytime
None
Proceed with translation in Transifex

[v2] Insert link to email into "contact us" phrases

---

cadasta/accounts/models.py
cadasta/accounts/tests/test_forms.py
cadasta/templates/organization/organization_members.html
cadasta/templates/organization/organization_members_edit.html

- Fixes #626.
- If a user's full name is empty, display the username instead in the organization members list and organization members edit views.
No Precondtions
No Potential Risks

Fix for show username in member permissions page

---

cadasta/config/settings/default.py
cadasta/resources/models.py
cadasta/templates/resources/form.html

- Added tif to accepted mime types
- Forced default icon for tiff files since preview is inconsistent for this file type
- Updated acceptable file type note to reflect recent changes
- As soon as possible - for Sprint 8
- None
---------------------------------------------------------------------------------
Completes #668 
Added to mime type and forced default preview icon
Updated acceptable file types text
For resource file uploads

Tiff default icon used for preview image

---

cadasta/spatial/forms.py
cadasta/spatial/tests/test_forms.py

- Fix #598
- Filter "Project extent" spatial unit type from the location type dropdown in the location form.
Any time.
None.
None.

Filter "Project extent" from location types

---

cadasta/organization/tests/test_views_api_organizations.py
cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/views/api.py
requirements/common.txt

This PR added permission-based filters (e.g. `GET /projects/?permission=party.create`) to selected API endpoints.
- Update requirements (django-tutelary==0.1.19)
- Add tutelary's `PermissionsFilterMixin` to the following views (Adding this functionality to other API endpoints is more or less straightforward.):
- `organization.views.api.OrganizationList`
- `organization.views.api.OrganizationProjectList`
- `organization.views.api.ProjectList`
- Resolved an issue in `OrganizationProjectList`, where `get_perms_objects` interfered with `PermissionsFilterMixin`.
Anytime
Very low risk
N/A

Add permissions filtering

---

cadasta/xforms/mixins/model_helper.py
cadasta/xforms/tests/files/test_resources.py
cadasta/xforms/tests/test_views_api.py

- Users can now add as many resources to a party/location/tenure relationship as they want.
- If a question submitted has an id that starts with `location_resource`, `party_resource`, or `tenure_resource`, it is automatically sorted and attached to the appropriate object.
- i.e. `tenure_resource_photo`, `party_resource_audio` 
- `party_photo` and `location_photo` are still in place so that old questionnaires will still work.
- Fixes #553 
Whenever.
- None
- Update questionnaire documentation to reflect changes.

Allows multiple resources to be attached to objects uploaded through ODK

---

uwsgi.ini

Changes uWSGI worker process timeout (harakiri) from 20 seconds to 60 seconds. This mitigates questionnaire upload failure on slower connections.
Anytime; this is a deployment-only change that is already in place on staging, demo, and prod.
None
None

Extend worker process timeout from 20s to 60s

---

cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py
cadasta/spatial/forms.py
cadasta/spatial/tests/test_forms.py
cadasta/templates/organization/project_add_details.html
functional_tests/pages/Organization.py
functional_tests/pages/ProjectAdd.py
functional_tests/projects/test_project.py
functional_tests/projects/test_project_add.py
functional_tests/projects/test_project_list_access.py
runtests.py

- Resolve #445:
- Please refer to [this comment](https://github.com/Cadasta/cadasta-platform/issues/445#issuecomment-248228338) to see which dropdowns are proposed to be modified, are already modified before, and won't be modified in this PR.
- Add a blank default choice for the organization selection form field when adding a new project, except when the number of orgs to be selected is just 1. In addition, if the user has already validly chosen an org by successfully going to step 3 of the add project wizard, going back to step 2 will no longer include the blank choice in the dropdown.
- Update the `ProjectAddDetails` form initialization to add the blank choice.
- Remove the now unnecessary `init_org_logo` and `init_org_hidden` wizard view context variables.
- Achieve the going-back …

Resolve #445: Add blank defaults for dropdowns

---

cadasta/config/settings/default.py

- Resolve #716:
- Add DigitalGlobe's +Vivid imagery and the variants with OSM with proper attributions.
- Update the OSM attribution to refer to ODbL instead of CC-BY-SA.
- Make the layer labels and DigitalGlobe attribution translatable.
A translation string is modified. The change is i18n-invariant in Latin scripts (changing CC-BY-SA to ODbL) so any existing translations should be rescued first.
None foreseen.
A few new translation strings are added (DigitalGlobe attribution and layer labels). These should be translated.

Resolve #716: Add DigitalGlobe Vivid layer

---

cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py

- Fix #674:
- Filter the resource count queryset with `filter(archived=False)`.
- Add a unit test for this, and update the `ProjectDashboardTest` unit test class to complete the template context.
Anytime.
None foreseen.
None.

Fix #674: Fix resource count on project dashboard

---

cadasta/organization/fields.py
cadasta/organization/tests/test_widgets.py
cadasta/organization/widgets.py

Fixing https://github.com/Cadasta/cadasta-platform/issues/632

---

cadasta/config/settings/dev.py

- Add `SASS_PROCESSOR_ROOT` setting to development VM settings.
- This fixes a problem introduced by removing the spurious `STATIC_ROOT` setting we used to have in the development settings.  The Django package we're using for SASS processing was looking for its output files (to check whether they were out of date) either in `SASS_PROCESSOR_ROOT` or, if that wasn't set, in `STATIC_ROOT`.  Taking out the `STATIC_ROOT` setting broke the SASS compilation. 
Any time.
None.
None.

Make SASS compilation work in dev VM again

---

cadasta/core/static/js/map_utils.js
cadasta/templates/organization/project_edit_geometry.html
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_edit.html
cadasta/templates/spatial/location_form.html

- Resolve #556:
- *Overview:* Editing project boundaries and location geometries will be made simpler because the user does not have to click as much:
- When the geometry edit page loads, the Leaflet.draw editing mode will be enabled automatically so that the geometry is immediately editable. This will be done by dispatching the "click" event on the "Edit" button on the map toolbar.
- When the user clicks the big "Save" button on the page, any changes to the geometry will be automatically saved as well. This will be done by dispatching the "click" event on the small "Save" button on the map toolbar if it is still visible.
- Add `enableMapEditMode` and `saveOnMapEditMode` functions to **core/static/js/map_utils.js**. These take care of two behaviors described above respectively.
- Add …

Resolve #556: Improve geometry editing UI

---

.travis.yml

- Removes postgis-2.1 from travis script, because it broke the builds and we overwrite it with postgis-2.2 anyway
ASAP
None
- Everyone should rebase after this is merge, otherwise builds of feature branches will continue to fail

Remove postgis-2.1 from .travis.yml

---

provision/roles/webserver/production/tasks/main.yml
provision/roles/webserver/production/templates/uwsgi.ini

Updates the Ansible deployment template to create a cron job that runs daily at 12:05AM, prunes files in MEDIA_ROOT that are at least 1 day old, and logs the results to a file.
Also includes an update to the uwsgi.ini template to increase harakiri duration for the worker processes (this change was already rolled out and made in another template location; keeping things consistent).
Anytime
Very low; Ansible deployment code changes only 
None

Enhancement/#354 Cron task to prune MEDIA_ROOT files

---

cadasta/party/tests/test_views_default.py
cadasta/questionnaires/managers.py
cadasta/questionnaires/tests/attr_schemas.py
cadasta/questionnaires/tests/test_attr_schemas.py
cadasta/spatial/tests/test_views_default.py
cadasta/xforms/mixins/model_helper.py
cadasta/xforms/tests/attr_schemas.py
cadasta/xforms/tests/files/test_resources.py
cadasta/xforms/tests/test_views_api.py
requirements/common.txt

- Adds support for `select_multiple` in xls form uploads (#586)
- Adds support for `select_multiple` digestion through ODK
- Adds support for `select_multiple` in the platform UI
- Updated version of jsonattrs (1.1.15)
- Added tests for JsonAttrsMixin render
- So this is going to conflict with my other PR #738 , so once either this one or the other is pulled in, I'll need to rebase and clean some stuff up.
- None
- Update documentation to indicate that select_multiple is now available.

#586: Added support for select_multiple in xls forms

---

cadasta/organization/forms.py
functional_tests/organizations/test_organization_member.py
functional_tests/pages/OrganizationMember.py

- Add filter for archived projects in org member edit form
- Doesn't cause conflicts because default permissions are added to all projects, and then changed by the user
- Fixes #763 and #779 
Whenever, I think it's minor enough that this week would be nice.
None
None

Only active projects appear on member permissions page

---

cadasta/core/static/js/dataTables.forms.js
cadasta/templates/organization/organization_members_edit.html
cadasta/templates/organization/project_add_permissions.html
cadasta/templates/organization/project_edit_permissions.html
cadasta/templates/party/relationship_resources_add.html
cadasta/templates/party/resources_add.html
cadasta/templates/resources/project_add_existing.html
cadasta/templates/resources/script_add_lib.html
cadasta/templates/spatial/resources_add.html

- Fix #782 and #796 and improve fix for #507:
- **Overview:** When a form has fields inside DataTables, these fields may become detached from the form and not submitted with the form because DataTables hides rows due to its search/filter/paging functionality. This may result in errors because the server expects complete fields to be submitted with the form.
- Create `activateFormFieldsInDataTable()` JS function inside a new static JS file **dataTables.forms.js**. This function activates the selected form DataTable form fields such that hidden form fields are submitted with the form.
- Call `activateFormFieldsInDataTable()` from the following templates:
- organization/organization_members_edit.html
- organization/project_add_permissions.html
- organization/project_edit_permissions.html
- …

Ensure form submission is complete with fields in DataTables

---

README.rst

Just a change to the README, to move AWS deployment instructions to the bottom.  No idea why they were there at the top.

Move AWS deployment instructions

---

cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/views/default.py
cadasta/templates/organization/organization_members_edit.html
functional_tests/organizations/test_organization_member.py

- Fix #794:
- Add exception handling to `OrganizationMembersEdit.get_context_data()` to avoid the error when the user is a superuser.
- Add a unit test to catch this bug and to verify that it is fixed.
- Disable the org role select form field when the viewing user is an org admin viewing his/her own member page.
- (Context: https://github.com/Cadasta/cadasta-platform/commit/1aac076acae061fa2c6e6ead305d4a68fef17e0c#commitcomment-19327831)
- Update a functional test to reflect the disabled select state. 
Anytime.
None foreseen.
None.

Fix #794: Avoid error when superuser views org member edit page

---

cadasta/party/models.py
cadasta/party/tests/test_models.py
cadasta/resources/mixins.py
cadasta/spatial/models.py
cadasta/spatial/tests/test_models.py
functional_tests/pages/Project.py
functional_tests/projects/test_project.py

- added detach resource methods to models with `ResourceObjectMixin`
- fixes issue #803 
Whenever
None
There is commented out code for whenever we implement resources for `PartyRelationship` and `SpatialUnitRelationship`

added pre_delete to detach resources from records

---

cadasta/spatial/tests/test_views_default.py
cadasta/spatial/views/default.py
cadasta/templates/spatial/location_add.html
requirements/dev.txt

- Fully fix #719:
- **Overall bugfix idea:** When the user first loads the add location page (via HTTP GET), the platform checks the HTTP referrer URL and if it exists and it is not the same add location page (the user could click the "Add location" button while on the add location page), then it stores this URL as the `cancel_add_location_url` session variable. Otherwise, the project dashboard URL is stored in that session variable. Later, when the view is rendered, the `cancel_url` context variable is copied from the `cancel_add_location_url` session variable if it exists, otherwise the project dashboard URL is used. This `cancel_url` context variable is used as the URL of the cancel button in the template.
- Update the `LocationsAdd` view to perform the behavior described above.
- …

Fix #719: Fix URL for canceling adding locations

---

cadasta/config/settings/production.py
provision/roles/cadasta/application/tasks/main.yml
provision/roles/cadasta/install/tasks/main.yml
requirements/common.txt

Adds configuration for memcached support to provisioning files. Included changes:
- Installing libmemcached-dev and pylibcmc packages
- Adding env vars for memcached host
- Updated Django production settings file with cache configuation
- Consistent hashing option enabled for multi-node capability
Anytime. Provisioning only; no platform changes.
None
None; changes are already in place on staging.

Provisioning for memcached support

---

cadasta/config/settings/dev.py
cadasta/config/settings/production.py
requirements/common.txt

- Bump django-tutelary version.
- Add cache configuration to development and production settings.
*The cache configuration in this PR at the moment is set up the same for development and production.  For development, this is the correct `DummyCache` backend.  For production, this needs to be updated to use `memcached` once `memcached` is included in the provisioning setup.*
**This PR should not be merged until @amplifi has modified it to include `memcached` setup in the production provisioning scripts.**
There shouldn't be any risk to this.  It's just caching, and before these changes, django-tutelary wasn't doing any across-process cache invalidation of its internal caches, so this can only make things better!
I don't know how to do this, but it would be good to have some diagnostics to …

Caching for tutelary

---

cadasta/resources/views/default.py

Fix the HTTP 502 errors that are encountered on the resources list page by adding the `success_url` = `None` context variable to views that include the `modal_archive` or `modal_unarchive` modals.
As soon as possible would be good.
Check that no 502 errors are encountered on staging (because this error doesn't seem to happen on the dev VM or Travis).

Fix 502 errors on resources list page

---

cadasta/templates/organization/user_list.html
functional_tests/fixtures/__init__.py
functional_tests/pages/Users.py
functional_tests/users/test_page_list.py

- Refactor functional tests user creation code
Reuse user creation code whether user is a superuser or not.  Apply the
superuser role if user is indeed supposed to be a superuser.
- Display user's full name on user list page
Under the "member" column, it used to show only the user's username, now
it's showing "username (full name)".
Close #316
Screenshot from original user list page:
Screenshot after proposed changes:
No preconditions
There shouldn't be any.
None

Display user's full name on user list page

---

cadasta/organization/tests/test_widgets.py
cadasta/organization/widgets.py

- Display username first then full name on projects permissions page
It was displaying full name first then username, reverse them to be
consistent with the new pattern.
Close #818
No preconditions.
None.
None.

Display username first then full name on projects permissions page

---

cadasta/templates/resources/project_list.html
functional_tests/projects/test_project_resources.py

In the project resources view, hide the 'Attach' button if the user doesn't have the permission to add resource
Fix for https://github.com/Cadasta/cadasta-platform/issues/835
Whenever possible

Project resource view 'Attach' button hiding from users who doesn't have permission

---

cadasta/accounts/management/commands/loadpolicies.py
cadasta/accounts/tests/test_management_commands_loadpolicies.py

- Add arguments for accounts loadpolicies command
Without the arguments, when running `python manage.py loadpolicies`, you
get a `KeyError`:
```
Traceback (most recent call last):
File "manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File "/home/karen/cadasta/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
utility.execute()
File "/home/karen/cadasta/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/home/karen/cadasta/env/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
self.execute(*args, **cmd_options)
File "/home/karen/cadasta/env/lib/python3.5/site-packages/django/cor …
```

Allow accounts loadpolicies command to be run on its own

---

cadasta/questionnaires/managers.py

- Fix #869 
- One line: default for a `get` should be `{}` instead of `None`.
Any time.
None.
None.

Fix None for translated labels

---

cadasta/config/settings/production.py

Adds a separate cache for jsonattrs, as distinct from the 'default' cache used by tutelary. This facilitates flushing of the jsonattrs cache without disturbing the tutelary cache.
Anytime; changes are already in place on staging.
None; provisioning-only change.
None

Add separate cache settings for jsonattrs

---

cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py
cadasta/resources/migrations/0005_fix_import_resource_urls.py
cadasta/resources/tests/test_migrations.py

Low risk. The PR introduces a data migration to update url values for imported CSV resources. The migration has been unit tested but should be tested on staging before deployment to production.
Existing Imported CSV resources on staging, demo and production should be moved from the root of the relevant S3 bucket into the **resources** directory.

Fix #857: Imported resources saved to wrong location

---

requirements/common.txt

Updates requirements to django 1.9.10
Very soon
Low
Support for Django 1.9 will stop when Django 1.11 will be released, which is currently scheduled for April 2017. We should upgrade to 1.10.x before.

Upgrade to Django 1.9.10

---

cadasta/templates/organization/project_add_extents.html
cadasta/templates/organization/project_edit_geometry.html
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_edit.html

- Fixes #858 In Safari >10.x the `map:init` event object is structured differently. This PR adds the necessary checks when parsing the object before adding controls to the map. 
Anytime.
None.
None.

Fix #858 -- Read map:init event details correctly

---

.travis.yml
provision/roles/cadasta/application/tasks/main.yml
requirements/common.txt

Downgrades GDAL to 1.10.0 because builds and provisioning broke with GDAL provided by ubuntu-gis PPA.
ASAP. 
We need to test how the downgrade affects existing installations on staging. 
After merging, everyone should rebase their branches to make the build work again

Fix GDAL install

---

cadasta/organization/forms.py
cadasta/organization/importers/csv.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py
cadasta/resources/migrations/0006_randomize_imported_filenames.py
cadasta/resources/tests/test_migrations.py
cadasta/templates/organization/project_select_import.html

- Adds a migration to update the `original_file` field on the `Resources` table for files with mime type `text/csv`
- Adds randomization to file names for imported `CSV` files
- The migration also rewrites the `file` field on the `Resource` table to reflect the randomized filename
Can be merged immediately. Should be included in the release for Sprint 10
Relatively low risk. It includes a migration that has been unit tested but will need testing on staging before release.
14 CSV files in Staging, and 7 files in Demo S3 buckets will need to be renamed to reflect the randomized filenames in the `Resource` table. This can be done manually post-release.

Fix: #884 and #911 update original_file field and randomize filenames for imported resources

---

cadasta/organization/serializers.py
cadasta/organization/tests/test_serializers.py

- Fix #881: When updating the user roles, assign the user object to `self.user`
Anytime
Low
None

Fix #881 -- Assign user instance when updating role via API

---

cadasta/accounts/urls/default.py
cadasta/accounts/views/default.py

- Fix #732
- Override `allauth` views used for password change and password reset to include `SuperUserCheckMixin` to ensure that "Users" menu appears where required.
Any time.
None.
None.

Fix #732: "Users" menu on password views

---

.travis.yml
tox.ini

Disable functional tests for now, since they're completely broken.

Disable functional tests for now

---

cadasta/core/static/js/L.Map.Deflate.js
cadasta/core/static/js/map_utils.js
cadasta/templates/core/dashboard.html
cadasta/templates/organization/project_dashboard.html
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_edit.html
cadasta/templates/spatial/location_map.html
cadasta/templates/spatial/location_wrapper.html

- Resolves #932
- Switch to a customized version of Leaflet.Deflate to improve the performance of map interactions. (These changes will be added upstream to Leaflet.Deflate at some point). The customized approach includes the following changes:
- Ignore point features when evaluation whether to show the original feature or the marker.
- Group features into bins according to the zoom threshold and evaluate only features that were affected by the last zoom action.
- When evaluating, features ignore everything that is outside the current map view. When the map is panned, the current map view is re-evaluated and updated accordingly. The reevaluation only includes features that have not be evaluated before.
- Removes Leaflet.MarkerCluster.LayerSupport as it is not needed any longer
I have …

Map interaction performance improvements

---

cadasta/core/static/js/L.Map.Deflate.js
cadasta/templates/spatial/location_edit.html

- Fixes an issue that prevented the location-edit map from loading after the changes introduced in #944 
- Fixes another problem related to binning features according to their zoom thresholds: Say, a feature's zoom threshold is 10. When the map zooms from zoom level 5 to zoom level 12 and the feature is not inside the resulting map view, the feature's display is not updated. When the map then zooms from zoom level 12 to 11, the feature is not evaluated because only zoom thresholds 11 and 12 get evaluated; even if that feature is now visible in the map view. In this case, the marker is displayed incorrectly instead of the actual feature geometry. The problem is fixed by removing the zoom-level bins and always checking all features inside the resulting map view. 
ASAP, before the next …

Fix handling of L.Deflate for location edit page

---

cadasta/templates/core/dashboard.html

- Fixes #949: Projects are showing up on platform dashboard again
- Small changes to `cadasta/templates/core/dashboard.html`:
- Remove markerClusterGroup
- Initialize L.Deflate correctly
ASAP
Very low
N/A

Fix #949 -- Remove markerClusterGroup and initialize L.Deflate correctly

---

cadasta/accounts/views/default.py

- Fixes #950: `PasswordResetView` requires users log in before the page can be accessed. I removed `LoginRequiredMixin`; the page is now also accessible to unauthenticated users. 
Anytime.
Low.
N/A

Fix #950 -- Remove LoginRequiredMixin from PasswordResetView

---

requirements/common.txt

Adds the AWS CLI pip package to requirements for all envs. Required for testing (in dev) and utilizing (in staging/demo/production) SQS for the ElasticSearch implementation.
Anytime
None
Anyone who needs to interact with the SQS staging queue or other AWS components via the CLI should contact me for API access keys and account permissions configuration.

Include AWS CLI for all envs

---

cadasta/accounts/forms.py
cadasta/accounts/serializers.py
cadasta/accounts/tests/test_forms.py
cadasta/accounts/tests/test_serializers.py
cadasta/accounts/tests/test_views_api.py
cadasta/accounts/urls/default.py
cadasta/accounts/validators.py
cadasta/accounts/views/default.py
cadasta/config/settings/default.py

- Added password strength requirements to registration, update password, and reset password
Depends on whether or not we want to combine this PR with Chandra's which includes the parsley integration and updated copy. I just made up error messages, but wanted to create the PR to see if there were other things that need to fixed.
- Currently doesn't include a way to trigger an already existing user if their password isn't up to snuff.
- Update copy to be consistent.
- Add trigger for existing users with weak passwords.

Password strength requirements implemented for server-side

---

cadasta/config/urls/default.py
cadasta/core/static/js/L.Map.Deflate.js
cadasta/core/static/js/map_utils.js
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py
cadasta/party/tests/test_views_default.py
cadasta/party/views/mixins.py
cadasta/spatial/tests/test_urls_async.py
cadasta/spatial/tests/test_views_async.py
cadasta/spatial/tests/test_views_default.py
cadasta/spatial/urls/async.py
cadasta/spatial/views/async.py
cadasta/spatial/views/default.py
cadasta/spatial/views/mixins.py
cadasta/templates/core/base.html
cadasta/templates/organization/project_dashboard.html
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_edit.html
cadasta/templates/spatial/location_map.html
cadasta/templates/spatial/location_wrapper.html

- Resolves #931: Improves responsiveness of map views by asynchronoulsy loading geographic features. 
- Introduces `spatial.views.asyc.SpatialUnitList`, which provides paginated access to spatial units on a project. The page size is set to 1000. The view uses a custom `Paginator` based on [`GeoJsonPagination`](https://github.com/djangonauts/django-rest-framework-gis#geojsonpagination)
- Removes synchronous loading of project locations from all map views. Views affected include:
- `organization.views.default.ProjectDashboard`
- `spatial.views.default.LocationList`
- `spatial.views.default.LocationAdd`
- `spatial.views.default.LocationDetail`
- `spatial.views.default.LocationEdit`
- `party.views.default.PartyRelationshipDetail`
- `party.views.default.PartyRelationshipEdit`
- …

Add asychronous loading to map views

---

.travis.yml

- Upgrade `.travis.yml` to use PostGIS 2.3
ASAP
None
Revisit whether we use PostGIS 2.3 on our production systems or make builds pass with PostGIS 2.1.

PostGIS 2.3 for Travis builds

---

cadasta/party/models.py
cadasta/party/tests/test_models.py
cadasta/resources/mixins.py
cadasta/spatial/models.py
cadasta/spatial/tests/test_models.py

- deferring attributes in record views caused a regression (#803)
- `detach_object_resources` now works for deferred objects
- added tests for deleting deferred objects
Whenever, unless this is a big enough bug that it needs to be added before releasing to platform.
None
None

detach_object_resources now works for deferred objects

---

cadasta/accounts/load.py
cadasta/accounts/management/commands/loadpolicies.py
cadasta/accounts/tests/test_load.py
cadasta/accounts/tests/test_management_commands_loadpolicies.py
cadasta/core/management/commands/loadstatic.py
cadasta/core/tests/factories.py
cadasta/core/tests/test_management_commands.py
provision/roles/webserver/production/tasks/main.yml

Fix to ensure policies are updated during provisioning -- see #978 
This PR:
1. Removes update flag from loadpolicies and cleans up tests
2. Restores provisioning step
3. Cleans up tests to prevent cruft
For Sprint 11 Release
Low
As long as we're happy with this process, I'll update in Sprint 12 to move the provisioning command into a single task file for both dev and prod to eliminate duplication.

Loadpolicies bugfix & provisioning

---

cadasta/accounts/tests/test_views_default.py
cadasta/core/static/css/main.css
cadasta/templates/allauth/account/password_reset_from_key.html

- Fix #984 
- Removes all client-side validation from the view. Let me explain: I had a PR ready that adds the user's username and email to the template and enables client-side validation. In this particular case, however, we might open a security hole, when we make the user's credentials public. If someone gets hold of the password reset link, they will get the username associated with the account and the new password, i.e. all information necessary to hijack the account. I checked back with Adrienne, and we decided to move validation entirely to the back-end for this view because it's too risky. 
Soon.
None.
None.

Fix #984 -- Remove client-side validation

---

CHANGELOG.md

Updates changelog for latest staging release
Anytime
None
None

Update changelog for v1.3.0-alpha.3

---

cadasta/templates/party/party_detail.html

- Completes #993
- When viewing party detail page (from party index or location relationship), parties tab is highlighted in left subnav
- None

Parties detail page - updated left nav tab on

---

.github/PULL_REQUEST_TEMPLATE

This PR adds a review checklist to the pull request template. The checklist lists things to look out for. It might not be exhaustive, feel free to add anything that is missing. 
Anytime
None
None

Adds PR review checklist

---

cadasta/core/static/js/map_utils.js
cadasta/templates/organization/project_edit_geometry.html

Fixes a bug that breaks the map when there are no project geometry or spatial units in a project. Currently, the the map extend is either based on the project extent or the extent of all spatial units in a project. If neither a present, an error is thrown. 
Soon
None
None

Fix map bounding box when there are no geometries

---

cadasta/questionnaires/serializers.py
cadasta/questionnaires/tests/test_serializers.py
cadasta/xforms/renderers.py
cadasta/xforms/tests/test_renderer.py

This PR fixes three issues regarding the rendering of XForms:
- Repeat groups were not rendered as such in XForm, but as standard groups instead. This issue is fixed by reading the correct type from the serialized object in the renderer. 
- Groups were not serialized with the right nesting; i.e. groups that are children of other groups were placed into the top level. This is fixed reading only groups without parent groups in the questionnaire serializer and traversing the hierarchy from there. 
- Groups did not render child groups; a group in a repeat group will not be rendered in the form. This is fixed by reading both child questions and groups when rendering a question group. 
It fixes some critical bugs, so the sooner the better
Low
None.

Fix repeat groups and question order in XForms

---

cadasta/config/settings/default.py
cadasta/core/static/js/file-upload.js
cadasta/resources/models.py
cadasta/resources/validators.py
cadasta/templates/resources/form.html
requirements/common.txt

- Fixes #662
- Fixes #972 (The fix comes with the new django-buckets version, I did not chnage any code in the platform. When reviewing, it should be tested if uploading and deleting files work as expected)
- Bump django-buckets to 0.1.19a5, which is a pre-release version. I suggest to check this PR, and when it's accepted, I will make a full release and update the requirements before merging. 
- Rename `MIME_LOOKUPS` to `ICON_LOOKUPS` to make it more obvious what the `dict` is for (looking up icons for mime types).
- Introduces a new `MIME_LOOKUPS` `dict` to lookup mime types for file extensions that are otherwise not detected in the browser.
- Change `file-upload.js` to use either the mime type detected by the browser or the one defined in `MIME_LOOKUPS`.
Soon, as #972 is a high …

Fix #662 -- Define MIMETYPE_LOOKUP to detect type from file extension

---

cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py

- Fix #1018:
- Corrected call to `super().post()`.
- Update unit tests. In particular, _test_post_with_blocked_questionnaire_upload_ should have resulted in a successful form submission. Also, `questionnaire` is removed from the default `post_data` in order to simulate the missing questionnaire fields in the template if the project has records.
Soon.
None foreseen.
None.

Fix #1018: Make project details editing work again

---

cadasta/accounts/tests/test_views_default.py
cadasta/accounts/views/default.py

- Fixes #904 
- Users are now redirected to profile page after changing their password
- Whenever
- None
- None
---

User is redirected to profile after changing password

---

cadasta/accounts/adapter.py
cadasta/accounts/tests/test_adapter.py
cadasta/config/settings/default.py
cadasta/config/settings/dev.py

[List all changes you want to add here. If you fixed an issue, please
add a reference to that issue as well.]
- Reconfigured allauth pre_authentication to use an exponential back-off method instead of a static time and attempt count.
- Changed default cache in the dev environment to LocMemCache
- Fixes #945
- Whenever
- This might confuse some users. It might be useful to add some addition information to the `Too many failed login attempts. Try again later.` message indicating the amount of time they should wait.
- Update messaging?
---
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be …

Reconfigured allauth pre_authentication to use an exponential back-off

---

cadasta/templates/organization/organization_dashboard.html
cadasta/templates/organization/project_list.html
cadasta/templates/resources/table.html

Resolve #1041 by adding a numeric date (seconds since the Unix Epoch) to the date column using DataTables' [data-sort HTML attribute](https://datatables.net/examples/advanced_init/html5-data-attributes.html). Affected tables are the main project list, organization dashboard project list, and the project resources list.
Note: An existing `default_if_none` filter is removed because the project/resource `last_updated` field is `auto_now=True` which makes the filter useless. 
It would be nice if this was merged by the end of the week.
None.
None.

Fix #1041: Fix date sorting

---

cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/views/api.py

- change ProjectDetail view from `RetrieveUpdateDestroy` to `RetrieveUpdate`
- Fixes #1048 
Probably sooner rather than later?
None
None
---

removed `destroy` option from ProjectDetail api view

---

cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/widgets.py

- Disabled `value_omitted_from_data` (newly added in django 1.10) for `PublicPrivateToggle` so that projects can be set to public and private again.
- Removed `access` from `ProjectEditDetailsTest`'s post_data since it is not present in post data if the project is public.
- Added a test for toggling a project's access from public to private and back.
- Fixes #1038 
Whenever
Low
None

Adjusted PublicPrivateToggle to work with django 1.10

---

cadasta/xforms/mixins/model_helper.py
cadasta/xforms/tests/test_model_helper.py
cadasta/xforms/tests/test_views_api.py
cadasta/xforms/views/api.py

- Adds a check whether the contributing user has permissions to add data to the project. The check is against user roles instead of permissions because we need to check against four different permissions here (`spatial.add`, `tenure_rel.add`, `party.add`, `resource.add`) as users upload everything at once. For our current setup, the proposed solution is sufficient; we need to revisit when we implement fine-grained permission settings. We could then either check if the user has all permissions, which means if one permission is missing they would not be able to add anything. Or we check if one permission is present, which means users could add information they are not supposed to. Both solutions obviously have flaws, and I have no idea how to solve this at this point. 
- Adds a test whether …

Fix #1036 -- Add permission check to GeoODK submissions

---

cadasta/core/static/css/main.css
cadasta/core/static/css/main.scss
cadasta/core/static/js/dataTables.selectFiltering.js
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/default.py
cadasta/templates/core/base.html
cadasta/templates/organization/organization_dashboard.html
cadasta/templates/organization/organization_list.html
cadasta/templates/organization/project_list.html

- Fix #1035:
- Note: See the bug report for the root cause.
- Move the first archived status column as the last column and use DataTables' `data-filter` HTML attribute with "archived-True" and "archived-False" values instead of cell contents "True" and "False" that get translated with "archived" and "unarchived" HTML classes. Using data attributes should avoid things getting unnecessarily translated, which led to the bug. Also, delete the explicit CSS to hide this column in favor of using the usual Bootstrap "hidden" class.
- Update static/js/dataTables.selectFiltering.js:
- Make the "Active", "Archived", and "All" labels translatable.
- Use a [custom DataTables search function](https://datatables.net/examples/plug-ins/range_filtering.html) to make the filtering code simpler.
- Since …

Fix #1035: Make archived filtering work when not using English

---

cadasta/organization/models.py
cadasta/organization/tests/test_models.py

- Fixes #1008: As @seav stated in the original bug report, permission policies were not removed from the user's assign policies when a project role is deleted. Policies were also not removed correctly when an organization admin role was deleted (as reported by @linzjax in the comments).
- Introduces a `post_delete` hook for `ProjectRole` instances that makes sure policies are unassigned correctly. The functionality to reassign project roles now lives in `assign_prj_policies`, which is used for both updating and removing project roles. 
- Adds changes to `assign_org_policies` (formerly `reassign_user_policies` to make sure policies are removed when an organization admin role instance is deleted.
- I also refactored functions related to permission assignment for both organisations and …

Fix #1008 -- Unassign policies when roles are deleted

---

cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/mixins.py
cadasta/templates/organization/project_wrapper.html

- Fixes #960: Hides the import button from the dropdown menu for users who do not have permission to import data
Anytime
None
None

Fix #960 -- Hide Import button from UI

---

cadasta/config/settings/production.py
provision/roles/cadasta/install/tasks/main.yml

Provisioning only changes; adds Ansible support for ElasticSearch host production environment variable to override defaults.
Anytime
None
None

Add ElasticSearch host to production override of defaults

---

cadasta/config/settings/default.py
cadasta/core/static/css/main.css
cadasta/core/static/css/maps.scss
cadasta/core/static/css/single.scss
cadasta/core/static/js/map_utils.js
cadasta/core/static/js/smap/index.js
cadasta/core/static/js/smap/map.js
cadasta/core/views/default.py
cadasta/organization/forms.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/urls/default/organizations.py
cadasta/organization/views/default.py
cadasta/spatial/forms.py
cadasta/templates/core/dashboard.html
cadasta/templates/organization/project_add_extents.html
cadasta/templates/organization/project_dashboard.html
cadasta/templates/organization/project_edit_geometry.html
cadasta/templates/organization/project_map.html
cadasta/templates/organization/project_wrapper.html
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_edit.html
cadasta/templates/spatial/location_form.html
cadasta/templates/spatial/location_map.html
cadasta/templates/spatial/location_wrapper.html
requirements/common.txt

__NOTE__: This is not being merged into master. Opening this PR as the first step towards SMAP. It's caused some oddities across the platform because of Leaflet 1.0, but those will be dealt with, so pardon the mess.
- Addresses #1057 
- ProjectMap will serve as the main view for all project pages (found at `/organization/{org-slug}/projects/{project-slug}/map/` for now)
- Side panel can be displayed or hidden by switching between `detail-hidden` and `detail-display`. Currently doesn't display anything.
- Upgraded _just_ project_map.html to Leaflet 1.0. Since other pages will be absorbed by this one, I am putting off the full upgrade until the other views have been reworked.
- Note: the other maps will have some odd ticks until then.
- Currently only standard tests for ProjectMapView. Will …

Single page map scaffolding view and html. Upgrade (kinda) to Leaflet1.0

---

cadasta/party/forms.py
cadasta/party/models.py
cadasta/party/tests/test_models.py
cadasta/spatial/forms.py
cadasta/templates/party/relationship_detail.html
cadasta/templates/spatial/location_detail.html

- Several strings are marked for translation in the platform but aren't actually showing up as translated in the UI despite having translations. It turns out that some instances of `ugettext` should have been `ugettext_lazy` instead. This PR fixes this problem and introduces a double underscore as an alias for `ugettext_lazy`.
- `ChoiceField` labels for the types of parties, locations, and tenure relationships are marked for translation. However the labels for the default tenure relationship types are not showing up as translated in the UI despite the use of `ugettext_lazy`. This is because the translation happens when the platform is initialized and only English labels are stored in the database. The PR fixes this problem by ensuring that these labels pass through `ugettext` whenever …

Ensure translations are applied

---

cadasta/core/mixins.py
cadasta/organization/download/base.py
cadasta/organization/download/shape.py
cadasta/organization/download/xls.py
cadasta/organization/tests/test_downloads.py
cadasta/organization/tests/test_forms.py
requirements/common.txt

This PR adds support for the export of conditional attributes. It makes use of the `SchemaSelectorMixin` added in PR #1076. 
- Upgraded `openpyxl` to version `2.4.1`
- Refactored the `write_items` methods of `ShapeExporter` and `XLSExporter` to export all attributes
- Refactored the `make_download` method of `XLSExporter` to use a streaming `WriteOnlyWorksheet` which streams rows to the spreadsheet rather than holding all data in memory before writing. This should help with improvements proposed in the [Asynchronous Import/Export DR](https://github.com/Cadasta/decision-records/pull/7)
- Refactored the `get_values` method of the base `Exporter` to return a dict of values instead of a list
- Added a method `get_conditional_selector` to the `SchemaSelectorMixin` to return the conditional …

Fix #935: Conditional attributes not exported during download process

---

cadasta/organization/tests/test_views_api_organizations.py
cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/views/api.py
cadasta/party/tests/test_views_api_parties.py
cadasta/party/tests/test_views_api_party_relationships.py
cadasta/party/tests/test_views_api_tenure_relationships.py
cadasta/party/views/api.py
cadasta/resources/tests/test_views_api.py
cadasta/resources/views/api.py
cadasta/spatial/tests/test_views_api_spatial_relationships.py
cadasta/spatial/tests/test_views_api_spatial_units.py
cadasta/spatial/views/api.py

Fixes #1104. @linzjax used `HTTP PUT` to update the project and organization, permissions were not checked for `PUT` requests on any of the API view. This PR adds `PUT` actions to all API views I could think of along with tests for unauthorised and unauthenticated users for both `PATCH` and `PUT` updates. 
Soon
No
None

Fix #1104 -- Add PUT actions to API views

---

cadasta/templates/xforms/submission_response.xml
cadasta/xforms/mixins/openrosa_headers_mixin.py
cadasta/xforms/views/api.py

When a form is sent to the Cadasta platform from GeoODK the server is sending an OpenRosa formatted XML response. If there is an error or success a custom message can be sent. The javaXMLParser lib does not understand python  string = """ textexttext """.  So changed it to regular format.
I have also added a success message that is has been received. 
Small fixes but necessary to get custom responses displayed.

Error response on mobile response string fix.

---

cadasta/search/tests/test_views_default.py
cadasta/search/views/default.py

- Fix #1115:
- Add the missing `ProjectAdminCheckMixin` to the search default view.
- Add a unit test to catch this bug.
Before Sprint 13 release.
None foreseen.
None.

Fix #1115: Add missing mixin to search default view

---

cadasta/templates/allauth/account/signup.html

1.As mentioned in issue-1087-we should implement an option to toggle the view of the password input when registering.I entered a checkbox to toggle the view of the password.
2.File that is changed here is -cadasta/templates/allauth/account/signup.html
-
-

Show password option-issue-1087

---

cadasta/party/tests/test_views_default.py
cadasta/party/views/default.py
cadasta/party/views/mixins.py
cadasta/templates/party/party_detail.html

- Implements #1001: Adds relationships to party detail page. Functionality and layout are similar to the location detail pages. There are three tabs, one for party details, one for relationships and one for resources. 
- The changes _do not_ include a workflow to add relationships to a party as this requires designing an appropriate workflow beforehand. 
- Translations for language dropdown are included as well
@clash99 Can you please check if the layout of the page is ok?
Whenever.
None
None

Fix #1001 -- Add relationships to party detail page

---

cadasta/core/static/css/main.css
cadasta/core/static/css/single.scss
cadasta/templates/organization/organization_wrapper.html
cadasta/templates/organization/project_wrapper.html

Issue #1128 Remove "back" link on organization and project wrapper
- Remove back/return to index link on organization wrapper and project wrapper.
- Increased font size of organization link on project wrapper by 2 pixels.

issue 1128 fixed

---

README.rst
Vagrantfile

Adds proxyconf settings to Vagrantfile. Users behind proxies can install the `vagrant-proxyconf` plugin for provisioning the local dev VM. Users without proxies experience no changes.
Anytime
None; users without proxies experience no changes. Only those with the `vagrant-proxyconf` plugin will obtain the new settings.
Document plugin option in readme.

Add proxyconf settings

---

cadasta/core/static/css/main.css
cadasta/core/static/css/orgs.scss
cadasta/templates/organization/organization_dashboard.html

Changed the order of divs (contact vs projects) on org pages - fix for issue 1092.

Issue 1092 fix

---

cadasta/config/settings/default.py
cadasta/search/tests/test_views_async.py
cadasta/search/tests/test_views_default.py
cadasta/search/views/async.py
cadasta/search/views/default.py
cadasta/templates/search/search.html

- Fix #1223:
- Add a new Django setting to match the maximum number of results ES will return
- Use this new setting to cap the returned number of search results hits so that DataTables will know not to go over
- Add a guideline advising the user of this limit
- Add a unit tests and update other affected unit tests
For Sprint 14 release.
None foreseen.
None.

Fix #1223: Cap search results to 10000

---

cadasta/core/static/css/forms.scss
cadasta/core/static/js/password_widget.js
cadasta/templates/allauth/account/login.html
cadasta/templates/allauth/account/password_change.html
cadasta/templates/allauth/account/password_reset_from_key.html
cadasta/templates/allauth/account/signup.html

Changes proposed:
- Fixes #1216 
- Fixes #1217
- Fixes #1236  
- Moves JS code to show/hide password to `password_widget.js`.
- Add a show/hide glyphicon toggle to the right of password widget.
- Add a border around the glyphicon when form submission returns errors.

Replace the `Show Password` checkbox with glyphicons.

---

cadasta/core/static/js/dataTables.conditionalPaging.js

- Hide row filter dropdown when the search is one page long
Anytime
- None
environments.]
- python manage.py collectstatic?

Fix #1221: Hide row filter dropdown when the search is one page long.

---

cadasta/templates/organization/project_dashboard.html
cadasta/templates/spatial/location_map.html

Included the Search and Go-To-My-Location map controls in Project Overview and Map pages.

issue-1002-fixed

---

cadasta/templates/organization/project_defaults_import.html

This change matches Location_type field to 'location_type' and Party_type field to 'party_type', while importing project data
See issue : https://github.com/Cadasta/cadasta-platform/issues/1090
- From issue discussion, export data maps/names location_type and party_type to both type. So when a file is being imported with type as one of its fields, it will not be displayed as default option.
- Probably, fix the export feature naming convention to  location_type and part_type

Fix issue #1090

---

cadasta/accounts/forms.py
cadasta/accounts/tests/test_forms.py

Bug Description: Registering with an email that is no longer associated with an account throws an error.
Cause: When a new user registers, an EmailAddress (Model class in allauth.account.models) object is created and an email confirmation mail is sent.  When the same user updates his/her email in the profile, the EmailAddress object associated with his User model was not being deleted which caused IntegrityError.
Solution: In clean_email method of ProfileForm class, delete any old instances of EmailAddress model for the current user if email is being updated.
PR can be merged without any preconditions.
There are no risks from merging this pull request.
No extra actions required.

Fix: #1102 Remove IntegrityError when using a released email to register

---

cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/views/default.py

This change leaves the user at a individual member's page after role has been changed from 'Administrator' to 'Member'
See issue : https://github.com/Cadasta/cadasta-platform/issues/1106
-
-
-
- [y ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ Y] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ Y] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled.

Fix bug #1106

---

cadasta/core/static/css/main.scss
cadasta/templates/organization/organization_dashboard.html

- Adds a CSS rule that shows each `li` element with a cursor pointer.
- Add links to member page on the username.
Anytime.
- None
environments.]
- None

Fix #1262: Add links to member profiles from OrganizationDashboard page

---

cadasta/core/static/js/form_submit_once.js
cadasta/templates/core/base.html
cadasta/templates/party/party_add.html
cadasta/templates/party/party_edit.html
cadasta/templates/party/relationship_resources_add.html
cadasta/templates/party/relationship_resources_new.html
cadasta/templates/party/resources_add.html
cadasta/templates/party/resources_new.html
cadasta/templates/resources/modal_add_lib.html
cadasta/templates/resources/modal_upload.html
cadasta/templates/resources/project_add_existing.html
cadasta/templates/resources/project_add_new.html
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_edit.html
cadasta/templates/spatial/relationship_add.html
cadasta/templates/spatial/resources_add.html
cadasta/templates/spatial/resources_new.html

This pull request fixes #1107. Following later suggestions, this PR has exported the handler into a static JS file instead of using onclick. In order to fully fix the issue, this PR also manually: 
1. validate the form using Parsley;
2. submit the form once;
3. disable the button after the form has been submitted. 
No dependecies.
The submit button may stay disabled even if processing the submission in the backend failed. To fix this, we would need to change to submitting the form via ajax. A work-around is to refresh the page.
Although the Parsley validation itself works, I noticed that the first field of the form, where you upload a file as resource, does behaves as if it's always a valid field in the parsley validation test. On the contrary, the name field return false if empty. As a …

Fix of bug #1107 *Possible to Create Duplicate Resource Entries*

---

cadasta/config/permissions/org-member.json
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/views/api.py
cadasta/organization/views/default.py
cadasta/organization/views/mixins.py
cadasta/templates/organization/organization_dashboard.html
cadasta/templates/organization/organization_wrapper.html

- This is working under the assumptions that __organization members__, not just organization admins should be able to __view__ the list of organization members. They cannot edit/add/remove members if they are not an admin, they can only see the list.
- Fixes #1241 
- Added `is_member` to OrgAdminCheckMixin.
- Replaced `is_administrator` and `show_members` with `is_member` where appropriate.
- Updated `org_member` permissions to include `org.users.list`
- Whenever
- This is based on my understanding of what permissions are expected to be as stated in the issue.
- Run `loadpolicies` management command.

Added is_member to OrgAdminCheckMixin. Updated org_member permissions.

---

cadasta/accounts/forms.py
cadasta/accounts/serializers.py
cadasta/accounts/tests/test_forms.py
cadasta/accounts/tests/test_serializers.py
cadasta/accounts/validators.py

Currently, usernames are case sensitive. This PR makes username comparisons for account registration and profile updates case insensitive for both default and api views. New usernames and updates to existing usernames are checked for uniqueness against the full set of usernames using the `casefold` algorithm. Existing mixed-case usernames in the database remain untouched. 
- Add username comparisons using `casefold` to `RegisterForm` and `ProfileForm`.
- Add username comparisons using `casefold` to `RegistrationSerializer` and `UserSerializer`. 
- Added tests for the above changes.
Anytime.
Low.
None required.

Fix #946: Make usernames case insensitive

---

cadasta/config/urls/default.py

When working on #1332, I noticed that there were a number of URLs that simply raised errors (no representative template files for the different views exist).  These were all from `django.contrib.auth.urls`.  Please note that I did not check all existing URL endpoints, I simply noticed that all of these endpoints failed as I was looking for the used login and password reset endpoints.  There may be other broken endpoints from different packages.
[`/login/`](https://demo.cadasta.org/login/)
[`/logout/`](https://demo.cadasta.org/logout/)
[`/password_change/`](https://demo.cadasta.org/password_change/)
[`/password_change/done/`](https://demo.cadasta.org/password_change/done/)
[`/password_reset/`](https://demo.cadasta.org/password_reset/) …

Remove broken django.contrib.auth url endpoints

---

cadasta/organization/tests/test_urls_api.py
cadasta/organization/urls/api/users.py

- Addressed Issue #1284 in this PR.
- Renamed url keyword of `organization/urls/api/users.py` from `slug` to `username`.
After reviews and passing of tests.
- None
- None

Bugfix #1284: Assertion error at /api/v1/users/<user-name>/

---

cadasta/core/static/css/single.scss
cadasta/templates/search/search.html

Search: Clear search textbox.
By overriding bootstrap, we now leverage the clear search textbox feature offered by HTML5 to meet our requirements of having clear search textbox in all search options.
Fixes #1147

Search: Clear search textbox.

---

cadasta/accounts/forms.py
cadasta/accounts/tests/test_forms.py
cadasta/accounts/tests/test_views_default.py
cadasta/templates/allauth/account/password_change.html
cadasta/templates/allauth/account/password_reset_from_key.html
cadasta/templates/allauth/account/signup.html
functional_tests/accounts/test_registration.py
functional_tests/pages/Registration.py

This PR resolves #1242.  The logic to be enforced:
- If you're creating a password, you shouldn't be required to enter it twice. Instead, you should be able to unmask the single `password` field.
- If you're entering an existing password, you should not be able to unmask the password field.
Actions to make this so:
- Remove second password field on the following forms:
- Registration View: `/account/signup/`
- Reset Password From Key View: `/account/password/reset/key/<key>/`
- Change Password View: `/account/password/change`
Both the `allauth` [`ChangePasswordForm`](https://github.com/pennersr/django-allauth/blob/9e36f1dcf1938277334621b82052c1c505614b8f/allauth/account/forms.py#L365-L387) and the [`ResetPasswordKeyForm`](https://github.com/pennersr/django-allauth/blob/9e36f1dcf19382773346 …

Remove confirm password fields (resolves #1242)

---

cadasta/accounts/models.py
cadasta/accounts/tests/test_urls_api.py
cadasta/accounts/tests/test_views_api.py
cadasta/accounts/urls/api.py
cadasta/accounts/views/api.py
cadasta/templates/accounts/email/password_changed_notification.txt

- Fixes #724: Sends an email to the user when the password has been changed or reset
- Adds a signal reviever for `allauth`'s `password_changed` and `password_reset` emails that takes care of sending the email. 
- Adds a new API view `SetPasswordView` that overwrites `djoser`'s default behaviour when setting a new password. The custom view sends a `password_changed` signal after the password has been updated via the API. 
Anytime
None
None

Fixes #724 -- Send confirmation email after password change and reset

---

cadasta/organization/views/mixins.py
cadasta/spatial/tests/test_views_default.py
cadasta/spatial/views/default.py
cadasta/templates/spatial/location_detail.html

Fix bug #1233: only show the location action buttons to users who have permission to do the action. 
Screenshot of location view for user without edit/delete permission: 
Screenshot of location view for user with edit/delete permission: 
No dependencies.
None.
None.

Hide location action buttons unless user has permission to do the action

---

cadasta/resources/serializers.py
cadasta/resources/tests/test_models.py
cadasta/resources/tests/test_serializers.py

- This PR adds a temporary workaround to #1322 to ensure thumbnails are created for @SteadyCadence's imports. Proper handling of mime types should be implemented with #490.
Soon; this is important to move forward with data imports.
None
None

Adds mime_type field to resource serializer

---

cadasta/core/static/css/main.scss
cadasta/templates/core/base.html
cadasta/templates/search/search.html

- Fixes #1259 
-    Changed order of elements so pagination is first and floats right
-    Made length menu wrap to second line when screen becomes very narrow
-    Changed length menu to have "per page" in dropdown and removed outside labels
-    Changed css to adjust border and padding
- Low
- None

Reworked data tables footer

---

cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py

This commit removes extra duplicate files that are downloaded when 
'all data' is downloaded.
Fix bug https://github.com/Cadasta/cadasta-platform/issues/923
Anytime
None
None

'All data' export option: Remove records that occur twice.

---

cadasta/organization/download/resources.py
cadasta/organization/tests/test_downloads.py

- This commit makes changes so that duplicate resources don't get removed
when resources are downloaded.
- See issue: https://github.com/Cadasta/cadasta-platform/issues/1303 & https://github.com/Cadasta/cadasta-platform/issues/1302
Anytime
None
None

Rename resources to avoid deletion during download process

---

cadasta/xforms/views/api.py
requirements/common.txt

Fixes #592. 
GeoODK sends empty XML (`<location_problems />`) elements when no value is provided for a form field. We convert the XML into a Python dictionary using pyxform.xform2json.XFormToDict; all empty XML elements are converted to empty strings (`"location_problems": ""`) or a list with one empty string (`"location_problems": [""]`).
This is a problem for integer, decimal, select_one and select_multiple fields because an empty string is an actual value but it's not valid for fields mentioned above because it's not a number and usually not an option for select fields.
This PR only bumps django-jsonattrs to a new version. The actual bug fix is added to [django-json attrs PR #17](https://github.com/Cadasta/django-jsonattrs/pull/17). Please review the django-jsonattrs PR before …

Fixes #592 -- Bump jsonattrs; small style fixes

---

cadasta/core/static/css/main.scss
cadasta/templates/organization/project_add_details.html
cadasta/templates/organization/project_edit_details.html

- Completes #1365 
- Updates questionnaire help text when creating or editing a project
- Low
- I think we should remove outdated questionnaires on AWS since these in google docs replace them

Modified questionnaire text 

---

cadasta/questionnaires/serializers.py
cadasta/questionnaires/tests/test_serializers.py

This PR fixes a bug that was introduced in PR #1372. When creating `Attribute` instances via the questionnaires API, all `Attributes` were created with an incorrect schema selector because the project's `current_questionnaire` was set _after_ question groups were created. This meant that the `Attribute` instances were not found when creating locations, parties, and relationships leaving forms incomplete or failing validation via the API.
The PR fixes this by assigning the `current_questionnaire` before creating question groups. I also added a test to verify the behavior.
Soon. This is a critical issue, relevant for the QGIS plugin to work properly. 
Low.
None.

Create Attributes with correct schema selector

---

cadasta/core/static/js/form_submit.js
cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py
cadasta/templates/organization/organization_add.html
cadasta/templates/organization/organization_edit.html
cadasta/templates/organization/project_add_details.html
cadasta/templates/organization/project_edit_details.html
cadasta/templates/party/party_add.html
cadasta/templates/party/party_edit.html
cadasta/templates/party/relationship_resources_add.html
cadasta/templates/party/relationship_resources_new.html
cadasta/templates/party/resources_add.html
cadasta/templates/party/resources_new.html
cadasta/templates/resources/project_add_existing.html
cadasta/templates/resources/project_add_new.html
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_edit.html
cadasta/templates/spatial/relationship_add.html
cadasta/templates/spatial/resources_add.html
cadasta/templates/spatial/resources_new.html

- Completes #1220 
- Made duplicate organization validation error translatable by transifex (once transifex gets updated) 
- Renamed form_submit_once.js to form_submit.js 
- Modified script to cover both disabling button on valid form submit or clearing server-side errors on invalid submit.  Added this script to both organization add and edit and project add and edit pages.
- Low
- Transifex files need to be updated

Clearing server-side validation errors upon submit

---

cadasta/search/mock_es/tests/test_urls.py
cadasta/search/mock_es/tests/test_views.py
cadasta/search/mock_es/urls.py
cadasta/search/mock_es/views.py
cadasta/search/parser.py
cadasta/search/tests/test_parser.py
cadasta/search/tests/test_views_async.py
cadasta/search/views/async.py
cadasta/templates/search/search.html
requirements/common.txt

- Use default "or":
- Make search use "or" by default and allow users to specify that terms are required or excluded by prefixing them with `+` and `-` respectively.
- Implement this by using the pyparsing Python library. See the new **search/parser.py** source file and the `parse_query()` function for details. Before, the platform just passes the UI query string directly to ES which does the parsing. Now, we can control our search query syntax by having the platform do the parsing and then constructing the ES search DSL based on the parsed results.
- Terms without the prefixed `+` or `-` are mapped to the ES `should` boolean clause, terms with the prefixed `+` are mapped to the ES `must` boolean clause, and terms with the prefixed `-` are mapped to the ES `must_not` boolean clause. [[ES …

Fix #1118 and other issues

---

cadasta/party/tests/test_views_default.py
cadasta/party/views/default.py
cadasta/spatial/tests/test_views_default.py
cadasta/spatial/views/default.py

- Fixes #1397: When an option for one of the standard select fields (location type, party type, tenure relationship type) was missing from the questionnaire and that same option was used in an entity instance `QuestionOption.DoesNotExist' is thrown when accessing the detail page of that entity. (Other that stated in the bug report this only affects detail pages). 
- The exception is caught and ignore. The `QuestionOption` instance is queried from the database to create multi-language labels. If an option is not present, multi-language labels will not be populated, a case that is handled gracefully on the client-side. That's why it's ok to just ignore the exceptions. 
- Anytime
None
None

Fixes #1397 -- Catch and ignore QuestionOption.DoesNotExist

---

cadasta/accounts/tests/test_views_api.py
cadasta/accounts/views/api.py

- When a login fails, we currently return a `400` response. A [`401` response](https://httpstatuses.com/401) is slightly more descriptive and accurate.
Any time.
Low. Only complication I could think of would be API consumers, however a review of the QGIS plugin failed to show any issues.
None

Return 401 responses on failed login

---

cadasta/questionnaires/models.py
cadasta/questionnaires/tests/test_models.py

- Currently, if a `Question` has no associated `QuestionGroup`, `repr()` of the `Question` instance fails. This allows it to handle `Question` instances that have no `QuestionGroup`.
Anytime
None
environments.]
-

Support repr() if Question has no QuestionGroup

---

cadasta/organization/download/shape.py
cadasta/organization/tests/test_downloads.py

- Fixes #1373: Ignores empty geometries when writing spatial units to a shape file. 
- The spatial unit properties are still available throught the CSV.
Whenever.
None.
None.

Fix #1373 -- Ignore empty geometries for SHP export

---

cadasta/config/settings/default.py
cadasta/core/tests/test_pagination.py
cadasta/core/util.py
cadasta/organization/tests/test_views_api_organizations.py
cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/tests/test_views_api_users.py
cadasta/party/tests/test_views_api_parties.py
cadasta/party/tests/test_views_api_relationship_list.py
cadasta/party/tests/test_views_api_tenure_relationships.py
cadasta/party/views/api.py
cadasta/resources/tests/test_views_api.py
cadasta/spatial/tests/test_views_api_spatial_units.py

All API list views now paginate the data returned.  This is important if we are to avoid tying up web servers with large responses (and is a requirement for #1400).  The default page size is set to `100` elements, although this can be changed via the URL or per view.  To add pagination, I used the [`LimitOffsetPagination`](http://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination) class which I felt adds a bit more transparency about the request than the [`PageNumberPagination`](http://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination) used by the `/async/organizations/<organization>/projects/<project>/spatial/` view (being that it makes the `limit` value obvious) *(this will likely be the most contentious aspect of the PR)*.
Any time seems …

Add pagination to API list endpoints

---

CHANGELOG.md

Update ye olde changelog
Anytime
None
N/A

Update changelog for v1.8.2-alpha.1

---

cadasta/accounts/load.py
cadasta/core/mixins.py
cadasta/core/tests/test_mixins.py
cadasta/core/tests/utils/cases.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_importers.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/api.py
cadasta/organization/views/mixins.py
cadasta/party/tests/test_views_api_parties.py
cadasta/party/tests/test_views_api_tenure_relationships.py
cadasta/party/tests/test_views_default.py
cadasta/questionnaires/tests/test_attr_schemas.py
cadasta/questionnaires/tests/test_managers.py
cadasta/resources/tests/test_forms.py
cadasta/resources/tests/test_managers.py
cadasta/resources/tests/test_models.py
cadasta/resources/tests/test_serializers.py
cadasta/resources/tests/test_views_api.py
cadasta/resources/tests/test_views_default.py
cadasta/spatial/tests/test_views_api_spatial_units.py
cadasta/spatial/tests/test_views_default.py
cadasta/xforms/tests/test_serializers.py
cadasta/xforms/tests/test_views_api.py

A few improvements to cut down the number of warnings issued when running tests:
- Close all open files
- Replace deprecated method calls with their corresponding properties (`User.is_anonymous`, `User.is_authenticated`
ASAP
Low, it only affects tests really.
There are still loads of warnings. Some can be resolved by upgraded libraries we use (pytest, django rest framework). We also need to update our own libraries: django-tutelary for example, which causes a lot of deprecation warnings.

Reduce the number of warnings logged for tests

---

cadasta/organization/tests/test_views_api_projects.py
cadasta/organization/views/api.py

Currently, the `OrganizationProjectList` API view has no `get_perms_objects()` method. When a user loads the Project List api view: `/api/v1/organizations/{slug}/projects/`, our system will search for all projects that the user is permitted to view and return those projects.  If no projects exist, it will return a `403`.  In reality, we should return a response with the body of an empty array (`[]`) and a `200` status code.  Add `get_perms_objects()` allows the view to question if the user is permitted to view the `Organization`, and if so will return the empty array.
Anytime
Low
None

Ensure that a view can list projects in an organization even if no projects exist

---

cadasta/pytest.ini
runtests.py

The `pytest` [v3.1.0](https://docs.pytest.org/en/latest/changelog.html#id1) update on 22 May integrated `pytest-warnings` -- this is what caused our Travis builds to break, as our warnings output exceeded the 4MB max log file size set by Travis.
This PR disables warnings for the Travis env, and adds filters to ignore warnings across all envs. To view the list of warnings in dev, remove the ignore filters in pytest.ini
ASAP, to restore normalcy to the realm
No risks to platform; only affects display of test suite warnings. End of build message will still indicate the number of warnings, but won't display the warnings themselves. Example:
`================= 1873 passed, 829 warnings in 499.97 seconds ==================`
(Yeah, that's how many warnings we've got.)
Fix the …

Pytest warning filters

---

cadasta/templates/party/party_add.html
cadasta/templates/party/party_edit.html
cadasta/templates/party/relationship_edit.html
cadasta/templates/spatial/location_add.html
cadasta/templates/spatial/location_edit.html
cadasta/templates/spatial/relationship_add.html

- Completes #1539
- Customizes english to use "en-gb" since the remote files have changed their names
- Low
- We should put this in a team discussion about external file sources. The con here was that they decided to add more versions of english, which in turn broke our link because the original was renamed. There is a certain maintenance involved with both moving this locally and keeping it external. Anyway, this is fixed for now in the simplest way possible.

Adjusted date picker localization file url

---

README.rst

Adds Requires.io badge to README for package requirements status.
Anytime
None; documentation only.
None

Add Requires.io badge to README

---

cadasta/core/static/js/map_utils.js
cadasta/resources/models.py
cadasta/resources/processors/gpx.py
cadasta/resources/tests/files/invalid_xml_version.gpx
cadasta/resources/tests/files/routes_tracks.gpx
cadasta/resources/tests/files/track_seg.gpx
cadasta/resources/tests/files/tracks.gpx
cadasta/resources/tests/test_gpx_processor.py
cadasta/resources/tests/test_models.py
cadasta/resources/utils/io.py
requirements/common.txt

- Removed `GPX` parsing with `GDAL` and replaced with `gpxpy`
- Added test for parsing of multiple nested `<trkseg>` elements within a single `<trk>` element
- Added sample `GPX` file with nested `<trkseg>` elements
- Updated requirements
- Refactored some exception handling in `GPXProcessor` and `resources/models.py`
Can be merged anytime.
Only `gpx` files with xml versions `1.0` or `1.1` are supported. Some devices (incorrectly) produce xml version 2.0 which doesn't exist. Depending on the device used to produce the xml there may need to be some pre-processing of the resources to force compliance with the xml spec.
None required

Add support for GPX tracks with multiple nested track segments

---

cadasta/core/static/js/file-upload.js
cadasta/templates/resources/form.html

Anytime.
None
- Collect static.

Prefill the resource name field with the filename

---

.travis.yml

Travis has updated their Trusty env, see details: [https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch)  — this is why our builds are failing. I recommend we update our `travis.yml` to work around the change and use the previous version of the Trusty build through the end of this sprint, then add a task for next sprint to update in compatibility with the new build.
ASAP
Very low; only affects Travis env, which is currently failing without this workaround.
Add a task for Sprint 19 to update our Travis config/tests for compatibility with the new build.

Update travis.yml to work around Trusty changes

---

cadasta/core/fixtures/__init__.py

Replaces named test accounts in dev environment with generic test accounts that explicitly reflect their permission levels. The `iross` and `oroick` accounts are replaced with `superuser1` and `superuser2`.
Anytime; low priority.
None; dev environment only, no changes to functionality.
Relevant updates to internal documentation.

Depersonalize test accounts

---

cadasta/resources/tests/factories.py
cadasta/xforms/mixins/model_helper.py
cadasta/xforms/tests/files/test_resources.py
cadasta/xforms/tests/test_model_helper.py
cadasta/xforms/tests/test_views_api.py

- Fixes #1613 
- For GeoODK submissions, string sanitation is only applied to text-like fields (text and notes). For each submission, a list of text-like fields is retrieved from the database and provided to the method `sanitize_submission`. When iterating through all fields of the submission, we compare the field's key with the list of text-like fields and only sanitize when there is a match. 
ASAP; the should be scheduled for the next release. 
Low
None

Sanitise text-like fields only

---

cadasta/questionnaires/managers.py
cadasta/questionnaires/serializers.py
cadasta/questionnaires/tests/test_managers.py
cadasta/questionnaires/tests/test_serializers.py

Adds syntax checking for the xlsform `relevant` bind statement to `questionnaire.managers.py`. The syntax checking is handled by a single method which implements a regex-based syntax checker. This method is then called from the `QuestionGroupManager`, the `QuestionManager` and during attribute schema creation. The relevant tests have been added to `test_managers.py`. 
Scheduled for a patch release after the Sprint 18 release.
None forseen. 
None
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions …

Fix #1638: Check for xlsform relevant clause syntax errors

---

cadasta/config/settings/production.py
cadasta/core/backends.py
cadasta/core/tests/test_backends.py
cadasta/core/tests/test_types.py
cadasta/core/types.py
requirements/common.txt

#1579 occurs due to the abundance of `Attribute` instances being put into the cache as pickled Python objects. This PR addresses the issues around the cache throwing exceptions when a key value is greater than the cache's max-permitted size (currently set at 1MB).
This PR creates a new cache backend class. It inherits from our currently used (in production) backend, `django.core.cache.backends.memcached.PyLibMCCache`, however this backend catches any `pylibmc.TooBig` exceptions and logs them rather than raising them.
`pylibmc` needed to be bumped in patch version as the `TooBig` exception did not exist previously 
(surprising that they call that a patch version change and not a minor version change).
The issue of _why_ the key values were so large is addressed in …

Log and pass on TooBig errors from Memcached (fixes #1579)

---

cadasta/core/fixtures/__init__.py
cadasta/core/tests/test_views_default.py
cadasta/core/views/mixins.py
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/tests/test_views_default_projects.py
cadasta/organization/views/mixins.py

- Fixes #1628: Superuser permissions were not applied to superusers on production machines because tutelary's superuser policies were not applied to superusers. Superusers are only identified through the `is_superuser` field in the User table. 
- Given the precondition, that superusers can access all data and perform all actions throughout the platform, using Django's built-in `User.is_superuser` field is sufficient to identify superusers. `User.has_perm` will also work as expected because `True` will always be returned for any permissions if the user is a superuser. It's Django's default behaviour. 
- Changed the `is_superuser` property of `core.views.mixins.SuperUserCheckMixin` to return the value of `is_superuser` of the user authenticated with the request. 
- Changed `get_queryset` of …

Use user.is_superuser to identify superusers

---

cadasta/accounts/forms.py
cadasta/accounts/serializers.py
cadasta/accounts/tests/test_forms.py
cadasta/accounts/tests/test_serializers.py
cadasta/templates/allauth/account/signup.html

Address issue #1654 for applying existing feature at the registration. Part of User Dashboard #1491 epic.
- Add dropdown language menu option by adding the language field both in the `signup.html` template and in the `RegisterForm`.
- Add language item in data used in testing a valid signup
- Simplify existing `language` and `measurement` fields by deleting respective `form.fields`, custom messages and tests
- As soon as it has been reviewed
- None
- None
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and …

add language dropdown at registration

---

cadasta/config/settings/default.py
cadasta/resources/models.py
cadasta/resources/tests/test_models.py

- Fixes #1135: Adds more mime types to the list of accepted types. 
- Excludes SVG images from creating thumbnails because vector graphics are not support by Pillow. 
- New thumbnails for non-images are already on the production buckts.
When ready. 
None
None. 
- **Are all requirements met?** …

Adds more allowed mime types

---

cadasta/core/static/js/image-upload.js

- Fixes #1684: Avatar images are displayed even when the image type is not accepted. 
- Adds a check if the file type is accepted and only displays the preview in this case. 
- ASAP, this is a bugfix for the next release
None
None
- **Are all requirements met?** Compare implemented …

Fixes #1684 -- Do not display image preview when file is not accepted

---

cadasta/core/static/css/reg.scss
cadasta/templates/accounts/profile.html

- Fixes #1681: The file name wasn't displayed because PR #1655 introduces CSS that generally hides the file name on all pages accross the platform.
- I removed that CSS from `req.scss` and added it to the template `profile.html` directly because this is the only place where it should apply. 
- ASAP, this is a bugfix for the next release
None
None
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that …

Fixes #1681 -- Display file name for resources uploads

---

cadasta/templates/core/base.html
cadasta/templates/resources/project_detail.html

Fix #1690:
- Display the resource contributor's username if they don't have a full name. 
ASAP; this is a bugfix for the next release.
None.
None.
- **Does the UI work as expected?** There …

Fix #1690: Display the resource contributor's username if they don't have a full name

---

CHANGELOG.md

Updates changelog
Anytime
None; documentation update only
None
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should …

Update changelog for v1.11.0-alpha.1

---

cadasta/accounts/backends.py
cadasta/accounts/forms.py
cadasta/accounts/migrations/0008_phone_and_verification_device.py
cadasta/accounts/serializers.py
cadasta/accounts/tests/factories.py
cadasta/accounts/tests/test_forms.py
cadasta/accounts/tests/test_serializers.py
cadasta/accounts/tests/test_views_api.py
cadasta/accounts/tests/test_views_default.py
cadasta/accounts/views/api.py
cadasta/accounts/views/default.py
cadasta/core/form_mixins.py
cadasta/templates/accounts/account_verification.html
cadasta/templates/accounts/profile.html

With this PR, changes have been introduced to Edit Profile Page. Once user changes their phone number, a token will be sent to the user, and user will be redirected to Resend Token Page. Once the new phone has been verified, user account will be updated with the new phone.
1. Changes to `ProfileForm` and add tests.
2. Changes to `UserSerializer` and add tests.
3. Add language and measurement to `UserFactory`.
4. Make changes to 'accounts/views/default.py` and `accounts/views/api.py` and add tests.
5. Make changes to `templates/accounts/profile.html`.
-
- None
- None
- **Is the PR labeled …

Add phone to User Profile

---

.github/CONTRIBUTING.md

Updates contributing guidelines to direct contributors to review the decision records repo. Also includes minor formatting/spelling corrections.
Thanks to @laura-barluzzi for identifying the need for this update.
Anytime
None; doco only
None
- **Are all requirements met?** Compare implemented …

Update contributing guidelines with reference to Decision Records repo

---

cadasta/accounts/middleware.py
cadasta/accounts/tests/test_middleware.py
cadasta/accounts/views/default.py
cadasta/organization/tests/test_views_default_organizations.py

This PR fixes [#1630](https://github.com/Cadasta/cadasta-platform/issues/1630) _When changing the user-preferred language, the alert message is in the previous language_.
The fix has been done by: 
- Adding the `process_response` function in `accounts/middleware.py` -- This enables translation also when the `form_valid` function returns a response.
- Changing `ugettext` to `ugettext_lazy` -- As adviced in [here](https://stackoverflow.com/questions/4160770/when-should-i-use-ugettext-lazy/4164683#4164683), `ugettext_lazy` should be used in `froms` and `models` definitions. The `ugettext_lazy` translates strings whenever they're used, mitigating the issue of changing languages.
- as soon as it's reviewed and approved
- low
- close issue #1630 _When changing the user-preferred language, the …

Fixes #1630:: translate success form message with new selected language

---

cadasta/organization/migrations/0006_add_project_area_trigger.py
cadasta/organization/tests/test_migrations.py

Fix bug where migration fails if no spatial units are associated with project.
As mentioned in [#1716](https://github.com/Cadasta/cadasta-platform/pull/1716#issuecomment-324097777).
Use `COALESCE` to fallback to `0` if `sum(<spatial_unit_areas>) == null`, in the event that a Project has no associated SpatialUnit instances.
Before releasing #1716.
-
environments.]
-
- **Is the risk …

Fix migration failure

---

cadasta/templates/resources/edit.html
cadasta/templates/resources/project_detail.html

This is a very simple PR that adds only some HTML into an existing template. The PR applies the existing thumbnail preview to the `resources/edit.html` template as requested by the open issue #1264.
The preview is copied-and-pasted by the one applied in the `resources/project_detail.html` template, so for now it always displays the _preview of the current stored resource_.
A small video demo on the work-flow of this feature is available [here](https://drive.google.com/file/d/0BzK57GHhuoRPRzdTTUlPcXBkSE0/view).
As soon as it has been approved.
Very low.
- Close issue **Add thumbnail preview to edit resources page** #1264 .
- Investigate on how to improve UX in case the user upload a new file
- **Is this PR explained thoroughly?** All code changes must be accounted for in the PR …

Address #1264:: Add preview in resource edit page

---

cadasta/accounts/exceptions.py
cadasta/accounts/forms.py
cadasta/accounts/messages.py
cadasta/accounts/serializers.py
cadasta/accounts/tests/test_forms.py
cadasta/accounts/tests/test_serializers.py
cadasta/accounts/tests/test_urls_default.py
cadasta/accounts/tests/test_views_api.py
cadasta/accounts/tests/test_views_default.py
cadasta/accounts/urls/default.py
cadasta/accounts/validators.py
cadasta/accounts/views/api.py
cadasta/accounts/views/default.py
cadasta/templates/accounts/account_verification.html
cadasta/templates/accounts/profile.html
cadasta/templates/accounts/resend_token_page.html

This PR enables a user to login with their registered phone. A Resend Token Page has been added to allow user to explicitly get a verification link or a verification code for verifying their phone and email.
If a user tries to login with unverified email/phone, user will be redirected to the Resend Token Page.
If user has both email and phone unverified, user account will be set to inactive and user will be redirected to the Resend Token Page.
1. Define 2 new exceptions `AccountInactiveError` and `PhoneNotVerified` errors, which will be raised when a user tries to obtain an authentication token with and unverified phone or when the user account is inacitve.
2. Add a `ResendTokenForm` to `accounts/forms.py`. User enters phone or email they're trying to verify. If the phone/email has …

Allow user to login with phone and add Resend Token Page

---

cadasta/accounts/models.py
cadasta/accounts/serializers.py
cadasta/accounts/tests/test_serializers.py
cadasta/accounts/tests/test_views_default.py
cadasta/accounts/views/default.py
cadasta/templates/allauth/account/password_reset_done.html

1. Make changes to `password_changed_reset` in `accounts/models.py`. Send email on password reset/change if user's email exists, and send SMS on password reset/change if user's phone exists.
2. Make changes to `PasswordResetFromPhoneView`. Add signal which is sent on password reset.
**Tests**
-  `PasswordResetFromPhoneViewTest: test_password_successfully_set`
3. Remove `UniqueValidator` for email from `RegistrationSerializer` and `UserSerializer`. Add validation inside `validate_email`.
**Tests**
- `test_update_insensitive_email_check` in `accounts/tests/test_serializer.py: UserSerializerTest`
- `test_insensitive_email_check` in `accounts/tests/test_serializer.py: RegistrationSerializerTest`
- As soon as it's been reviewed and approved.
- Low
- None
- **Is this PR explained thoroughly?** …

Send message on Password Reset and add separate unique email validation for serializers

---

cadasta/accounts/middleware.py
cadasta/accounts/tests/test_middleware.py

Going off of the description in [this StackOverflow article](https://stackoverflow.com/questions/11223597/django-wsgirequest-object-has-no-attribute-user-on-some-pages), #1746 appears to be related to situations where we have a redirect from `APPEND_SLASH=True`. Typically, a request works its way through the middleware stack, is sent to a view, and then a response works its way through the middleware (in opposite order). If a redirect occurs from the `CommonMiddleware` middleware but before `AuthenticationMiddleware`, the `AuthenticationMiddleware` is skipped (meaning the `user` object is not added to the `request`) and the response is sent through _all_ middleware. Our `UserLanguageMiddleware` expects that the `request` have a `user` property, but in the event of skipping the …

Handle situations where request has no User object, closes #1746

---

cadasta/core/templatetags/tags.py
cadasta/core/tests/test_tags.py
cadasta/templates/allauth/account/login.html
cadasta/templates/core/base.html

- Fixes #1747: On the login page, only add the `next` URL parameter to the "Register" link if the URL is defined.
- Also, fixes #1731 (If I understand the issue correctly): When you're on the signup page, then go to log-in the redirect is set to the sign-up page. So after you've logged you will be redirected to the sign-up page. I fixed this by adding the redirect links only if you're not coming from with the login page or the signup page. I introduced the template tag `define` so you can set a variable in a template, something which isn't possible with standard Django functionality. 
While the issues don't cause any significant damage, it still is a major inconvenience to new users. I'd vouch that we include this into the next release. 
None
None
- **Is this PR explained thoroughly?** …

Fixes #1747 -- Provide redirect only when not on sign-up or login page

---

cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/views/default.py

This PR fixes #1544 _Organization admins can remove themselves through the URL_.
Why this problem occurred? This happened because we don't have a permission action that refers to this user case: an administrator deleting themselves. 
Since it's difficult to define this very conditional action in the permission policies, I proposed to simply add a final check inside the `OrganizationMembersRemove` class before posting the member to be deleted. To do so:
1. I created a function called `admin_is_not_deleting_themselves` that checks if the current user is an administrator and if the `current_user.username == member_to_remove.username`.
3. Inside the `get()` function, I call `self.admin_is_not_deleting_themselves()` to check if the current user is an administrator trying to remove themselves. …

Fixes #1544: Org admins cannot remove themselves through the URL

---

cadasta/party/tests/test_views_default.py
cadasta/party/views/default.py
cadasta/templates/party/party_detail.html

**If you review this, please review also #1738 since they are the same.**
Note: after doing this PR I read that the issue was "on hold". I still think that it's worth fixing this issue since it's linked to direct permission over deleting things. Once the permission system is changed, this will still work. See #1739 to know why.
This PR fixes  #1693 _Party detail page shows edit and delete buttons to project users_ by applying the same strategy that has been used previously in the already-merged PR _Hide location action buttons unless user has permission to do the action_ #1268. 
Specifically:
- In `party/views/default.PartyDetail` I added the parameters `is_allowed_update_party` and 
`is_allowed_delete_party` to the context.
- In `templates/party/party_detail.html` I wrapped the edit and …

Fixes #1693: displays edit and delete button in party detail page only if has permission

---

cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/views/default.py

This PR fixes #820 with a second approach after the discussion in the closed PR _Fixes#820: maintains project.archived value when their org is archived/unarchived_ #1734.
This PR fixes the bug by keeping all projects archived even when an already-archived organization is unarchived.
For example: 
- Project 1 is archived, Project 2 is active
- Organization is archived
- Organization is unarchived
- Project 1 and Project 2 are both archived.
- As soon as it's reviewed and approved
- Low
- Close #820 
- **Is the risk level assessment sufficient?** The risks section should contain all risks …

fix bug #820: unarchiving organization does not cascade to projects

---

cadasta/party/tests/test_views_default.py
cadasta/party/views/default.py
cadasta/templates/party/relationship_detail.html

**If you review this, please review also #1735  since they are the same.**
Note: after doing this PR I read that the issue was "on hold". I still think that it's worth fixing this issue since it's linked to direct permission over deleting things. Once the permission system is changed, this can be changed easily as well. But I think it's worth integrating this small change for now.
This PR fixes #1680 by applying an approach already used in two similar cases:
- in the existing code in master: see [template](https://github.com/Cadasta/cadasta-platform/blob/d9239c8d7891b42bb393a7a2f74d34222c8a1869/cadasta/templates/spatial/location_detail.html#L22-L27), [view](https://github.com/Cadasta/cadasta-platform/blob/d9239c8d7891b42bb393a7a2f74d34222c8a1869/cadasta/spatial/views/default.py#L118-L123), …

Fixes #1680: displays edit and delete buttons only if user has permission

---

cadasta/organization/forms.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_serializers.py

1. Make changes to `OrganizationForm` , `ProjectAddDetails` and `ProjectEditDetails` in `organization/forms.py`.
Use `name__iexact` instead of `name` when filtering out org/project. `name__iexact` is used for case-insensitive exact match, check [here](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#iexact).
Add an explicit uniqueness validation in `OrganizationForm`.
**Tests**
- `OrganizationTest`: test_duplicate_name_error_case_insensitive
- `ProjectAddDetailsTest`: test_add_new_project_with_duplicate_name_case_insensitive
- `ProjectEditDetailsTest`: test_update_project_with_duplicate_name_case_insensitive
2. Make changes to `ProjectSerializer` and `OrganizationSerializer`.
Use `name__iexact` instead of `name` when filtering out org/project. `name__iexact` is used for the …

BugFix #1745, case insensitive org/project name

---

.travis.yml
requirements/common.txt
requirements/dev.txt

Update some more dependencies and packages flagged by Requires.io. No platform code needs to be updated for this batch of updates.
Probably with Sprint 21 release.
While the Travis build passes, and some very limited testing was done in the dev VM, extensive QA testing should be done (as part of QA day testing) to confirm there are no side-effects.
Continue investigating/testing updated packages flagged by Requires.io.
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate …

Update some dependencies flagged by Requires.io (IV)

---

cadasta/resources/serializers.py
cadasta/resources/views/api.py

_NOTE: This PR works towards the goals of #1400_
The export operation currently [records the relationships between Resources and system records](https://github.com/Cadasta/cadasta-platform/blob/a14f87e330653a9633326fc8f362f8384764e98b/cadasta/organization/download/resources.py#L32-L43). The API does not currently support listing links between Resources and other records, unless we tested every record individually (e.g. accessing the `/parties/<party>/resources/` endpoint).  This PR adds a `links` field to the `ProjectResources` API view.
This is independently deployable from #1400, so as soon as possible is fine. Being that this is a requirement of #1400, #1400 can't be completed without this feature.
None foreseen, this only adds new functionality, does not alter existing functionality. …

Async: Add link field to resources API

---

cadasta/organization/forms.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_serializers.py

- This PR amends PR #1770. Something went wrong during the merge and changes committed after initial commit were not reflected in the merge. Those changes are now introduced in this PR.
-As soon as it's approved
- Low
- None
- **Are all requirements met?** Compare implemented functionality with …

Amend #1770

---

README.rst
Vagrantfile
cadasta/tasks/migrations/0001_initial.py
provision/roles/cadasta/application/tasks/main.yml
provision/roles/db/development/files/pg_hba.conf
provision/roles/db/development/files/postgresql.conf
provision/roles/db/development/handlers/main.yml
provision/roles/db/development/tasks/main.yml
provision/roles/db/production/handlers/main.yml
provision/roles/db/production/tasks/main.yml
provision/roles/webserver/production/templates/uwsgi.ini

_NOTE: This PR works towards the goals of #1400_
Our asynchronous task consumers need to be able to access the Cadasta DB in order to record task results. This PR includes changes that ensure that:
1. The dev VM exposes its DB to the host machine. This is done by altering the Vagrantfile to port-forward Postgres' port (`5432`) to host machine (`5433`). This is helpful when running a worker on the host machine.
1. The results tables of the database are set up in accordance to the expectations of the Celery database result backend. This required renaming the sequence generated by Django to match the sequence expected by Celery.
1. A DB user is created via Ansible in both dev and production environments. This DB worker should only have access to Create, Read, and Update task results and to …

Async: Configure DB and Cadasta Platform dev VM to support async workers

---

cadasta/party/serializers.py
cadasta/party/tests/test_serializers.py
cadasta/party/tests/test_urls_api.py
cadasta/party/tests/test_views_api_party_relationships.py
cadasta/party/tests/test_views_api_tenure_relationships.py
cadasta/party/urls/api/relationships.py
cadasta/party/views/api.py
cadasta/spatial/serializers.py
cadasta/spatial/tests/test_views_api_spatial_relationships.py
cadasta/spatial/views/api.py
cadasta/xforms/serializers.py

_NOTE: This PR works towards the goals of #1400_
The export operation currently [writes Tenure Relationships to an XLS file](https://github.com/Cadasta/cadasta-platform/blob/a14f87e330653a9633326fc8f362f8384764e98b/cadasta/organization/download/xls.py#L55-L63). The API does not currently support listing Tenure Relationships. It does have a `/api/v1/organizations/:org/projects/:proj/relationships/tenure/` view, however [this view only supports `POST` requests](https://github.com/Cadasta/cadasta-platform/blob/a14f87e330653a9633326fc8f362f8384764e98b/cadasta/party/views/api.py#L191-L199) as it inherits from DRF's `generics.CreateAPIView` class. 
This PR updates the view to inherit from `generics.ListCreateAPIView` to allow for listing of the Tenure Relationships for the purpose of exporting …

Async: Add list view to relationships API endpoints

---

.travis.yml
cadasta/config/settings/travis.py
provision/roles/testing/tasks/main.yml
requirements/dev.txt
runtests-functional
runtests.py

_Note: This PR is branched off from PR #1774. To see the specific changes for this PR, do a branch comparison:_ https://github.com/Cadasta/cadasta-platform/compare/functest/loadfixtures...functest/accounts
This PR incorporates changes to accommodate automated User Accounts tests in the **cadasta-test** repo.
- Update the tag of **cadasta-test** repo to v0.2.1.
- Update settings for Travis to use a dummy email backend and set the max file upload size (for the future).
- Update the **runtests-functional** bash script to run non-file-upload tests using BrowserStack and the remaining tests using the local ChromeDriver.
- Update the **runtests.py** Python script to pass on extra command-line arguments to pytest when running under `--functional`.
The following conditions need to be met:
No …

Accommodate User Accounts functional tests

---

cadasta/accounts/models.py
cadasta/accounts/tests/test_models.py
cadasta/accounts/tests/test_views_default.py
cadasta/accounts/urls/default.py
cadasta/accounts/views/default.py
cadasta/core/static/css/datatables.scss
cadasta/core/static/css/header.scss
cadasta/core/static/css/main.scss
cadasta/core/static/css/reg.scss
cadasta/core/static/css/single.scss
cadasta/organization/models.py
cadasta/organization/tests/test_models.py
cadasta/templates/accounts/profile.html
cadasta/templates/accounts/user_dashboard.html
cadasta/templates/core/base.html

This PR creates a User Dashboard (UD) as defined in the Epic issue User Dashboard #1491. Specifically it addresses these open issues: [#1492](https://github.com/Cadasta/cadasta-platform/issues/1492), [ #1483](https://github.com/Cadasta/cadasta-platform/issues/1483), [#1482](https://github.com/Cadasta/cadasta-platform/issues/1482), [#1485](https://github.com/Cadasta/cadasta-platform/issues/1485), [#610](https://github.com/Cadasta/cadasta-platform/issues/610).
**Added user functionalities:** 
- A user can access their UD page by clicking on "My Dashboard" in the top-left navigation bar drop-down menu:
- In the UD, a user can see the list of organizations (if any) and respective projects (if any) that the user is part of
- The user can see their roles for each organizations and/or projects …

Create User Dashboard

---

cadasta/config/settings/dev.py
cadasta/core/tests/factories.py
cadasta/organization/download/resources.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_importers.py
cadasta/questionnaires/managers.py
cadasta/resources/models.py
cadasta/search/export/resource.py
cadasta/search/export/shape.py
cadasta/search/export/xls.py
cadasta/xforms/tests/test_model_helper.py
cadasta/xforms/tests/test_views_api.py

Changes in this PR reduce the number of `ResourceWarning` while running tests by:
- Adding `'delay': True` to the logging handler, so the log file is only open when it's needed. 
- Closing all files used in tests. 
You'll see that there are still a few `ResourceWarning` being thrown from `xforms/tests/test_views_api.py::XFormSubmissionTest`. I wasn't able to locate the origin of those. Something seems proper messed up in these tests; the number of warnings and the stack trace changes depending on what tests I run or if I comment out some of the tests. I'll look into that another time. 
Whenever; this is not urgent.
None. 
Address all other warnings. 
- **Is the PR labeled correctly?** It …

Reduce number of ResourceWarning when running tests

---

cadasta/config/settings/languages.py

- Resolves #1826: Forms containing Aymara and Garifona labels can now be submitted
- Resolves #1807: Forms containing Odia labels can now be submitted
For the next release
None
None
- **Does …

Adds languages: Odia, Aymara, Garifuna

---

cadasta/organization/forms.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_serializers.py

This PR fixes issue #1842 
- Change `clean_name` method of `OrganizationForm` to exclude the organization instance(if it exists) when checking for uniqueness of the org name.
- Make similar changes to `validate_name` method of `OrganizationSerializer`.
- Add 2 new tests to both `organization/tests/test_forms.py` and `organization/tests/test_serializers.py`.
1. **test_update_org_name_with_different_case** : This test checks if a user is allowed to change  the 
org  name to a different case. For example, if the org name is **cadasta_organization**, then the 
user should be allowed to change the org name to **CADASTA_ORGANIZATION**
2. **test_update_org_check_for_org_name_error** : This test checks the case mentioned in #1842.
- Once approved
- Low
- None
**Is this PR explained thoroughly?** …

Fix issue 1842

---

cadasta/config/permissions/group-policies.json
cadasta/core/mixins.py
cadasta/core/tests/test_auth.py
cadasta/core/tests/test_mixins.py
cadasta/core/tests/utils/cases.py
cadasta/core/views/auth.py
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/views/default.py
cadasta/templates/organization/organization_list.html

This PR mainly  introduces three new mixins in `core.views.auth`: `LoginRequiredMixin`, `PermissionRequiredMixin`, `OrganizationPermissionMixin`.
- `LoginRequiredMixin` simply replicates the functionality of tutelary's [`LoginPermissionRequiredMixin`](https://github.com/Cadasta/django-tutelary/blob/master/tutelary/mixins.py#L111). 
- `PermissionRequiredMixin` is the basic mixin to use throughout the platform when access to views is restricted. It extends Django's [`UserPassesTestMixin`](https://docs.djangoproject.com/en/1.11/topics/auth/default/#django.contrib.auth.mixins.UserPassesTestMixin), which allows us to hook custom permissions checks into `test_func`. I added docstrings so that I won't go into too much detail here, but I want to point out that:
- `get_permission_required` should …

Permissions org views

---

requirements/dev.txt
runtests-functional

This PR builds up on the changes in [PR #43](https://github.com/Cadasta/cadasta-test/pull/43) of the **cadasta-test** repo. The idea is that for PRs we run the functional test suite locally on Travis and only run the test suite using BrowserStack for commits to the `master` branch (when PRs are merged). (And as before, normal commits skip executing the test suite.)
After the **cadasta-test** PR mentioned above has been merged and tagged with `v0.2.4`.
None foreseen.
None.
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the …

Make test suite execute in less time

---

cadasta/core/form_mixins.py
cadasta/organization/forms.py
cadasta/organization/serializers.py
cadasta/organization/tests/test_forms.py
cadasta/organization/tests/test_serializers.py
cadasta/organization/tests/test_views_default_organizations.py
cadasta/organization/tests/test_views_default_projects.py

This PR removes `core.form_mixins.SuperUserCheckMixin` from the code base and refactors all forms that depended on it. 
Super users can not be identified using Tutelary's `Role` because we never actually assigned the superuser role to any users. Instead, super users can be identified using Django's `User.is_superuser` flag. 
The changes can be considered a step towards replacing Tutelary. It's not urgent but it should go into master before we have the first big chunk ready for the permissions rework. 
None
None
**Is the risk level assessment sufficient?** The risks section should contain all …

Remove `core.form_mixins.SuperUserCheckMixin`

---

cadasta/organization/forms.py
cadasta/organization/views/default.py
cadasta/templates/organization/organization_members_edit.html

- Fixes #1121: Superusers are always displayed as Administrators on organization permissions page. - Added flags for superusers in templates
- Changed how `ProjectRoleEditField` is initialized in `EditOrganizationMemberProjectPermissionForm` so that superusers are always indicated as admins. 
After 1.13.0 is released. 
None
None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or …

Fixes #1121 -- Displays permissions correctly for superusers in orgs

---

cadasta/accounts/tests/test_views_default.py
cadasta/accounts/views/default.py
requirements/dev.txt

Changes `accounts.views.RegisterView` so the user's chosen language is set when signing up. 
The PR is is not to be merged into `master`; it can be merged whenever accepted.
None
None
**Does the UI …

Set user's language when signing up

---

cadasta/config/settings/production.py
provision/roles/cadasta/install/tasks/main.yml
provision/roles/db/production/tasks/main.yml

Fixes complications while deploying to production by using variables for database access. 
- Use playbook variable `postgres_pw` for user `postgres` initialize the cadasta database. 
- Export the playbook variable `db_pass` to enviroment variable `DB_PASS`
- In Django's production settings use environment variable `DB_PASS` instead of the hard coded password. 
The secret deployment configs are updated accordingly.
ASAP
None
None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to …

Use variables for database passwords for deployment

---

cadasta/core/tests/test_auth.py
cadasta/core/views/auth.py
cadasta/organization/tests/test_views_default_users.py
cadasta/organization/views/default.py

- Adds `core.views.auth.SuperUserRequiredMixin`, which extends `LoginRequiredMixin` and  `PermissionRequiredMixin`. The mixin overwrites `test_func` so it returns `True` if the current user is a superuser. The mixin should be used for views that can only be accessed by superusers.
- Refactors `organization.views.default.UserList` and `organization.views.default. UserActivation` to use `SuperUserRequiredMixin`. 
Not going into master; can be merged whenever accepted.
None
None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with …

Refactor user management views to new permission system

---

cadasta/config/settings/production.py
provision/roles/webserver/production/files/nginx.conf
provision/roles/webserver/production/tasks/main.yml
provision/roles/webserver/production/templates/nginx-production

This PR contains a few changes to how we deploy the Cadasta-Platform.  This includes:
* Attempting to add the local IP of the AWS instance to Django's `ALLOWED_HOSTS` setting. This is important as the AWS Elastic Load Balancer will be doing healthchecks on the instance(s) attached to the load balancer. This occurs by sending a GET request to `/account/login` to test the service's health. Being that the healthcheck will be targeting a single machine, the HOST value of the request will be the machine's internal IP address (`10.*.*.*`)
* Add a default server that will simply return a 404 to the user. This is important as NGINX will try to serve _something_ to a user. If a user makes a request to NGINX with a HOST value not matching the NGINX server's `server_name` value, that server will …

New deployment configuration

---

cadasta/accounts/tests/test_views_default.py
cadasta/accounts/views/default.py

Fixes #1869 by removing all messages from the queue before adding the generic info message. 
For 1.14.0
None
None
**Does the UI work as expected?** There should be no Javascript errors in the console; …

Fix #1869 -- Clear message queue in ResendTokenView

---

cadasta/accounts/forms.py
cadasta/accounts/messages.py
cadasta/accounts/serializers.py
cadasta/accounts/tests/test_forms.py
cadasta/accounts/tests/test_serializers.py
cadasta/accounts/tests/test_views_api.py
cadasta/accounts/utils.py
cadasta/accounts/views/api.py
cadasta/organization/tests/test_views_api_users.py
cadasta/templates/accounts/profile.html

- Changes the profile template so only the phone or email form field is displayed. 
- Removed unnecessary code and tests
- Changed all tests so the user object has either a phone number or an email address
- Made the phone or email field required in the profile form, depending on the identifier the user chose when signing up
- Added a check to the serializer, so user accounts can only be created via the API with either a phone number or email address but not both
ASAP for release 1.14.0
None
None
**Is the risk level assessment sufficient?** The risks section should contain all risks that …

Fix #1863 -- Remove option to switch between phone and email identifiers

---

cadasta/organization/forms.py
cadasta/templates/organization/organization_dashboard_member.html

When discussing the #1918 bug with @SteadyCadence, we ran into an issue where a user could not get past Step 2 of the Project Creation process.
Upon inspection, it became clear that while the user was an admin for the project (all that is needed to see the project creation button), it lacked the `project.create` permission.  Without this permission, the form failed to render the organization for which the project would be created in a hidden dropdown on the form.  Being that the dropdown was hidden, it was not possible for the user to see the error rendered on the input, making the bug's cause difficult to diagnose.
~~This PR adds all orgs that a user has admin status to the ProjectAdd form's organization choicefield.~~
**UPDATE:**
This PR updates the visibility of the Add Project button …

Only show Add Project link on Organization Dashboard if user has project.create perm

---

cadasta/core/serializers.py
cadasta/core/tests/test_serializer.py

Fixes #1872: Make sure that string sanitation is always run against a `dict` for JSON fields, i.e. if the field's value is `None`, we validate against `{}`.
When ready
None 
None
**Does the UI work as …

Fixes #1872 -- Ensure JSON fields are sanitized against dict

---

cadasta/organization/forms.py
cadasta/organization/tests/test_forms.py

Fixes #1856 to display a 404 error instead of a platform error. This is achieved by querying the `OrganizationRole` object using `get_object_or_404`.
Whenever ready. Possibly for 1.15.0 or earlier
None
None
**Are all requirements met?** Compare implemented functionality with the requirements …

Fixes #1856 -- Raise 404 when user is not member of org

---

cadasta/accounts/models.py

Currently, any time that a user is saved (such as when a user logs in or changes their password), we re-apply all Tutelary permissions to that user.  This is exceptionally slow (see Cadasta/django-tutelary#39). I'm unsure if this is actually needed, rather I believe that we should only re-assign permissions if the permissions changed (such as needing to add the 'default' permission for some reason).
Anytime.
I'm uncertain if there was a good reason to re-apply permissions on every save. The [change that added the code](https://github.com/Cadasta/cadasta-platform/commit/7956a82ddfb5369081278c17c33480fba201f96f#diff-1ec82efacfd767281c32995e3d9b1547R53) doesn't seem to offer much insight. 
-
**Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. …

Avoid assigning policies on user save if user already has default policy

---

cadasta/core/fixtures/__init__.py

Now that we are using the `is_superuser` field for the `User` model, we need to ensure that the 2 superusers in our standard fixtures are actual superusers.
Anytime.
None.
Devs should reload fixtures if they want full superusers in their dev VM.
**Are all requirements met?** Compare implemented …

Ensure that superusers in fixtures are full superusers

---

CHANGELOG.md
cadasta/core/backends.py
cadasta/core/tests/test_backends.py

Add `close()` method to our used cache class.
@oliverroick noticed that PR django/django#7200 introduced a change to Django 1.11 which keeps Django from closing memcached connections.  The reasoning behind this being that libmemcached should handle connections internally.  This change seems to be the cause for our cache connection errors that began occurring after deployment of [release v1.14.1](https://github.com/Cadasta/cadasta-platform/releases/tag/v1.14.1) in which we upgraded to Django 1.11.  While we are unsure why it appears that libmemcached is not in-fact closing our connections, it does seem to be our best candidate for a bugfix.  The `close()` method was originally added to fix the issue of unclosed connections (https://code.djangoproject.com/ticket/5133), however apparently …

Add close method to cache

---

cadasta/xforms/mixins/model_helper.py
cadasta/xforms/tests/test_model_helper.py
cadasta/xforms/views/api.py

We were seeing issues where one partner wasn't able to submit questionnaires via ODK.  
The group `tenure_relationship_attributes` in the form in question contains two questions which both have a `relevant` condition. When you select any tenure type that is not `CO - Concessionary Rights` you never get to any of these questions in the form. In this case, ODK sends the response to question group `tenure_relationship_attributes` as an empty string. The platform expects a `dict` hence the exception. 
Check whether the object provided has the attribue `keys` before trying to drill down the question group. This will skip all string-like responses. 
Need to deploy to staging and verify
ASAP. 
None.
None.
**Is this PR explained thoroughly?** All code changes must be accounted for in the PR …

Handle questiongroups submitted as string by ODK

---

cadasta/core/serializers.py
cadasta/core/tests/test_views_api.py
cadasta/core/views/api.py
cadasta/party/tests/test_serializers.py
cadasta/questionnaires/tests/test_attr_schemas.py
cadasta/spatial/tests/test_serializers.py
cadasta/xforms/mixins/model_helper.py
cadasta/xforms/tests/test_model_helper.py
cadasta/xforms/tests/test_views_api.py
requirements/common.txt

Following the changes in https://github.com/Cadasta/django-jsonattrs/pull/39, we need to adapt the way we handle the `ValidationError` on the platform side. I decided to implement two solutions that were mentioned in the corresponding discussions:
- I updated `JSONAttrsSerializer`'s `validate_attributes` to catch unknown keys and return the appropriate error. I wanted to return an error that complies with DRF's practices; the error message should accessible via the `attributes` key in the response. The `ValidationError` is raised when the model is saved, so it would require a great deal of work to construct and return the correctly structured error. I further believe that the error should be caught during the data-validation stage and not when the model is saved. 
- As an additional layer …

Improve handling of ValidationErrors for API

---

cadasta/party/tests/test_models.py
requirements/common.txt

Fixes #1656 
* Update `django-jsonattrs` to not attempt to validate the contents of a `jsonattrs` against that field's schema when reading from the field.  Instead, we will only scrutinize the data when insterting it into the field.
* Has the bonus effect of improving response times for API endpoints that include `jsonattrs` fields.
On `master` branch, in shell:
```
$ DJANGO_SETTINGS_MODULE=config.settings.dev_debug ./manage.py shell_plus`)
```
Use the `cpaste` command and paste:
```py
import json
from django.db import connection
from rest_framework.renderers import JSONRenderer
from organization.models import Project
from spatial.serializers import SpatialUnitSerializer
_id = "asd"
with connection.cursor() as c:
sql = "INSERT INTO {table} ({columns}) VALUES ({values})"
data = [
('id', …
```

Test newest jsonattrs lib

---

cadasta/config/settings/production.py
provision/roles/cadasta/install/tasks/main.yml
provision/roles/webserver/production/templates/uwsgi.ini

Ensure `environment` is available on the Sentry logs and that `release` is better than just the git sha.
Set the `environment` detail for Sentry from the `SENTRY_ENVIRONMENT` environment variable. This will match the `identifier` provided by Ansible (same thing used to populate the template identifying staging/demo/platform systems).
Set the `release` environment to the output of `git symbolic-ref -q --short HEAD || git describe --tags --exact-match`, which will report the branch name if a branch is checked out or the tag name if the codebase is checked out from a tag.
Finally, I'm putting the git sha as a tag onto the sentry logs which seems good to keep.
Comment out all other details from the `production` settings (outside of the `RAVEN_CONFIG`), spin up the django shell and examine the …

Set sentry environment via env, use git to provide release

---

cadasta/templates/organization/project_attrs_import.html
cadasta/templates/organization/project_defaults_import.html
cadasta/templates/organization/project_select_import.html

After we deployed `v1.17.0`, the import pages in all projects throw a `502 Bad Gateway`. Our debug logs show stack overflow for these events, which causes the server to crash and restart. 
The issue is caused by an `if`  statement in the template; if removed the page renders as expected. 
I don't fully understand the purpose of the code in question, why it's there and what it does. Looking at the template itself and testing out different scenarios it seems like the condition is never met and the template in the `else` branch is always rendered. I'm assuming the code is not needed. 
The reason we haven't seen the error before is likely because of some changes to our logging setup, when we switched from Opbeat to Sentry. 
Removed the faulty code. 
Add the following logger to the …

Remove recursive template code

---

cadasta/core/form_mixins.py
requirements/common.txt

If you have a non-required select field in a questionnaire, it is possible to leave that field blank in ODK.
If you edit the dataset on the website and save the record, a value is assigned to previously blank select fields.
The issue is that we don't support the concept of "no selection" on the website and thus the first value in the select field is automatically selected.
I added an empty option to all select fields. I chose to added it to all fields instead of only the non-required ones to enforce that users actually select a value for required fields instead of just using the option selected by default. 
I also updated to the latest kombu version because the build on Travis would fail otherwise. 
Create a new project using [this …

 Add empty option to select fields

---

cadasta/tasks/consumer.py
cadasta/tasks/tests/test_consumer.py

If our task consumer loses connection to the DB, it will continually try and fail to use that same connection, throwing either a `OperationalError` (the first time) or `InterfaceError` (every following time) when attempting to save a `BackgroundTask` to the database.
When a failed DB connection is caught, Django's `close_old_connections()` function is called which automatically closes any bad connection.  When our system then tries to use the connection, a new connection is opened.  The message is never acknowledged when a bad connection occurs, ensuring that it will be put back in the queue for processing after the SQS visibility timeout expires.
I think the tests are clear enough regarding out handling of the errors. To replicate the error itself, open your Django shell and in another …

Reset DB connections if connection is lost

---

.travis.yml
provision/roles/db/development/files/postgresql.conf
provision/roles/db/development/tasks/main.yml
provision/shared_vars.yml

Upgrades the dev and test environment to Postgres 9.5. 
Postgres 9.4 is no longer supported and cannot be installed. 
Updates all references from Postgres 9.4 to 9.5
Spin up a fresh development environment; run the tests or the test server.

Upgrade dev env to Postgres 9.5
