app/package.json, app/src/js/account/components/Login.jsx, app/src/js/account/components/Password.jsx, app/src/js/account/components/PasswordReset.jsx, app/src/js/account/components/PasswordResetConfirm.jsx, app/src/js/account/components/Profile.jsx, app/src/js/account/components/RegistrationForm.jsx, app/src/js/messages/components/Message.jsx, app/src/js/settings.js, app/src/locale/gettext.po, app/test/account/components/test_login.js, app/test/account/components/test_password.js, app/test/account/components/test_password_reset.js, app/test/account/components/test_password_reset_confirm.js, app/test/account/components/test_profile.js, app/test/account/components/test_registerfrom.js
It uses [formsy-react](https://github.com/christianalfoni/formsy-react) and [formsy-react-components](https://github.com/twisty/formsy-react-components) to setup form fields and to enable client-side form field validation. 
Existing tests needed to be adapted slightly. New tests have been added to ensure that forms are not submitted when invalid.
=> Implements form field validation for user accounts

app/src/css/_variables.scss, app/src/css/main.scss, app/src/js/core/components/App.jsx, app/src/js/core/components/Footer.jsx
=> Footer & Footer CSS

.travis.yml, app/src/js/settings.js, app/src/locale/gettext.po, cadasta/config/settings/dev.py, cadasta/config/settings/travis.py, cadasta/core/views.py, cadasta/organization/models.py, cadasta/organization/tests/test_views.py, cadasta/organization/views.py, provision/roles/cadasta/application/tasks/main.yml, requirements/common.txt
- Updates to organization views and associated tests to work with new django-tutelary.
- Use django-tutelary 0.1.3 from PyPI.
- Update Djoser to 0.4.3.
- Small change to get tests working, due to upgrade in Djoser, which now tests `SEND_ACTIVATION_EMAIL` setting before making new users active.
=> Update for new tutelary functionality

cadasta/accounts/models.py, cadasta/accounts/serializers.py, cadasta/config/urls.py, cadasta/organization/models.py, cadasta/organization/serializers.py, cadasta/organization/tests/factories.py, cadasta/organization/tests/test_serializers.py, cadasta/organization/tests/test_views.py, cadasta/organization/urls/organizations.py, cadasta/organization/urls/users.py, cadasta/organization/views.py, requirements/common.txt
Serializers and endpoints to:
- List all users (with filtering, searching and sorting)
- Retrieve a single user
- Update a user (particularly a user's active/inactive status)
=> User management API

cadasta/accounts/tests/factories.py, cadasta/core/factories.py, cadasta/core/management/commands/loadfixtures.py
Creates test data for users, organizations, roles and (eventually) projects.
=> Created management command 'loadfixtures'

.travis.yml, SHELF.md, cadasta/accounts/templates/profile.html, cadasta/accounts/tests/test_default.py, cadasta/accounts/views/default.py, cadasta/templates/allauth/account/login.html, cadasta/templates/allauth/account/signup.html, functional_tests/accounts/test_login.py, functional_tests/accounts/test_profile.py, functional_tests/accounts/test_registration.py, functional_tests/base.py, functional_tests/pages/Login.py, functional_tests/pages/Profile.py, functional_tests/pages/Registration.py, functional_tests/pages/base.py, provision/roles/testing/tasks/main.yml
=> Get all functional tests working again

cadasta/organization/views/api.py, requirements/common.txt
Split PermissionRequiredMixin into "normal" and API cases.
=> Upgrade to django-tutelary 0.1.10

functional_tests/accounts/test_login.py, functional_tests/accounts/test_profile.py, functional_tests/accounts/test_registration.py, functional_tests/base.py, functional_tests/run.py
- Add XPath whitespace normalisation method
- Fix calling sequence for pytest.main
=> Functional test fixes

functional_tests/base.py, functional_tests/run.py, provision/roles/cadasta/development/tasks/main.yml, provision/roles/testing/tasks/main.yml
Replace PhantomJS because it only works intermittently on Travis.
=> Firefox and Xvfb for functional tests

cadasta/core/management/commands/loadfixtures.py, cadasta/core/tests/factories.py
- added organization logos
- removed unnecessary argument options
- fixed --delete issue that was leaving behind extra roles/policies
- moved core/factories.py into core/tests/factories.py
- added [documentation](https://github.com/Cadasta/cadasta-platform/wiki/Loading-test-data)
=> Cleaned up test data. Again.

functional_tests/base.py, functional_tests/pages/Users.py, functional_tests/users/test_activation.py, functional_tests/users/test_page_access.py, functional_tests/users/test_page_list.py
> Eugene: make me a PR!  You'll need to rebase your branch, but it shouldn't cause you any trouble -- there's just one merge conflict and it's obvious how to fix it (I checked that it all works, but you should do the rebase yourself, just in case you have local changes you've not yet committed).  You'll also need to fix one failing test (test_nonloggedin_user in test_page_access.py), because the treatment of non-logged in users has changed a bit: they get redirected to the login page rather than getting a "permission denied" message.
Branch rebased (merge conflict resolved). Failing test fixed. Local changes committed. Squashed branch. Git pushed. Pull requested.
=> Add initial set of users management UI functional tests

cadasta/core/static/css/main.scss, cadasta/core/static/css/reg.css, cadasta/templates/organization/project_dashboard.html, cadasta/templates/organization/project_wrapper.html
Removed reg-area specific css to reg.css
Added project wrapper template, adjusted project dashboard
=> New project wrapper template

cadasta/organization/tests/test_widgets.py, cadasta/organization/views/default.py, cadasta/organization/widgets.py, cadasta/templates/organization/project_add_details.html
- Always show Organzation select field when project is not added from organizations
- Display Private/Public toggle state correctly
=> Fix #195 -- Correct display of project forms

cadasta/organization/tests/test_views_api_projects.py, cadasta/organization/views/mixins.py, functional_tests/base.py, functional_tests/common_test_data/common_test_data_1.py, functional_tests/pages/Project.py, functional_tests/pages/ProjectAdd.py, functional_tests/pages/ProjectList.py, functional_tests/pages/Registration.py, functional_tests/projects/test_project_access.py, functional_tests/projects/test_project_add.py, functional_tests/projects/test_project_add_duplicate.py, functional_tests/projects/test_project_list_access.py, functional_tests/projects/test_project_list_contents.py
Couple of tests failing and commented out (see issue #188).  @linzjax is
working on that.
=> Functional tests for projects UI

cadasta/core/static/js/map_utils.js, cadasta/organization/models.py, cadasta/organization/tests/test_models.py, cadasta/templates/organization/project_add_extents.html, functional_tests/pages/ProjectAdd.py
Added logic into model to check if project extent is within the map bounds.
Added bounding box to project_add_extent map.
This feels really hacky, but it works. If there's a better way to do this I'm all for it.
=> Fixes #213: Points are now centered on the map.

cadasta/resources/tests/test_validators.py, cadasta/resources/validators.py
Added MIME/media types for TIFF, GIF, old Excel (.xls), Office Open XML Workbook (.xlsx), and Office Open XML Document (.docx) file types.
=> Fixes #279

cadasta/organization/download/resources.py, cadasta/organization/download/xls.py, cadasta/organization/forms.py, cadasta/organization/messages.py, cadasta/organization/models.py, cadasta/organization/tests/test_downloads.py, cadasta/organization/tests/test_forms.py, cadasta/organization/tests/test_urls_default.py, cadasta/organization/tests/test_views_default_projects.py, cadasta/organization/urls/default/organizations.py, cadasta/organization/views/default.py, cadasta/party/tests/test_views_default.py, cadasta/questionnaires/tests/test_attr_schemas.py, cadasta/questionnaires/tests/test_managers.py, cadasta/questionnaires/tests/test_serializers.py, cadasta/questionnaires/tests/test_views_api.py, cadasta/resources/models.py, cadasta/resources/tests/factories.py, cadasta/resources/tests/test_forms.py, cadasta/resources/tests/test_managers.py, cadasta/resources/tests/test_models.py, cadasta/resources/tests/test_serializers.py, cadasta/resources/tests/test_validators.py, cadasta/resources/tests/test_views_api.py, cadasta/resources/tests/test_views_default.py, cadasta/spatial/tests/test_views_default.py, cadasta/templates/organization/project_download.html, cadasta/templates/organization/project_wrapper.html, cadasta/templates/resources/table_add_lib.html, requirements/common.txt
- Data download as XLS
- Resources download as Zip
- Combined data and resources download as Zip
=> Adds data download

cadasta/organization/models.py, cadasta/spatial/models.py, cadasta/spatial/tests/test_models.py
Probably not the best way to do this, but at least temporarily fixes the issue of world spanning polygons. Also added the same login to spatial units.
=> Fixes 333 and Fixes 332 (temporarily)

cadasta/core/static/js/map_utils.js, cadasta/organization/tests/test_views_default_projects.py, cadasta/organization/views/default.py, cadasta/spatial/views/default.py, cadasta/templates/organization/project_dashboard.html, cadasta/templates/spatial/location_add.html, cadasta/templates/spatial/location_map.html, cadasta/templates/spatial/location_wrapper.html
- Show project boundary and locations on all maps
- DRY-out JavaScript that creates features on the map
- Improvements to map styling
=> Improve map display

cadasta/organization/tests/test_forms.py, cadasta/organization/tests/test_views_default_projects.py, cadasta/questionnaires/managers.py, cadasta/questionnaires/tests/test_attr_schemas.py, cadasta/questionnaires/tests/test_managers.py, cadasta/questionnaires/tests/test_serializers.py, cadasta/questionnaires/tests/test_views_api.py, cadasta/xforms/serializers.py, cadasta/xforms/tests/test_serializers.py
Thanks @linzjax and @amplifi for pointing to the solution.
=> Fixes #417 -- Fixes naming of form download URLs

cadasta/xforms/mixins/model_helper.py
For some reason geoshape was duplicating the second point, not the first. Now removing the last point and connecting it to the first.
=> Geoshape glitch work around.

cadasta/xforms/mixins/model_helper.py, cadasta/xforms/serializers.py, cadasta/xforms/tests/files/test_resources.py
also checking to see if photos exist. Need to find a better what to do this (not relying on what the user labels it), but it works for now.
=> XForm attributes are now loaded properly

cadasta/party/views/default.py, cadasta/resources/views/default.py
Some views missing the "superuser aware" mixin.
=> Fix #452: user menu visibility

cadasta/templates/core/base.html
Hides users hamburger menu option to everyone but superuser.
=> Hamburger menu conditional users

functional_tests/base.py, functional_tests/common_test_data/common_test_data_1.py, functional_tests/organizations/test_organization_list.py, functional_tests/pages/Project.py, functional_tests/pages/ProjectAdd.py, functional_tests/pages/ProjectList.py, functional_tests/projects/test_project_add.py, functional_tests/projects/test_project_list_access.py
Made all functional tests internally deterministic. (External factors, like network failure, will still add some randomness.) Also fixed lint errors.
=> Fix #457: Remove randomness from functional tests

cadasta/templates/resources/table_add_lib.html
Removed form-control class from checkbox
Completes #436.
=> Checkbox focus css fix

cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/core/static/css/single.scss, cadasta/templates/core/base.html, cadasta/templates/resources/form.html, cadasta/templates/resources/project_add_existing.html, cadasta/templates/resources/project_add_new.html, cadasta/templates/resources/table_sm.html, cadasta/templates/spatial/location_detail.html
Formatting changes to datatable header and footer, updated error message on upload new resource page, fixed responsiveness in location resources table for medium screens.
Completes #446, #498, partial #344.
=> Datatable formatting

cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/core/static/css/reg.scss
Fixed css bug I introduced in last merge from #344 (page-content class)
asap
none
none
--------------------------------------------------------------------
Fixing css for page-content
Reg form css
=> Page content css bug fix

cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/templates/organization/organization_dashboard.html, cadasta/templates/organization/project_dashboard.html, functional_tests/pages/Organization.py, functional_tests/pages/OrganizationMemberList.py
- Organization overview and project overview - adds details of url, and contact names with email and phone numbers.  Completes #372.
- As soon as possible
- None
----------------------------------
Overview detail css
Spacing updates
=> Seav's branch changes

cadasta/config/settings/dev.py, cadasta/config/settings/production.py, cadasta/xforms/views/api.py
- Add logging configuration to dev settings
- Update **dev** and **production** settings to include _xform.submissions_ logger
- Add _date/time_ and _loglevel_ to logging output
- Update xforms api view to use new logging configuration
Can be merged immediately, no preconditions.
None.
None required.
=> Improved logging configuration

cadasta/templates/core/base.html
Added people tracking so we can choose which tutorial to display based on new users.
Before Sprint 7 release.
None foreseen.
Once code is on demo, need to ensure tracking is working correctly in inlinemanual.
=> Added people tracking

cadasta/config/urls/default.py, cadasta/core/tests/test_views_default.py, cadasta/core/views/default.py, cadasta/templates/500.html
Adds a basic 500 error page and related view.
None.
None required.
=> Add custom 500 error page

cadasta/core/management/commands/loadstatic.py
Quick fix for error introduced by #633.
Right away.
None.
None.
=> Quick fix!

cadasta/config/settings/default.py
- Hides arabic from language dropdown in footer until right to left layout is addressed (next sprint)
When convenient, for sprint 8
- None
------------------------------------------------------------------------------
Hiding until right to left layout can be addressed.
Removed indent
Added indent
=> Hiding arabic language option

cadasta/config/locale/en/LC_MESSAGES/django.po, cadasta/config/settings/default.py
- Add Portuguese language.
- Update source message catalogue.
Any time.
None.
None.
=> Language support

cadasta/xforms/mixins/model_helper.py
Ensure geopoint type gets parsed correctly when all geotype questions are present in xlsform.
Immediately
None
None required
=> Fixing #643

cadasta/core/static/css/footer.scss, cadasta/core/static/css/main.css, cadasta/core/static/css/orgs.scss, cadasta/templates/core/base.html, cadasta/templates/organization/organization_dashboard.html
- Fixed responsive css for org overview page
- Fixed responsive css for registration footer
- As convenient
- None required
-----------------------------------------------------------------------------------
Adjusted footer css for dashboard and registration
Adjusted padding
=> Org overview page and footer changes

cadasta/xforms/mixins/model_helper.py, cadasta/xforms/tests/files/test_resources.py, cadasta/xforms/tests/test_views_api.py
- fixes issue #698 
Whenever.
None
None
=> Fixes formatting issue caused by setting location_geometry to geoshape

cadasta/accounts/models.py, cadasta/organization/tests/test_views_default_projects.py, cadasta/templates/organization/organization_dashboard.html, cadasta/templates/organization/organization_members_edit.html, cadasta/templates/spatial/relationship_add.html
Some minor fixes, so I can feel I have accomplished something today:
- Fix #740 -- Change label from Tenure Type to  Relationship Type
- Remove unnecessary get_full_name() from User model
Anytime
None.
=> Small fixes

cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/core/static/css/orgs.scss, cadasta/templates/organization/organization_members_edit.html
- Updated member permissions layout to have Save/ Cancel buttons at bottom of entire page
- Removed redundant css
- For this sprint
- None
---------------------------------------------------------
Closes #627 
Member permission page layout and CSS updates
=> Updated member permissions layout

cadasta/organization/forms.py, cadasta/organization/views/default.py, cadasta/spatial/forms.py, cadasta/spatial/widgets.py, cadasta/templates/allauth/account/login.html, cadasta/templates/allauth/account/signup.html, cadasta/templates/core/dashboard.html, cadasta/templates/organization/download/shp_readme.txt, cadasta/templates/organization/organization_dashboard.html, cadasta/templates/organization/organization_list.html, cadasta/templates/organization/organization_members.html, cadasta/templates/organization/organization_members_add.html, cadasta/templates/organization/organization_members_edit.html, cadasta/templates/organization/organization_wrapper.html, cadasta/templates/organization/project_add_details.html, cadasta/templates/organization/project_attrs_import.html, cadasta/templates/organization/project_dashboard.html, cadasta/templates/organization/project_download.html, cadasta/templates/organization/project_edit_details.html, cadasta/templates/organization/project_list.html, cadasta/templates/organization/project_wrapper.html, cadasta/templates/party/party_detail.html, cadasta/templates/party/relationship_edit.html, cadasta/templates/party/resources_list.html, cadasta/templates/resources/form.html, cadasta/templates/spatial/location_form.html, cadasta/templates/spatial/relationship_add.html
Add translation tags for (I hope...) all the strings in templates missing them.
Any time.
None.
None.
=> Fix untranslatable strings mostly in templates

cadasta/organization/tests/test_views_default_organizations.py, cadasta/organization/tests/test_views_default_projects.py, cadasta/organization/views/default.py, cadasta/templates/organization/organization_list.html, cadasta/templates/organization/project_list.html, functional_tests/fixtures/common_test_data_1.py, functional_tests/fixtures/common_test_data_2.py, functional_tests/organizations/test_organization_list.py, functional_tests/projects/test_project_list_contents.py
- Check to see if any viewable projects/organizations are archived
- Add Archived/Active filter if any are archived.
- Fixes #762 
During bugfix week.
None
None
=> Archive filter appears even if pagination occurs

cadasta/organization/download/base.py, cadasta/organization/tests/test_downloads.py
- Updated formatting to join arrays (select_multiple) into a comma delimitated string.
- Select_multiple is now compatible with data downloads.
- Fixes #780 
Before release
None
None
=> Updated data download formatting for select_multiple

cadasta/spatial/widgets.py, cadasta/templates/organization/organization_list.html, cadasta/templates/organization/organization_wrapper.html, cadasta/templates/organization/project_add_details.html, cadasta/templates/organization/project_edit_details.html, cadasta/templates/organization/project_list.html, cadasta/templates/party/relationship_edit.html, cadasta/templates/spatial/location_add.html, cadasta/templates/spatial/location_detail.html, cadasta/templates/spatial/location_edit.html, cadasta/templates/spatial/location_form.html, cadasta/templates/spatial/relationship_add.html
Fix one missing `ugettext`.
Any time.
None.
None.
=> Fix missing ugettext call

cadasta/spatial/tests/test_views_default.py, cadasta/spatial/views/default.py
Fixing https://github.com/Cadasta/cadasta-platform/issues/754
Issue Description : Can't add a resource in a location uploading a file
-
-
-
No preconditions
-
-
-
No Risks
-
-
-
No follow up actions
-
-
-
=> Fixing https://github.com/Cadasta/cadasta-platform/issues/754

cadasta/templates/resources/project_list.html
- Add a dummy value for `archive_url` in the `resources/project_list.html` template in the hope that it will stop some of these 502 errors we've been seeing.
Right away, so we can test it on staging.
None?
Check whether it makes a difference.
=> Attempt "fix" for #770

cadasta/core/static/css/_variables.scss, cadasta/core/static/css/main.css, cadasta/core/static/css/widgets.scss, cadasta/templates/organization/project_list.html, cadasta/templates/resources/table.html
- CSS for date picker
- Project index column width adjustment
- Username/ fullname swap on resources table
- Whenever possible
- None
- None
---------------------------------------------------------
Completes #771
Widen org column in project index, branded date picker, swap username
and fullname in resource table
=> CSS adjustments

cadasta/templates/organization/organization_dashboard.html, functional_tests/organizations/test_organization.py
Copy of #759 for rebasing and merging.
=> Kavindya89 bugfix#758

cadasta/config/settings/dev.py, cadasta/config/settings/travis.py, cadasta/core/fixtures.py, cadasta/core/management/commands/loadfixtures.py, cadasta/core/tests/test_management_commands.py, cadasta/core/views/default.py, cadasta/organization/views/default.py, cadasta/organization/views/mixins.py, cadasta/spatial/views/default.py, requirements/common.txt
Some performance improvements: some in django-tutelary, some in django-jsonattrs, some in the main platform code.  Mostly about restricting the fields we load for some SQL queries, and using Django's `select_related` to bundle some other sets of queries up into joins.
Any time.
I think it's mostly OK.
Look at performance again.
=> First round of performance improvements

provision/roles/webserver/production/templates/uwsgi.ini
Adds the final piece to pass through the new env vars for memcached and Opbeat, because committing all the files at the same time is too easy.
Anytime
None; provisioning change only.
None
=> uWSGI needs env vars

cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/core/static/css/wizard.scss, cadasta/organization/views/default.py, cadasta/templates/organization/project_add_wrapper.html, cadasta/templates/organization/project_attrs_import.html, cadasta/templates/organization/project_defaults_import.html, cadasta/templates/organization/project_import_wrapper.html, cadasta/templates/organization/project_select_import.html
- Added css layout to import wizard pages for consistency.
- Removed unused text on project add wizard steps.
- Anytime, for Sprint 10
- None
-----------------------------------------------------------------------
Completes #565
Import changes
Changes to text and field layout
Parsley update
Design for data import
Import changes
Changes to text and field layout
Parsley update
Adding wizard to data import
Label changes on page 3
=> Design for data import

cadasta/accounts/models.py, cadasta/accounts/tests/test_models.py, cadasta/organization/models.py, cadasta/organization/tests/test_models.py, cadasta/party/models.py, cadasta/party/tests/test_models.py, cadasta/questionnaires/models.py, cadasta/questionnaires/tests/test_models.py, cadasta/resources/models.py, cadasta/resources/tests/test_models.py, cadasta/spatial/models.py, cadasta/spatial/tests/test_models.py, cadasta/xforms/models.py, cadasta/xforms/tests/test_models.py
Adds or changes `__repr__` methods on models to create more meaningful print-outs in logs and on Opbeat. 
Any time.
None
None
=> Add useful __repr__ methods to models

cadasta/templates/spatial/location_form.html
- Removes double numbering
- Anytime
- None
- None
------------------------------------
Completes #874
=> Removed extra number

cadasta/core/static/css/main.css, cadasta/core/static/css/single.scss, cadasta/core/static/js/parsley.js
- Completes #872 
- Adjusts stats numbers to avoid overlap
- Adjusts parsley js comment to avoid Safari console error
- Anytime
- None
- None
=> Adjusted stats number sizes and added parsley comment fix

cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/templates/core/base.html, provision/roles/cadasta/production/tasks/main.yml, provision/roles/cadasta/production/templates/inline-manual-player
- Completes #722 
- Swaps "i" for "?" icon in header
- Used new myplayer variable to use correct inline manual player per site
- Anytime
- None
- Test help panel once released (should have different help topics available per site)
-----------------------------------------
Space to trick timeout exception
Removed switch statement
Add myplayer var via Ansible template
Update default myplayer for local dev environment
=> Updated help link, embedded player per site

cadasta/core/static/js/file-upload.js, cadasta/templates/organization/project_add_details.html, cadasta/templates/organization/project_edit_details.html
- Clears residual error messages when bad questionnaire file is removed
- Completes #679 
- Anytime, for Sprint 10
- None
------------------------------------------------
Cleanup spacing
=> Added script for removing file upload errors

requirements/common.txt
Django upgrade to 1.9.11
ASAP
Low
None
=> Django upgrade to 1.9.11

cadasta/core/static/js/inline-manual-player.js, cadasta/templates/core/base.html, provision/roles/cadasta/production/templates/inline-manual-player
- Completes #912
- Moves people tracking out of inline-manual-player.js
- Anytime
- None
=> Moved user tracking to base

functional_tests/projects/test_project.py
- Provides are temporary work-around for #902 
- Disables failing tests for the time being until #919 is resolved
Anytime
None
Further investigate the root cause for these intermittent failures and implement a long-term solution.
=> Re: #902 -- Disable failing functional tests temporarily

CHANGELOG.md
Updates changelog for v1.2.0 and prior alphas. 
Anytime
None
None
=> Update changelog for v1.2.0

cadasta/core/static/css/footer.scss, cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/core/static/css/reg.scss, cadasta/core/static/css/wizard.scss, cadasta/organization/tests/test_views_default_projects.py, cadasta/organization/views/mixins.py, cadasta/templates/allauth/account/login.html, cadasta/templates/organization/organization_list.html, cadasta/templates/organization/organization_members.html, cadasta/templates/organization/organization_wrapper.html, cadasta/templates/organization/project_dashboard.html, cadasta/templates/organization/project_list.html, cadasta/templates/organization/project_wrapper.html, cadasta/templates/party/party_detail.html
- Completes #677 
- Login screen added messaging for redirected anonymous users
- Modified layout for orgs and projects for anonymous and registered users without project permissions
- Added import data to project "Add location" button
- H1 and H2 css tweaks for long titles 
- Responsive css tweaks for smallest screens
- Anytime, for Sprint 11
- None
=> User layout changes

cadasta/core/static/css/_variables.scss, cadasta/core/static/css/main.css, cadasta/core/static/js/parsley.js, cadasta/core/static/js/parsleyAddValidator.js, cadasta/templates/allauth/account/password_change.html, cadasta/templates/allauth/account/password_reset_from_key.html, cadasta/templates/allauth/account/signup.html
- Completes client-side messaging for #735 
- Adds help-notes and password validation on registration, change password, and reset password pages
- When possible, for sprint 11
- Issues mentioned in server-side PR
- Update transifix with translations
------------------------------------------------
Updates to registration page
Updates to change password page
Updates to password reset page
=> Password validation on registration page - client-side

CHANGELOG.md
Updates changelog for v1.3.0-alpha.2
Anytime
None
None
=> Update changelog for staging release

cadasta/core/static/css/main.scss, cadasta/core/static/js/parsleyAddValidator.js
- Fixes error message text
- Soon as possible
- None
- None
-----------------
Only partially completes #984 -
=> Fix error message text

cadasta/questionnaires/tests/test_views_api.py, cadasta/questionnaires/views/api.py, cadasta/templates/organization/project_edit_details.html
- Fixed misspelled "disabled" in alert messaging
- Whenever possible
- None
- None
=> Fixed misspelling

cadasta/organization/importers/base.py
- Malformed error message during import when a required attribute is missing.
Low risk.
None required.
=> Fix for #970

cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/templates/organization/project_select_import.html
- Completes #970 
- Updated flow pattern to match top-down
- Updated text descriptions
- Recommend removing first file type question with task #976 
---------------------------------------
Layout and text changes
Removing file type descriptions
=> Project data import ui changes

provision/roles/webserver/production/tasks/main.yml
Implements an alternative method of static asset collection via Django management command.
Anytime. Provisioning change only; no impact to platform code.
Very low
None
=> Tidier static content handling

requirements/dev.txt
Resolve errors encountered in Travis due to fake-factory package being renamed to Faker by updating factory_boy from 2.7.0 to 2.8.1.
ASAP.
None.
None.
=> Update factory_boy to 2.8.1

requirements/common.txt
- Updates Pillow to 3.4.2, because previous version was insecure
ASAP
Low
None.
=> Update Pillow to 3.4.2

CHANGELOG.md
Updates changelog for v1.4.0
Anytime
None
None
=> Update changelog for v1.4.0

cadasta/core/static/css/forms.scss, cadasta/core/static/css/header.scss, cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/core/static/css/modals.scss, cadasta/core/static/css/single.scss, cadasta/resources/models.py, cadasta/templates/organization/organization_add.html, cadasta/templates/organization/organization_dashboard.html, cadasta/templates/organization/organization_wrapper.html, cadasta/templates/organization/project_add_wrapper.html, cadasta/templates/organization/project_wrapper.html, cadasta/templates/party/party_detail.html, cadasta/templates/party/relationship_detail.html, cadasta/templates/party/relationship_edit.html, cadasta/templates/party/relationship_resources_add.html, cadasta/templates/party/resources_add.html, cadasta/templates/party/resources_list.html, cadasta/templates/resources/project_add_existing.html, cadasta/templates/resources/project_detail.html, cadasta/templates/spatial/location_add.html, cadasta/templates/spatial/location_detail.html, cadasta/templates/spatial/location_edit.html, cadasta/templates/spatial/location_form.html, cadasta/templates/spatial/relationship_add.html, cadasta/templates/spatial/resources_add.html
-  Replaced ellipsis with "More actions" on project and organization wrapper
-  Replaced ellipsis with Edit and Delete buttons for locations and relationships
-  Updated party detail and resource detail page to match interaction
-  General CSS cleanup of main.scss to compartmentalize into smaller sections
- Low risk
- These menus should be included as part of the permissions audit since some of these actions are limited to only specific roles/users.
=> Ellipsis menu rework

cadasta/templates/organization/organization_members_edit.html
- Added minimal html to separate Role label from Role field for read-only situation
- Goes along with #823 
- Low
- None
=> Separate Role and Administrator

cadasta/makemessages
Fixes #926.
The untranslated string reported in #926 belongs to the source of django-allauth, which doesn't provide Indonesian translations. We can pull in messages from third-party libraries into our translation sources by setting a symlink to the source of the libraries.
This PR adds a bash script (`makemessages`) that should be used to create translation sources. It creates the required symlinks, pulls the messages and removes the symlinks after the process is finished. 
Currently, untranslated strings are pulled in from django-allauth and django-buckets. If in the future, we need to pull messages from other libraries, the corresponding library names can be added to the `LIBS` list at the beginning of the script. 
Anytime.
If a third-party library provides translations in a certain …
=> Add makemessages command

requirements/common.txt
This PR bumps the version of django-jsonattrs, which fixes a bug that prevented decimal values from being stored to the database correctly.
The problem was a [`lambda` function](https://github.com/Cadasta/django-jsonattrs/blob/a371fa931783f7b2b24220dea7ee5082d5779745/jsonattrs/fields.py#L169-L173), which deals with values that cannot be serialised to JSON. In it's original implementation, only `date` and `datetime` types were supported. Instead of raising a `TypeError` for unsupported types, the function returned `None`. Decimal values, which are of type `Decimal`, were therefore always serialised to `None`.
[This is now fixed](https://github.com/Cadasta/django-jsonattrs/blob/a371fa931783f7b2b24220dea7ee5082d5779745/jsonattrs/fields.py#L169-L173). `Decimal` types are now converted to …
=> Fix #1039 -- Bump django-jsonattrs

provision/roles/webserver/production/templates/nginx-production
Modifies nginx configuration to reject requests without the correct hostname in the header. Basically, if it's not addressed to us, return to sender.
Anytime
None; changes are already tested and in place on staging
None
=> Block access requests that do not specify hostname (bots)

CHANGELOG.md
Updates the changelog for platform release v1.5.0
Anytime
None
None
=> Update changelog for v1.5.0

cadasta/core/static/js/dataTables.selectFiltering.js
- Fix #1065:
- Instead of looking for the archived status table cells using jQuery, look for them using DataTables itself. The solution that was used in #765 where a class was added to the table header cell would mean reintroducing the `any_archived` context variable which increases database accesses.
Anytime, but sooner rather than later.
None foreseen.
None.
=> Fix #1065: Make archived filtering work with pagination

.github/PULL_REQUEST_TEMPLATE
Added a check to the **Test** section of the PR template for manual test cases when PR's are adding new features or altering existing ones.
Anytime
None
None required
=> Add check for manual test cases to PR template

.github/PULL_REQUEST_TEMPLATE, cadasta/core/static/js/dataTables.selectFiltering.js
- Fix #1088:
- See the bug report discussion for the root cause.
- Replace the `innerHTML` extension with a proper DOM manipulation so that the search input field with its event handlers are intact.
- Also don't use `dtSettings`' properties. As mentioned by the DataTables reference, the [DataTables settings object is considered private](https://datatables.net/reference/type/DataTables.Settings) and its properties shouldn't be read.
- Fix formatting on the pull request template. (Minor fix that's been bugging me for a while.)
Anytime.
None foreseen.
None.
=> Fix #1088: Make DataTables search work with archived filter

cadasta/party/tests/test_views_default.py, cadasta/party/views/default.py
Bug fix for issue : https://github.com/Cadasta/cadasta-platform/issues/1073
Whenever possible
None
=> Fixing delete party redirection page : bugfix #1073

cadasta/core/static/css/main.css
Fix errant block with superfluous bracket.
Now
Very low
None
=> Bugfix CSS

cadasta/core/static/css/single.scss, cadasta/templates/search/search.html
- Completes #1110 
- Simplified text on search strings (removed search index reference):
• From "Search index was lasted updated on" to "Last updated on"
• From "We’re sorry, it seems the search index is currently not available" to "We’re sorry, search is currently not available"
- Add margin to left of resource thumbnail to align with other search result details 
- In this sprint
- Low
- None
=> Simplified search text strings, adjusted img left margin

README.rst
There is problem in running ansible on Windows as Windows isn’t supported for the control machine,so a documentation and a link  is added for the windows users( to be more specific for new users) .
As soon as possible as windows users are getting confused and are having having problem installing and running the development platform
=> Improvement in README document

.github/CONTRIBUTING, CONTRIBUTING
- Adds a set of contributing guidelines to the repo. The goal is to provide new contributors with guidance to prepare their PRs. The guidelines will be [linked when opening a new PR](https://github.com/blog/1184-contributing-guidelines). 
When convenient. 
None
None
=> Adds contributing guidelines

provision/roles/webserver/production/templates/nginx-production
Implements browser cache controls and compression for static assets. According to performance metrics thus far, this change should improve subsequent page load times by 40-60% for most (if not all) current platform pages. Full improvement of up to ~85% is pending relocation of external static assets as mentioned in "Follow up actions" below.
**Note:** Changes are implemented only for access via the platform's web interface URL (i.e. https://platform-staging.cadasta.org) , not the API URL (i.e. https://platform-staging-api.cadasta.org). Because there's been some confusion and cross-use of these URLs in the past, care should be taken in the future to ensure we are using and documenting these URLs appropriately. Only programmatic access should be using the API URL.
Ref #863 
Whenever
Very …
=> Browser caching and compression

cadasta/party/tests/test_views_default.py
Fixes a test that intermittently failed on Travis. 
When convenient
None
None
=> Fix intermittently failing test

cadasta/templates/allauth/account/email/password_reset_key_message.txt
- Changed cadasta/templates/allauth/account/email/password_reset_key_message.txt
- Fixes #1139 
- No problems for merging. Can be merged now.
- None
- None
=> Bugfix/#1139: Fixed password reset email

cadasta/templates/organization/organization_wrapper.html
- Fixes #1213 
- Vertically centres the action buttons on Organization Dashboard.
Anytime
To ensure it does not break rendering on other organization pages, I verified their rendering. Another round of scrutiny wouldn't hurt though.
None
=> Fix #1213: Vertically centre action button

.gitignore
- Less conflicting versions of main.css
- Whenever
- happiness?
environments.]
-
=> Added main.css to gitignore

cadasta/templates/allauth/account/login.html, cadasta/templates/allauth/account/password_change.html
- Partially completes #1242 (removes show option from current password fields - removing confirm field will take more time)
As soon as possible
- None
=> Removed show option from current password fields on login and change password

cadasta/core/static/css/forms.scss, cadasta/core/static/css/main.css
- CSS to add border around show/hide element on password field
- As soon as possible - please put on staging to see if it fixes main.css issue
-
=> Updating forms.scss for show/hide

CHANGELOG.md
Updates changelog for v1.7.1
Anytime
None
None
=> Update changelog for v1.7.1

cadasta/config/settings/production.py, provision/roles/cadasta/install/tasks/main.yml
Switches existing Slack hooks to env vars for Ansible provisioning. The Slack hooks aren't being changed, just the way we populate them in the config files.
Anytime. Provisioning-only change; no platform code mods.
None
None
-
=> Provisioning hooks update

cadasta/templates/spatial/location_delete.html
Fix #1299 
- We now have the closing of location-delete modal by clicking "×" as expected.
No preconditions
- None
environments.]
- None
=> Bugfix #1299: Fix the closing of location-delete modal.

cadasta/templates/resources/form.html
Fixes- [1271](https://github.com/Cadasta/cadasta-platform/issues/1271)
File that is changed- cadasta/templates/resources/form.html
Whenever convenient
None
-
-
=> Fixed-1271: Unmentioned file types when uploading a new resource.

cadasta/party/tests/test_views_default.py, cadasta/spatial/tests/test_views_default.py
[List all changes you want to add here. If you fixed an issue, please
add a reference to that issue as well.]
- Fixing typo as mentioned in https://github.com/Cadasta/cadasta-platform/issues/1291
This can merge immeadiately
- No risks
- None
=> fixing typo in test classes bugfix#1291

cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/templates/organization/organization_members_edit.html
Fix #1256 
- Reworked member profile page into two sections.
No preconditions.
- NONE
environments.]
- NONE
=> Fix #1256: Rework member profile page into two sections.

cadasta/templates/spatial/relationship_add.html
- Removed extra branket in datepicker variable.
- Fixes #1309
- Whenever
- None
- None
=> Removed extra bracket from relationship_add.html

provision/roles/webserver/production/templates/uwsgi.ini
Updates Ansible template for uWSGI config for availability of Slack hook and ES host env vars within uWSGI.
Anytime; provisioning config change only.
None
None
-
=> Update Ansible template for uWSGI config

cadasta/templates/organization/project_dashboard.html, cadasta/templates/spatial/location_map.html
- Fixes #1289 
- When possible
=> Show whole project extent on overview and map project pages

cadasta/organization/tests/test_views_api_organizations.py, cadasta/organization/tests/test_views_api_projects.py, cadasta/organization/views/api.py
- Continuation of #1214 
- Removes users from the API response for unauthenticated users
- Separates test case for authorized and unauthorized users.
Anytime
- None
- None
=> Fix #1042: Hide user details for unauthorized users

cadasta/templates/allauth/account/login.html
Fix #1323
- On login page, changed the text, instead "Username" to "Username or email address".
Anytime soon.
- NONE
environments.]
- NONE
=> Fix #1323: Add email to login page text.

provision/ROLES.md
Updates Ansible documentation in repo; brings roles manifest up to date.
Anytime
None; documentation change only
None
-
=> Update Ansible roles manifest

cadasta/core/static/css/main.css, cadasta/templates/allauth/account/password_change.html
To add a 'forgot password' link to the 'change password' page.This shall enhance the user experience as otherwise, the user will have to go to the reset password page separately but with this link added the same will be only a click away.
-
Good to be merged from my side.
None according to me.
-
-None.
=> Bugfix #1188:Add 'forgotten password' link to the 'change password' page.

provision/roles/webserver/production/templates/nginx-production
Fixes the favicon path for static content serving in nginx. I'm probably the only one this annoys, but it'll spare our nginx logs and make legit errors easier to track.
Anytime
Very low, if any
None
=> Fix static serving of favicon in nginx config

.github/PULL_REQUEST_TEMPLATE
Fixes the bold markup in the PR review template. Just annoyed me.
Anytime
None; GitHub template change.
None
=> Fix bold markup in PR review template

cadasta/core/static/css/main.css, cadasta/core/static/css/main.scss, cadasta/templates/party/party_detail.html
- Addressed #1331 in this PR.
- Removed `default` css class from panel div. No shadow below panel now.
After reviews.
- None
- None
=> Fixed #1331: Wrong style used in party detail page

cadasta/core/static/css/maps.scss, cadasta/templates/core/dashboard.html, cadasta/templates/organization/project_add_extents.html, cadasta/templates/organization/project_edit_geometry.html, cadasta/templates/spatial/location_add.html, cadasta/templates/spatial/location_edit.html, cadasta/templates/spatial/location_map.html
- Fixes #1165 
- Updated leaflet-geocoder-mapzen/1.8.0/ (from leaflet-geocoder-mapzen/1.4.0/)
- Updated css to fix IE search issue 
- Updated css to make map buttons consistent for all responsive widths
- Whenever possible
- I don't see any manual test cases for any of the map interactions.  Should this be a new tab since we should test map controls manually?
=> Fixed search box on map in IE

provision/roles/webserver/production/tasks/main.yml
Extends existing cron job for pruning media/s3/downloads/ to also cover media/temp/
Anytime; no changes to platform code
None; already in place and verified on staging
None
-
=> Extend pruning for media/temp/

cadasta/geography/management/commands/loadcountries.py, cadasta/party/management/commands/loadtenurereltypes.py, cadasta/party/models.py
Try running the management commands `loadtenurelreltypes` or `loadcountries` and you'll find that neither work:
```bash
(env)vagrant@vagrant-ubuntu-trusty-64:/vagrant/cadasta$ ./manage.py loadtenurereltypes
Traceback (most recent call last):
File "./manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File "/opt/cadasta/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
utility.execute()
File "/opt/cadasta/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/opt/cadasta/env/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
self.execute(*args, **cmd_options)
File …
```
=> Add required options and helpful output to management commands

cadasta/templates/organization/project_wrapper.html
When user clicked search icon again it will take him to top of page with animation. Animate is added just for  good user experience. #1148
=> Fixed #1148

cadasta/config/settings/dev_debug.py, requirements/dev.txt
Add [django-extensions](https://github.com/django-extensions/django-extensions) to the `dev_debug` settings. 
Recommended features for developers:
- [`shell_plus`](https://django-extensions.readthedocs.io/en/latest/shell_plus.html) - Brings you into a shell with all models imported (and some convenience methods, such as `django.utils.timezone`)
- `show_urls` - show all urls exposed by app
There's a bunch of other stuff in there, it takes some exploration to find
Anytime
None
None
=> Use Django Extensions in dev qa mode

cadasta/accounts/backends.py, cadasta/accounts/forms.py, cadasta/accounts/tests/test_backend.py, cadasta/accounts/tests/test_forms.py, cadasta/accounts/tests/test_views_api.py, cadasta/accounts/tests/test_views_default.py, cadasta/accounts/utils.py, cadasta/accounts/views/api.py, cadasta/accounts/views/default.py, cadasta/config/settings/default.py, cadasta/templates/accounts/email/email_changed_notification.txt, cadasta/templates/accounts/profile.html, cadasta/templates/allauth/account/email/email_confirmation_message.txt
- Email is updated _after_ the new email has been verified. Updating an email address does not change the verified status of the users account as the old email is kept until the new email is verified. 
- A notification email is sent to the old email address. Introducing `send_email_update_notification` for this. 
- Remove the mention of the user name in the verify email text. 
- Whenever ready.
None
None
=> Fix #1140 -- Update change-email process

cadasta/core/static/css/main.scss, cadasta/core/static/css/orgs.scss, cadasta/templates/organization/organization_members_edit.html
- Fixes #1379 
- Adds ability for wrapping super long email addresses, fixed h2 bug, modified
last login css to match other pages.
- Low
- None
=> Fixed long email issue

requirements/common.txt
Upgrades Django to 1.10.7 for #1387. Includes two security fixes and some bug fixes (should also resolve the GDALClose errors we've been seeing).
Release notes: https://docs.djangoproject.com/en/dev/releases/1.10.7/
For the current release
Low; minor fixes included, will be tested on staging.
Similar updates for django-buckets and django-skivvy
=> Update Django to 1.10.7

cadasta/templates/allauth/account/password_reset_done.html
Fixes #1374 by updating the password reset notification text as discussed in #1272. 
For inclusion in release v1.7.3
None
None
=> Update password reset notification text

cadasta/core/static/css/single.scss
- Fixes overlap bug mentioned in cadasta-test (Cadasta/cadasta-test#21)
- Adds clearfix to page title
- Low
- None
=> Added clearfix to page title to avoid overlapping buttons

cadasta/organization/tests/test_views_default_organizations.py, cadasta/organization/views/default.py
- Adds tests to verify the issue.
- Updates the queryset to fix the issue.
Anytime.
- None
- None
=> Bugfix #1270: Fix the property `num_projects` of an organization.

cadasta/templates/party/party_delete.html
Fix: #1360 
- The close action of party-delete modal was not proper via "x" in the top-right corner of the modal. This bug has been corrected in this PR.
Anytime soon after approval.
- None
environments.]
- None
=> Bugfix #1360: Fix closing of party-delete modal.

cadasta/organization/download/resources.py, cadasta/organization/tests/test_downloads.py
Fixes #1380 
- Archived (deleted) resources are now removed from project data download.
Anytime after review.
- None
environments.]
- None
=> Bugfix/#1380: Archived resources removed from project data download.

cadasta/core/static/css/forms.scss, cadasta/core/static/css/main.scss
- Partially completes #1282 
- Adjusts so there is no overlapping on smaller responsive screens
- Low
- None but with map interactions this is better integrated into the layout. Still looks a bit taped-on but at least it fixes the break on smaller screens.
=> CSS adjustments for language dropdown on responsive screen

cadasta/accounts/views/api.py, requirements/common.txt, requirements/dev.txt
- Upgrades django-skivvy and django-buckets to their latest versions.
- Removes exception handling from the accounts API that was only introduced because of the poor setup of test views in django-skivvy. This is now resolved since django-skivvy uses Django's `RequestFactory` to build requests.
Whenever convenient. 
None
environments.]
None
=> Upgrade django-skivvy and django-buckets

CHANGELOG.md
Changelog updates for v1.7.3
Anytime
None; documentation only change
None
=> Update changelog for v1.7.3

cadasta/core/static/css/main.scss, cadasta/core/static/css/maps.scss, cadasta/core/static/css/single.scss, cadasta/core/static/js/map_utils.js, cadasta/resources/tests/test_views_default.py, cadasta/templates/core/dashboard.html, cadasta/templates/party/party_detail.html, cadasta/templates/party/relationship_detail.html, cadasta/templates/party/relationship_edit.html, cadasta/templates/resources/edit.html, cadasta/templates/resources/project_detail.html, cadasta/templates/search/search_result_item.html, cadasta/templates/spatial/location_detail.html, cadasta/templates/spatial/location_form.html, cadasta/templates/spatial/location_wrapper.html
- Fixes #1342 
- Updates page header for resource detail to match party detail
- Added adjustments for detail table (future file size, etc to follow in #1267) 
- CSS updates
- Low
- None but a little unsure about unit test change include in this. Let me know if its incorrect.
=> Adding header to resource detail

CHANGELOG.md
Update changelog for v1.7.4-alpha.1
Anytime
None
None
=> Update changelog for v1.7.4-alpha.1

CHANGELOG.md
Updates changelog for sprint release
Anytime
N/A; doco only
None
=> Update changelog v1.8.0

CHANGELOG.md
Updates changelog for v1.8.0 release
Anytime
None; doco change only
None
=> Update Changelog for v1.8.0 release

CHANGELOG.md
Updates changelog for v1.8.1
Anytime
None; doco only
None
=> Update CHANGELOG for v1.8.1

cadasta/core/static/css/datatables.scss, cadasta/core/static/css/main.scss, cadasta/core/static/js/bootstrap.min.js, cadasta/templates/core/base.html
- Completes #1408 
- CDN file provides js for bootstrap 3.3.5, jquery 1.11.3 and datatables 1.10.8
- Removed jquery.js call
- Removed bootstrap.js call and file
- Moved datatables css into scss file and pulled into main.scss (using same version that we were already using)
- Few small css spacing changes
- Low
- Ensure all datatables and js working as expected in QA
=> Eliminate duplicate js and css

cadasta/templates/organization/project_edit_details.html
Shows link to current questionnaire when the project schema is locked.
Anytime
None
None
=> Bugfix #1423: Show links to questionnaires even when project schema is locked.

cadasta/config/settings/default.py, cadasta/config/settings/dev.py, cadasta/config/settings/travis.py, provision/roles/webserver/production/tasks/main.yml, requirements/common.txt, requirements/dev.txt
Extends our current SASS compilation process for robustness across dev, travis, and production configurations. Also tidies up env configs to avoid duplication of shared settings.
Anytime
Very low; changes already in place on staging and only affect provisioning
None
=> Sass compilation update

cadasta/templates/organization/project_wrapper.html
Related to #1282 
Only project members can see project language selector dropdown.
Anytime.
None
None
=> Partial bugfix/1282: Only project members can see project language selector dropdown

CHANGELOG.md
Updates changelog for v1.8.2
Anytime
None; doco only change
None
=> Update changelog for v.1.8.2

CHANGELOG.md
Update changelog v1.9.0-alpha.1
Anytime
None; doco only
None
=> Update changelog v1.9.0-alpha.1

CHANGELOG.md
Update CHANGELOG for v1.9.0
Anytime
None; doco only
N/A
=> Update CHANGELOG for v1.9.0

cadasta/templates/organization/organization_members.html
- Completes #1543 
- Added form submit script to organization member pages
- Low
- None
=> Added form submit js to add org member page

Gruntfile.js, cadasta/accounts/forms.py, cadasta/core/static/css/leaflet.toolbar.css, cadasta/core/static/css/main.scss, cadasta/core/static/css/maps.scss, cadasta/core/static/js/contacts.js, cadasta/core/static/js/parsley/sanitize.js, cadasta/core/static/js/smap/edit/controls.js, cadasta/core/static/js/smap/edit/editor.js, cadasta/core/static/js/smap/index.js, cadasta/core/static/js/smap/map/map.js, cadasta/core/static/js/smap/map/vendor/L.TileLayer.GeoJSON.js, cadasta/core/static/js/smap/router/CreateRoutes.js, cadasta/core/static/js/smap/router/RouterMixins.js, cadasta/core/static/js/smap/router/SimpleRouter.js, cadasta/core/static/js/smap/router/vendor/L.Hash.js, cadasta/organization/forms.py, cadasta/party/forms.py, cadasta/resources/forms.py, cadasta/spatial/forms.py, cadasta/spatial/tests/test_views_async.py, cadasta/spatial/views/async.py, cadasta/templates/organization/project_map.html, cadasta/templates/organization/project_wrapper.html, cadasta/templates/spatial/location_form.html
[___Note:__ Not going into master. Going into __feature/map-spa-router___]
By no means a complete list of bugfixes, but it's a start. Addresses issues in #1516.
- Fixes "Sometimes geometries do not all load."
- Fixed "Geometry doesn't change back to default color" and renamed state.current_location.feature to state.current_location.layer for consistency with editor
- Fixes "Unsaved geometry edits: Can we make them save automatically?". Removed modal, made saving/canceling automatic.
- Fixed location delete hooks
- Prevent error in setCurrentLocationFeature
- Fixes "Pagination added to API is blocking async tile loading"
- Removed inefficiency from L.TileLayer.GeoJSON. Improved logic for centering on individual locations
- Fixing error in hash construction
- Fixes "CSS: Size and position …
=> SMap Bugfixes Round 1

README.rst
- Added django debug toolbar info to readme
- I think this is helpful. If you don't agree, feel free to disregard this PR.
- Low
- None
=> Adding debug toolbar info to readme

cadasta/core/static/css/header.scss, cadasta/templates/core/base.html
- Completes #1553 
- Adds SU badge to right of username if superuser
- Low
- With the superuser bug, I'm not 100% sure this will work on staging until that gets fixed.
=> Added badge icon next to user name for super users

cadasta/core/static/css/single.scss, cadasta/templates/resources/table.html
- Fixes #1611 
- Updates tab css to match mocks
- Right aligned button in relationships table
- Low
- None
=> CSS for tabs

README.rst
Updates readme to reflect migration from devwiki to GitHub wiki. Current readme contains full instructions for dev VM setup, so no longer necessary to link out to wiki for that content. Replaced with link to instructions for loading test data.
ASAP
None; change is documentation only.
None
=> Update wiki reference in readme

.github/CONTRIBUTING.md
Update contributing guidelines after migration to new wiki. Adds references to wiki, style guide, git workflow, code layout.
Anytime
None; documentation change only.
None
=> Update contributing guidelines for new wiki

.github/PULL_REQUEST_TEMPLATE
- New checklist items for scalability and maintenance
- Adds two checkboxes per checklist item
When reviewed
None
None
=> Changes to PR template

cadasta/core/static/css/single.scss
This fixes a SASS file syntax error in the latest master (after PR #1617 was merged). I think this syntax error was caused when the PR branch was rebased and a conflict in the single.scss file was resolved but left a missing closing curly brace in the process.
ASAP.
None foreseen.
None.
- **Are …
=> Fix syntax error in SASS file

cadasta/core/static/css/single.scss
- Fixes tab issue in #1629 
- Adjust spacing on small screens for detail area
- Soon
- Low
- None
- **Does the UI work as expected?** There should be no Javascript errors in the console; all …
=> Tab css and padding fix

CHANGELOG.md
Update changelog
Anytime
None; documentation only change 
None
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should …
=> Update changelog for v1.10.0

cadasta/config/settings/dev.py, cadasta/config/settings/production.py, requirements/common.txt
- Bumps django-buckets to 0.1.21 to enable file-size limits
- Adds file-size limit to settings
- For the upcoming release
None
None
- **Does the UI work as expected?** There should be no …
=> Add file-size limits to resource uploads

cadasta/templates/party/party_add.html, cadasta/templates/party/party_edit.html, cadasta/templates/party/relationship_edit.html, cadasta/templates/spatial/location_add.html, cadasta/templates/spatial/location_edit.html, cadasta/templates/spatial/relationship_add.html
- Fixes #1434 
- Changes default date format of date picker from mm-dd-yy to yy-mm-dd to match other project data date displays
- Low
- None
- **Does the UI work as …
=> Modified data format for query data picker

requirements/common.txt
Bumps the version of `django-buckets` to 0.1.22. The updated release fixes an issue with static files in the package not installing properly. With this change, the correct error message displays for resource uploads exceeding the max size. The file size limit appears to be enforced in testing. Resolves #1683. 
ASAP for the pending release
Very low; branch already tested on staging
None
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are …
=> Fixes #1683 django-buckets file size/error message/static files

CHANGELOG.md
Updates changelog for v1.11.0
Anytime
None; documentation only.
environments.]
-
- **Are all requirements met?** Compare implemented functionality with …
=> Update changelog for v1.11.0

cadasta/templates/allauth/account/login.html, cadasta/templates/core/base.html
- Fixes #1671 
- Added return path values to sign in and register button in right header
- Added return path values to links on login page
- Adjusted layout on login page to show "sensitive project" message to all links coming from /projects/ pages, otherwise user sees only sign-in form.
- Whenever convenient
- None
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be …
=> Adding return path to upper right buttons

cadasta/core/static/css/main.scss, cadasta/core/templatetags/filters.py, cadasta/core/tests/test_filters.py, cadasta/organization/tests/test_views_default_projects.py, cadasta/spatial/views/default.py, cadasta/templates/organization/project_dashboard.html, cadasta/templates/organization/project_dashboard_member.html, cadasta/templates/organization/project_dashboard_nonmember.html, cadasta/templates/spatial/location_detail.html
This PR addresses issue #1666 and combines features from 2 merged PRs: #1534 and #1610. This PR takes the already-calculated area value and displays it on templates `location_detail.html` and `project_dashbord_member.html`.
- Add a filter property function inside` filters.py` that filters the `user.measurement` value (defined in #1610) and then applies the right function to aptly calculate the area (defined in #1534).
- Add a test in `test_filters.py` for the added filter function.
- Add `{% load filters %}` tag in both templates
- Display area values using `area` (in `location_detail.html`) or `total_area` (in `project_dashboard_member.html`) as defined in the respective view classes created in #1534.
After completion of #1658.
None.
[List any possible follow-up actions here; for …
=> Fixes #1666 showing calculated areas with user measurement system

cadasta/templates/organization/user_list.html
- Fix #1704:
- Apply the same solution used in PR #1043 to correctly sort the last login column in the User List page.
_Note: This is a PR submitted to break the monotony and to help pay our “bug tax” because it is such a low-hanging fruit. I suggest this be reviewed and then merged if one has nothing else better to do._
Whenever.
None.
None.
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need …
=> Fix #1704: Add correct last login sorting to the user list

cadasta/core/management/commands/resetdatabase.py
This PR adds a management command as requested in the old issue #233. I personally would have benefited from this during my internship, so I thought to make it happen for saving developers' time :)
This adds one command `resetdatabase` that, in turns, runs the following commands:
**1.** **`reset_db`** -- I used the `reset_db.Command().handle()` because it's the best option.
**2.** **`./manage makemigrations`** -- I used `subprocess.call()` for this because `makemigrations.Command().handle()` asked for too many information (e.g. an `'app_label'` for each call, verbosity, interactivity etc.).
**3.** **`./manage migrate`** -- Same as above.
**4.** **`./manage loadstatic`** -- I used `subprocess.call()` because for some (still unclear to me) reasons `loadstatic.Command().handle()` has a _very …
=> Address #233: add management command for database reset

cadasta/accounts/serializers.py, cadasta/accounts/tests/test_serializers.py, cadasta/accounts/tests/test_urls_api.py, cadasta/accounts/tests/test_views_api.py, cadasta/accounts/urls/api.py, cadasta/accounts/views/api.py
Add API endpoint to verify phone number.
1. Add `PhoneVerificationSerializer` to verify phone number. This serializer takes a phone and token. If Verification Device with this token exists, verify the token. If the token is successfully verified, set `phone_verified` to True, `is_active` to True, and if the phone needs to be updated then update it.
**Tests**
- Token is valid.
- Token is invalid.
- Token has expired.
- Phone does not exist
- Invalid token format.
- Invalid phone format.
2. Add `ConfirmPhoneView` to `accounts/views/api.py`. This view is hooked to the `PhoneVerificationSerializer`. It sends HTTP_200_OK status if the phone is successfully verified, else sends HTTP_400_BAD_REQUEST status. Permission is set to `AllowAny`, so that phone can be verified with both authenticated …
=> Add API endpoint for phone verification

CHANGELOG.md
Updates changelog
Anytime
None; documentation-only
None
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no …
=> Update changelog for v1.12.0-alpha.2

cadasta/organization/tests/test_serializers.py, requirements/common.txt, requirements/dev.txt, tox.ini
This PR updates some more dependencies and packages flagged by Requires.io. This PR also includes a few changes to the platform code:
- Update error messages due to update in DRF.
Probably within Sprint 21.
While the Travis build passes, and some limited testing was done in the dev VM, extensive QA testing should be done (as part of QA day testing) to confirm there are no side-effects.
Continue investigating/testing updated packages flagged by Requires.io.
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and …
=> Update some dependencies flagged by Requires.io II

cadasta/core/static/css/widgets.scss
- Fixes #1649 
- Low
- None
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected …
=> Removed private toggle widget css breaking translations

cadasta/templates/spatial/location_add.html, cadasta/templates/spatial/relationship_add.html
Removes duplicate lines in `cadasta/templates/spatial/location_add.html` and `cadasta/templates/spatial/relationship_add.html`
Any time
None
None
- **Does the UI work as expected?** There …
=> Clean up JS

CHANGELOG.md
Updates changelog
Anytime
None; documentation only 
None
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no …
=> Update changelog to v1.12.1-alpha.1

cadasta/config/settings/default.py
- Fix #1780:
- According to [this GitHub issue](https://github.com/carltongibson/django-filter/issues/562), we now need to include django-filter into our `INSTALLED_APPS` setting. I've checked that this fix works in the dev VM. Without it, we get the 500 error, and with it, filterable browsable API views work.
When convenient.
None foreseen.
None.
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that …
=> Fix #1780: Add django-filter to INSTALLED_APPS

cadasta/templates/organization/project_add_details.html, cadasta/templates/organization/project_add_extents.html, cadasta/templates/organization/project_add_permissions.html, cadasta/templates/organization/project_add_wrapper.html, functional_tests/pages/ProjectAdd.py
- Fixes #1545 
- Removed type=submit on details Previous button (root of bug)
- Simplified code by moving button html into wizard wrapper
- Added formnovalidation to Previous buttons (validation only on Next/Finish buttons)
- Adjusted functional test to match new button class
- Low
- None
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to …
=> Project Add wizard buttons work

cadasta/config/settings/default.py
Currently, the DRF will render `<select>` tags with up to 1000 elements. This can be quite expensive on certain views.  This PR limits the amount of elements to 100 max. ([docs](http://www.django-rest-framework.org/api-guide/settings/#html-select-field-cutoffs)).
Anytime.
Low as it only affects DRF browsable API views and only a configuration change.
-
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries …
=> Limit length of select list for browsable api

cadasta/config/urls/dev.py
When running with the `dev_debug` settings, I've recently started getting the following error when rendering views:
```
NoReverseMatch at / 'djdt' is not a registered namespace
```
This is the same bug (and fix) as mentioned in bernardopires/django-tenant-schemas#222.
Anytime is good.
Minimal, a try/catch that should only effect dev instances.
None
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that …
=> Support Django Debug Toolbar for dev setups

CHANGELOG.md
Update changelog
Anytime
None; documentation only
N/A
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no …
=> Update changelog v1.12.1

cadasta/core/management/commands/loadfunctestfixtures.py, runtests-functional
This PR adds a new Django management command, `loadfunctestfixtures` to load the test data from the functional test suite to the database.
The test fixtures are JSON files that were created by doing `manage.py dumpdata` and then extracting only the objects needed for the functional tests. The new management command is then basically a wrapper around the `manage.py loaddata` command that retrieves the JSON files from the test suite package. (See the [Django docs](https://docs.djangoproject.com/en/1.10/howto/initial-data/) for more information.)
This PR also updates the **runtests-functional** shell script to call this management command as part of the Travis build.
This PR is currently branched off from the branch for PR #1766. So that PR must be approved and merged first, then this PR's …
=> Add management command to load functional test fixtures

cadasta/organization/tests/test_downloads.py
Fix #1776:
- Make `test_write_features` unit test deterministic by adding location types to the test data to ensure a desired order. Our `SpatialUnit` model already orders by type so no change in the model is needed.
- Update the temporary directory name of the `test_write_features_empty` unit test so that it doesn't conflict with the previous test. When the previous unit test fails, the temporary file it creates is not deleted leading to a failure in this unit test.
As soon as reviewed to avoid further Travis failures.
None foreseen.
None.
- **Is the risk level assessment sufficient?** …
=> Fix #1776: Make unit test deterministic

.travis.yml, requirements/dev.txt
_Note: This PR is branched off from PR #1788. To see the specific changes for this PR, do a branch comparison:_ https://github.com/Cadasta/cadasta-platform/compare/functest/accounts...functest/orgs
This PR just updates the tag of **cadasta-test** repo to v0.2.2 which includes the organization functional tests.
The following conditions need to be met:
This PR ought to be merged by Sprint 21 QA day.
Continue functional test coding.
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which …
=> Accommodate Organization functional tests

cadasta/templates/organization/project_wrapper.html
- Fixes #1817 
- Adds add party option to responsive menu
- Low
- None
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources …
=> Included add party in responsive menu

cadasta/accounts/tests/test_views_default.py, requirements/dev.txt
- Upgraded **django-skivvy** to 0.1.9
- Some views expected variables in session, but since the older version of skivvy did not support session variables, tests were not written with skivvy. Now that django-skivvy supports temporary storage in session, make changes to `accounts/test_views_default.py`. Use `session_data` kwarg to temporarily store session variables and thus change all tests which previously did not use skivvy for testing.
- As soon as it's approved
- None
- Upgrade django-skivvy to 0.1.9
- **Is the risk level assessment sufficient?** The risks section should contain all …
=> Additional Login Options - upgraded django-skivvy to 0.1.9

cadasta/templates/organization/organization_wrapper.html
- Fixes #1816 
- Replaces old ellipsis menu with new cog one
- Low
- None
- **Does the UI work as expected?** There should be no Javascript errors in the console; all …
=> Updated org menu to replace old ellipsis with cog

cadasta/core/static/css/datatables.scss, cadasta/core/static/css/footer.scss, cadasta/core/static/css/forms.scss, cadasta/core/static/css/header.scss, cadasta/core/static/css/main.scss, cadasta/core/static/css/maps.scss, cadasta/core/static/css/orgs.scss, cadasta/core/static/css/reg.scss, cadasta/core/static/css/single.scss, cadasta/core/static/css/wizard.scss, cadasta/organization/tests/test_widgets.py, cadasta/organization/widgets.py, cadasta/resources/tests/test_widgets.py, cadasta/resources/widgets.py, cadasta/templates/core/base.html, cadasta/templates/organization/organization_members_edit.html, cadasta/templates/organization/project_add_details.html, cadasta/templates/organization/project_add_extents.html, cadasta/templates/organization/project_add_permissions.html, cadasta/templates/organization/project_add_wrapper.html, cadasta/templates/organization/project_defaults_import.html, cadasta/templates/organization/project_edit_details.html, cadasta/templates/organization/user_list.html, cadasta/templates/party/party_detail.html, cadasta/templates/resources/table_add_lib.html, cadasta/templates/spatial/location_form.html, cadasta/templates/spatial/location_wrapper.html, cadasta/templates/spatial/relationship_add.html
- Fixes #1791 
- Partial of #1759 
- Removed redundant datatables css
- General css simplification and improvments
- Made user indexes consistent as bold username followed by full name on following line
- Simplified wizard steps to maximize real estate
- Made select party name and type on one line in dropdown
- Small html changes for layout consistency
- UI only
- QA in all responsive sizes
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these …
=> CSS fixes and linting

.travis.yml, requirements/common.txt, requirements/dev.txt, tox.ini
Update some more dependencies and packages flagged by Requires.io. No platform code needs to be updated for this batch of updates.
In addition, django-leaflet is now pinned to 0.18.1. When we restart the development for SMAP, we will eventually replace django-leaflet and we cannot continue to update django-leaflet before then because it has now switched to using Leaflet 1.0.0 and there are some weird UI bugs that show up with this version of Leaflet. It would be better to concentrate dev effort on SMAP instead.
Hopefully this can be included with the Sprint 21 release.
While the Travis build passes, and some very limited testing was done in the dev VM, extensive QA testing should be done (as part of QA day testing) to confirm there are no side-effects.
Nothing else apart from continuing …
=> Update some dependencies flagged by Requires.io (V)

requirements/dev.txt
This PR just updates the tag of **cadasta-test** repo to v0.2.3 which includes the organization functional tests.
After [PR #42](https://github.com/Cadasta/cadasta-test/pull/42) of the **cadasta-test** repo has been merged and tagged with `v0.2.3`. Also this PR ought to be merged by Sprint 21 QA day.
Continue functional test coding.
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries …
=> Accommodate Project functional tests

provision/roles/testing/tasks/main.yml
During the provisioning of Vagrant VMs, both @clash99 and I experienced the following error:
```
TASK [testing : Make Chromium dependency visible to Chromium] ******************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/usr/lib/chromium-browser/libffmpeg.so' in expected paths."}
```
When reviewing the filepath on the VM, I could see that `/usr/lib/chromium-browser/libffmpeg.so` was indeed present:
```sh
root@vagrant-ubuntu-trusty-64:/vagrant/cadasta# ls /usr/lib/chromium-browser/libffmpeg.so
/usr/lib/chromium-browser/libffmpeg.so
```
The Ansible [copy](http://docs.ansible.com/ansible/latest/copy_module.html) module assumes that it's copying data from the local machine to a remote machine, unless `remote_src` is set to `true`. I would theorize …
=> Bugfix: Copy libffmpeg.so from remote source

.github/PULL_REQUEST_TEMPLATE
Adds changes to make the checkboxes in the PR checkable. 
When checkboxes are indented they are rendered correctly, you can click them but their state isn't maintained. I flattened the list and removed the indentation from the checkboxes to fix this. 
Whenever ready.
None
None
- **Are all …
=> Makes review checklist checkable

cadasta/core/static/css/main.scss, cadasta/templates/accounts/user_dashboard.html
- Improved readability of left area but removing layer of nesting
- As soon as possible to accompany new user dashboard code on staging
- Low
- None
**Does the UI work as expected?** There should be …
=> Eliminated a nesting layer in the left column

cadasta/accounts/views/default.py, cadasta/core/static/css/reg.scss, cadasta/templates/accounts/profile.html, requirements/dev.txt
- Fixes #1823 
- Improved layout for content to two column (except for responsive smaller screens)
- Added Cancel button
- Success url directs user to user dashboard
- Low
- None …
=> Updates to profile page layout

cadasta/accounts/tests/test_views_default.py, cadasta/accounts/views/default.py
Fixes #1840: Adds Django's `LoginRequiredMixin` to ensure users are aways authenticated when accessing the user dashboard
High priority -- this needs to go into the next alpha
None
None
**Does the UI …
=> Fixes #1840 -- user must be authenticated to access user dashboard

provision/roles/webserver/production/templates/nginx-production
Fixes #1845  by switching off default caching. The reason users weren't able to log out was that the logout page was cached once you logged out once, all subsequent log-out attempts didn't hit the server anymore thus not kicking off the server-side log-out logic. 
For release 1.13.0
None
None.
**Are …
=> Fixes #1845 -- Switch off default caching

CHANGELOG.md
Add changes of Staging Release [`v1.13.0-alpha.1`](https://github.com/Cadasta/cadasta-platform/releases/tag/v1.13.0-alpha.1) and [`v1.13.0-alpha.2`](https://github.com/Cadasta/cadasta-platform/releases/tag/v1.13.0-alpha.2) to the changelog. 
I changed the format a bit, hoping that the changelog is a bit more readable and helpful. I following the format proposed by [keepachangelog.com](http://keepachangelog.com/en/1.0.0/). 
Whenever ready
None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need …
=> Add changelog for v1.13.0

.travis.yml, requirements/common.txt, requirements/dev.txt, tox.ini
Update some more dependencies and packages flagged by Requires.io. No platform code needs to be updated for this batch of updates.
For Sprint 22.
While the Travis build passes, and some very limited testing was done in the dev VM, extensive QA testing should be done (as part of QA day testing) to confirm there are no side-effects.
Nothing else apart from continuing investigating/testing updated packages flagged by Requires.io.
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to …
=> Update some dependencies flagged by Requires.io (VI)

cadasta/core/static/css/main.scss, cadasta/core/static/js/file-upload.js, cadasta/templates/organization/project_add_details.html, cadasta/templates/organization/project_dashboard_member.html, cadasta/templates/organization/project_edit_details.html
- Fixes #1627 by updating regex to replace all underscores with blank spaces in file name
- Fixes #1626 by updating links to contact pages with mailto and subject line
- CSS tweak to have add buttons z-index placed above datatables
- Low
- None
**Are all requirements met?** Compare …
=> Replaces all underscores in file names with blank spaces

requirements/dev.txt
Fixes intermittand test failures by upgrading to latest version of cadasta-test
ASAP
None
None
**Does the UI work as expected?** There should be no Javascript errors in the console; all resources …
=> Update cadasta-test to 0.2.7

provision/roles/cadasta/install/tasks/main.yml, provision/roles/cadasta/production/tasks/main.yml, provision/roles/webserver/production/templates/uwsgi.ini
Following the deployment om staging, two updates to the Ansible playbooks:
- Make sure `DB_PASS` env variable is passed both to SSH and uwsgi envs (Fixes bugs introduced with #1870).
- Make sure that user `cadasta` owns the application directory and all subsequent directories and files to prevent hickups when generating compressed static files (Introduced with #1861)
This is urgent it needs to go with the next release
Low.
None.
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to …
=> Fixes issues of deployment with recent changes

CHANGELOG.md
- Add changelog for v1.13.1
When ready
None
None
**Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. …
=> Add changelog for v1.13.1

requirements/common.txt
This PR resolves an issue with Travis unit test jobs failing recently by pinning the py package version to 1.4.34 and instructing Requires.io not to flag it to be updated to 1.5.0 or later.
As far as I can tell, one of the packages we are using requires the py package, but did not specify which version it wants, so Pip in Travis is installing the latest version which is 1.5.0, which was released yesterday (November 14). However, a later package we are using requires the py package to be >1.4.33 and <1.5 resulting into a `ContextualVersionConflict` error on Travis. The requirement that py should be <1.5 apparently stems from the [new message in the py 1.5.0 release](https://pypi.python.org/pypi/py/1.5.0) that it is in maintenance mode:
> **NOTE:** this library is in **maintenance mode** …
=> Pin py package version to 1.4.34

runtests.py, tox.ini
This PR allows functional tests to run even when Celery is installed. It was previously noted that when Celery is installed, the functional tests would not run properly (we encounter the `django.core.exceptions.ImproperlyConfigured` exception).
So instead of trying to disable Django when running functional tests (by unsetting the `DJANGO_SETTINGS_MODULE` environment variable before invoking Pytest), we make the Cadasta Django app findable by adding `/vagrant/cadasta` or `{toxinidir}/cadasta` into the Python path. Allowing Django to be loaded should be harmless because it is not used by the functional tests anyway.
Before the Async branch is merged.
None foreseen.
None. (But rebase the Async branch onto master when this PR is merged.)
**Is this PR explained thoroughly?** All code changes …
=> Include cadasta app in Python path

cadasta/config/settings/default.py, cadasta/core/static/css/main.scss, cadasta/organization/tests/test_views_default_projects.py, cadasta/templates/organization/project_dashboard_member.html, cadasta/templates/organization/project_dashboard_nonmember.html, cadasta/templates/spatial/location_detail.html
- Fixes #1756 
- Fixes #1847 by not showing areas calculated to be less than 0
- Using django.humanize, adds commas to stats numbers and area in project overview and dashboard and to area on location detail 
- Doesn't account for localization of number's commas, periods, spaces at this time
- Low
- None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes …
=> Added commas to stats numbers and area

.travis.yml, runtests-functional
Use the new [conditional builds, stages, and jobs](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/) feature of Travis to entirely skip functional test jobs when it is not needed.
For now, we can't use this new feature to simplify the runtests-functional shell script because we still need to target particular tests to run (`-m uploads` vs. `-m 'not uploads'`).
When convenient.
None foreseen.
None.
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. …
=> Use Travis conditional jobs feature

.travis.yml
Resolve #1905. Lint checks, migration checks, and unit tests are now only run for push/commit events to any branch and not for PRs. (For PRs to `master`, we now run only functional tests. For PRs to other branches, nothing is run. [I wonder if Travis will complain.])
When convenient
None foreseen.
None.
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment …
=> Resolve #1905: Skip other Travis jobs for PRs

cadasta/accounts/gateways.py, cadasta/accounts/tests/test_gateways.py, cadasta/config/settings/default.py, cadasta/config/settings/production.py, provision/roles/cadasta/install/tasks/main.yml, provision/roles/webserver/production/templates/uwsgi.ini, requirements/common.txt
Adding required env variables for deployment on production environments:
- Adds `TWILIO_ACCOUNT_SID` and `TWILIO_AUTH_TOKEN` to uswsgi env
- Introduces new env variable `TWILIO_PHONE`, which we use to define the sending phone number for texts
For the final release of the phone feature
None, assuming we're doing another test deploy to staging with the new config. 
None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new …
=> Add missing env variables for deployment

cadasta/templates/core/base.html
- Fixes #1873 
- Defers inlinemanual player javascript until after page content has loaded.  This should speed up the initial page paint which seems slowed by inlinemanual.
- Low
- Test performance improvements on staging 
**Are all requirements met?** Compare implemented …
=> Defer loading of InlineManual JS

requirements/common.txt
- Reverts changes added with #1894 since Travis builds started failing today. 
- ASAP; this is critical for our builds to run successfully
None
After this is merged, rebase all other branches
**Does …
=> Remove pinning of py package

cadasta/core/management/commands/loadfunctestfixtures.py, requirements/dev.txt
- Upgrades cadasta-test to `v0.2.8`, which includes tests for party views.
After #1916 is merged; builds will fail until then.
None
None
**Does the UI work as expected?** There should be no Javascript …
=> Upgrade cadasta-test

runtests.py
Since #1867 `cadasta-platform` is snyced to `/opt/cadasta`, which is why you can't run unit tests from `runtests.py` any longer because the script points to the wrong path. This PR fixes that. 
Soon
None
None
**Are all requirements met?** Compare implemented functionality with the requirements …
=> Fix cadasta path in runtests.py

provision/roles/testing/tasks/main.yml
This PR updates the `testing` Ansible playbook to install the required dependencies to allow developers to run functional tests using either Chromium or Firefox in the dev VM.
The [wiki has been updated](https://github.com/Cadasta/cadasta-platform/wiki/Running-functional-tests/_compare/b776673d28d8010b2299c1a8f340bae2b6ce56d1) to provide instructions on how to select between the two browsers.
This PR also reverts the addition of the task “Make Chromium dependency visible to Chromium” introduced in PR #1788. This task was added to work around a [bug](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1718885) introduced when Chromium was updated to version 61. This bug has since been fixed.
When convenient. Not mandatory for 1.14.0.
None.
None. (But re-provision the dev VM as …
=> Update browsers and WebDrivers in VM

cadasta/config/settings/default.py
=> Re-add Leaflet settings, resolves #1921

cadasta/accounts/load.py, cadasta/accounts/serializers.py, cadasta/accounts/views/api.py, cadasta/config/urls/default.py, cadasta/core/types.py, cadasta/organization/importers/base.py, cadasta/organization/models.py, cadasta/organization/views/api.py, cadasta/party/views/api.py, cadasta/resources/views/api.py, cadasta/spatial/tests/test_serializers.py, cadasta/spatial/views/api.py, functional_tests/pages/OrganizationList.py, functional_tests/pages/OrganizationMemberList.py, functional_tests/pages/Registration.py, requirements/common.txt, requirements/dev.txt, tox.ini
Update some more dependencies and packages flagged by Requires.io. The following changes were done to the platform code:
- Fix flake8 errors related to bare `except`s and ambiguous variable name `l` (see [relevant PEP 8 style guide](https://www.python.org/dev/peps/pep-0008/#names-to-avoid)).
- Update references to Djoser serializers and views that have been renamed.
- Import `djoser.urls` into our URL config. This is based on the [Djoser changelog](https://github.com/sunscrapers/djoser/blob/master/CHANGELOG.rst#100-2017-10-14). To quote:
> **Breaking:** For Token-based and JWT authentication `djoser.urls` should be included in the URLconf as well as either `djoser.urls.authtoken` or `djoser.urls.jwt`
- Update references to `DjangoFilterBackend` (this was moved from the DRF app to the …
=> Update some dependencies (VII)

cadasta/templates/organization/project_add_permissions.html
@SteadyCadence was experiencing an issue where she was unable to proceed past the "Step 3: Assign Permissions to Members" view of the Project Creation Wizard.  She reported that this occurred in projects with many users. Upon investigation, it appears that this occurs when there are any non-admin members that don't appear on the first page of 10 users:
This is because of the fact that DataTables removes the form elements from the view when they are not in the viewable page.
My solution was the simplest thing I could think of: remove usage of DataTables on this view.  This should have almost no performance implications as all users are loaded even with DataTable's pagination. Thus, this should purely be a UX change.  I struggled to think of any tests that would verify this fix, and thus …
=> Disable DataTables on project-add permissions view

cadasta/config/settings/dev.py
When running our system with the `settings.dev` configuration and `DEBUG=True`, log DB queries to `stderr`.  This will help make egregiously high amounts of SQL queries evident to developers.
Anytime.
Little, as the changes should only apply to development environments.
environments.]
-
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate …
=> Log db queries when using dev settings

requirements/common.txt
Use new version of Tutelary.  This includes a few optimizations that should drastically improve the performance of the platform. See Cadasta/django-tutelary#36 and Cadasta/django-tutelary#39.
Anytime.
Optimizations were tested fairly thoroughly, although there's always a risk that things were missed regarding permissions logic.  Recommend doing a proper QA of permission logic.
QA
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database …
=> Use optimized tutelary

cadasta/core/views/default.py
I noticed a number of duplicated queries when loading the dashboard view:
This is caused by us running queries within a for loop.  A queryset optimization was able to remove these redundancies.
Anytime
Low.  Queryset logic should be reviewed.
N/A
**Are all requirements met?** Compare implemented …
=> Reduce queries on dashboard view

requirements/common.txt, requirements/dev.txt, tox.ini
Update some more dependencies and packages flagged by Requires.io. No changes to the platform code are needed.
Good for 1.15.0, but can be included in 1.14.1.
While the Travis build passes, and some very limited testing was done in the dev VM, regular QA testing should be done to confirm there are no side-effects.
Nothing else apart from continuing investigating/testing updated packages flagged by Requires.io. (GDAL is still not updated to 1.11 because errors are encountered. This still needs further investigation.)
**Is the risk level assessment sufficient?** The risks section should contain …
=> Update some dependencies (VIII)

CHANGELOG.md
Add changelog for v1.14.1
Anytime, when approved.
None
None
**Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no …
=> Add changelog for v1.14.1

provision/roles/cadasta/application/tasks/main.yml
The deadsnakes python3 repository was moved to a new location.
Updates the corresponding Ansible tasks to point to the new repository. 
To reproduce the error and validate the fix you need to provision your dev VM.
Provisioning with the current master will throw and error:
```
TASK [cadasta/application : Add deadsnakes Python repository]
fatal: [default]: FAILED! => {"changed": false, "cmd": "apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 tag:launchpad.net:2008:redacted", "failed": true, "msg": "gpg: \"tag:launchpad.net:2008:redacted\" not a key ID: skipping", "rc": 2, "stderr": "gpg: \"tag:launchpad.net:2008:redacted\" not a key ID: skipping\n", "stdout": "Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.pmGvO0fwZt …
```
=> Update deadsnakes repository

cadasta/config/settings/production.py
Whenever we have an exception on the service, we end up with two incident reports in our logs: The first one for the exception itself (say a `KeyError`) and the second one for the resulting `Internal Server Error`, which is just a replication of the first log. 
To reduce the noise in our error logs, I'd suggest removing the `django` logger. Now I'm not an expert on logging, so I can't think of any negative side effects, so I'm putting this up for discussion. I tested the setting with a known error on `demo`, the original error is logged as expected and site admins still receive emails about every error. 
Remove the `django` logger from production settings. 
The only way to test this is to deploy the change to staging and deliberately cause an exception. 
Anytime. 
Given my lack of …
=> [For discussion] Remove Django logger from prod settings

cadasta/templates/allauth/account/signup.html, requirements/dev.txt
- Updated broken link to sign in form located below REGISTER button
- Removed hidden class on password help text
- The sign-in link was broken
-  For class change, there is a bug in Chrome with parsley and focus events conflicting. Basically any initial action caused the help text to display and prevented any further actions. I could have moved it to on click but given the importance of the information, I didn't want to leave out users that use the tab key to navigate our form.
- Added correct login link
- Removed class and script the showed help text on focus of password field
- Click link below register button on registration form and make sure you are directed to the sign in page for previously registered users
- Ensure that you can view the password help text located directly below …
=> Updated sign in link

CHANGELOG.md
We made a release and some changes were missing from the changelog.
Adds the missing changes to the changelog
Read the changes in the changelog.
Whenever ready.
environments.]
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database …
=> Updates 1.15.0 Changelog

requirements/common.txt
Security update for Django was released
Upgrade Django dependency to 1.11.10
[The release notes](https://docs.djangoproject.com/en/2.0/releases/1.11.10/) don't indicate any big changes, I'd say if the tests pass it's good to go. 
ASAP; this is a ciritcal security fix 
environments.]
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be …
=> Django security update (1.11.10)

requirements/dev.txt
To incorporate the latest approved PRs in the **cadasta-test** repo.
Update the cadasta-test version to `v0.3.3`.
Just monitor that the PR build on Travis succeeds.
When approved.
None foreseen.
None. …
=> Update cadasta-test to v0.3.3

.gitignore, cadasta/accounts/manager.py, cadasta/accounts/tests/test_manager.py
To fix #1563. 
Changes the `UserManager. get_from_username_or_email_or_phone` to use non-case-sensitive matching for emails and usernames. 
I also added `.pytest_cache` to `.gitignore`. 
1. Create a user with username `TestUser` and email address `testuser@example.com`. 
2. Sign in with another user and create a new organization.
3. Go to the organization's member page and try to add the new user using `testuser`. The user should be added with the changes applied; on `master` you should see a message indicating the user was not found. 
4. Remove the user and try to add the same user using `Testuser@example.com`. The user should be added with the changes applied; on `master` you should see a message indicating the user was not found. 
When accepted. 
None. 
None.
**Is this PR explained …
=> Fixes #1563 -- Use iexact matching when querying users

provision/roles/webserver/production/templates/nginx-production
To resolve #1939.
Adds a condition to the nginx config that drops all illegal connections without a response (`444` is a nginx-specifc, non-standard HTTP error code that instructs nginx to do exactly that). All connections where the host has more than two subdomains are considered illegal. 
I've applied the changes manually to staging. You can run curl `curl --verbose 'mail.staging.cadasta.org'` and should receive the corresponding response. 
Whenever accepted. 
environments.]
**Is the …
=> Fixes #1939 -- Drop connection for illegal hosts

requirements/dev.txt
To leverage the latest changes in cadasta-test
Upgrade to the latest version
Nothing to test really. Should be good if the build passes. 
When ready.
None
None
**Does the UI work as expected?** There …
=> Upgrade cadasta-test to 0.4.0

requirements/common.txt
**When reviewing this PR, please do also provide a review for https://github.com/Cadasta/django-buckets/pull/48**
To fix #1761. When an upload to S3 errors, the submit button will not be enabled, which makes uploading an alternative file impossible. 
Update django-buckets. For the time being the requirements point to the branch containing the fix. Once approved, I'll release a new version and update this PR accordingly. 
1. Check out branch `bugfix/1761`
2. Install the update requirements `pip install -U -r requirements/dev.txt`
3. Try to create a new resource. 
4. Upload a file that is too large. The current limit is 10MB. To make it easier, you can adjust the accepted size to `1048576` (1MB) in the [dev settings](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/config/sett …
=> Fixes #1761 -- Bump django-buckets

requirements/dev.txt
To incorporate the latest approved PRs in the **cadasta-test** repo.
Update the cadasta-test version to `v0.5.0`.
Just monitor that the PR build on Travis succeeds.
When approved.
None foreseen.
None. …
=> Update cadasta-test to v0.5.0

cadasta/core/static/fonts/bootstrap
- Added font files to font folder under static
- Removed need for alias
- Simplified means of accessing icons
- Added 5 fonts to static/fonts/bootstrap
- Should fix broken icons on local machine (see attached screenshots)
**BEFORE (not missing icons and console errors)**
**AFTER**
- Low
environments.]
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which …
=> Added glyphicons font

cadasta/templates/spatial/relationship_add.html
- Updated link to css file
- Fixes #1989
- Link was broken
- Changed link to reference jquery-ui css file
- Use a project that includes a questionnaire with a date in the relationship fields (such as sample Urban form)
- Add a relationship to a location and make sure the calendar looks properly formatted
- When convenient, officially part of Sprint 2018.02
- Low
- None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new …
=> Updated link to css file

cadasta/core/static/jsx/paginated-table.jsx
Quick fix for #1995. It feels to me that the pagination of the table is dependent-on/secondary-to the table's contents, meaning that once the table's contents changes it makes no sense to retain the page number viewed as it no longer has any useful relevance.  For this reason, the best plan of action is to reset the table's offset when the data that makes up the table's contents changes (i.e. after a user changes the search query).
When someone inputs a search, we set the table `offset` to `0` to ensure that we are looking at the first page of data.
1. Checkout branch
2. Build JS: `npm run-script build`
3. Runserver: `./runserver`
4. Access project with lots of data, view table, navigate to second page of data, enter in search criteria, verify that the offset returned to zero when search …
=> Clear table offset when searching (fixes #1995)

cadasta/core/static/js/map_utils.js
- Lower deflate minimum threshold for project maps from 20 to 5.
- Fixes #1990 
- Projects with many small parcels close together are having problems viewing them.
- Lowered threshold for project maps.
- Look at a project map with small parcels that are currently represented with icon markers. After the change, they should show as small boundaries. (Parcels under 5 pixels X 5 pixels will still show as icon markers.)
- When convenient, for current sprint
- Low
- None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and …
=> Lower deflate tolerance for project maps

cadasta/config/settings/dev.py
A little bird told me that they thought it was annoying how many logs get printed when loading fixtures.
With the change, you can now run a command with `NODB=1 <your-command>` to silence DB output.
Run `./manage.py migrate`, see lots of lDB ogs.
Run `NODB=1 ./manage.py migrate`, see no DB logs.
Anytime
None that I can think of.
environments.]
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced …
=> Add option to silence DB logs during dev process

.travis.yml, requirements/dev.txt, tox.ini
We are starting to hit the Travis 50-minute timeout limit again for BrowserStack-based functional test builds.
- Point to the (future) `v0.6.2` tag of the cadasta-test repo which includes tests reorganized into 4 batches.
- Update **tox.ini** and **.travis.yml** to add new references to the 4th batch of functional tests.
- Simplify the conditional build config in **.travis.yml**. First, we move the `BROWSERSTACK_USERNAME` and the secure `BROWSERSTACK_ACCESS_KEY` environment variables to the `env`-`global` block since they are harmless when unused and are only used if and only if `CADASTA_WEB_DRIVER` is set to `BrowserStack-Chrome`, which is controlled in the **runtests-functional** file. Second, this now makes the `pull` and `push_request` conditional jobs for functional tests the same …
=> Reorganize functional tests into 4 batches; simplify Travis config

cadasta/core/static/js/map_utils.js, cadasta/core/static/js/xlang.js, cadasta/templates/spatial/location_detail.html, cadasta/templates/spatial/location_map.html, cadasta/templates/spatial/location_wrapper.html
@MappingKat pointed out that the location type in the location header is not translated when switching the languge using the form-language switcher. 
- Added the translations for the location type to the location-detail template
- Make sure `span` elements are picked up when changing the language. 
1. Create a project using a multi-language form, ideally `Sustainable Sourcing (1_1) Form.xlsx`.
2. Create a location.
3. On the location detail page, switch the language and verify that the language changes (Might have to clear the cache). 
ASAP, as this seems to be a really big deal to one of our partners. 
None
None
**Is the PR labeled correctly?** It should have the `migration` label if a new …
=> Add multi-lang support to location header

provision/roles/cadasta/install/tasks/main.yml, provision/roles/webserver/production/templates/uwsgi.ini
environments.]
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes …
=> Rm opbeat variables from ansible tooling

requirements/dev.txt
New version of functests is available
Updade requirements to use new functional tests
Run functests locally or watch Travis builds
When it's ready
None
None
**Does the UI work as expected?** There …
=> Upgrade functional tests to v0.7.0

CHANGELOG.md
We have a new release
Add changes to the changelog
N/A
When approved
None
None
**Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There …
=> Update changelog (v1.17.0)

requirements/common.txt
Django 1.11.10 is insecure; a new version was released
Upgrade dependencies to Django 1.11.11
The tests should be sufficient
ASAP
None
Make a new release and deploy to prod as soon as possible.  …
=> Ugrade Django to 1.11.11

requirements/dev.txt
New version of functests is available
Updade requirements to use new functional tests
Run functests locally or watch Travis builds
When it's ready
None
None
**Does the UI work as expected?** There …
=> Upgrade cadasta-test to v0.8.0

cadasta/templates/organization/project_dashboard_member.html
Loading avatars block all other subsequent requests on the project dashboard. Since we don't process uploaded images, it is possible that users upload large images, which we're downloading onto the page, hence blocking the overall loading of the site (for example, the map. 
Hide avatars from the list of project members on the project dashboard. 
Go to the project dashboard and find the avatars removed from the list of project members.
Soon
None. 
None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions …
=> Hide avatars on project dashboard

CHANGELOG.md, requirements/common.txt
Fixes #2017 
Use updated `drf-tmp-scoped-token` version.
See Cadasta/drf-tmp-scoped-token#10
1. Create **private** project with name of `tést`.
1. Populate the following script with your username, an org slug, a proj slug, and run in your shell:
```py
from django.core.urlresolvers import reverse
from rest_framework_tmp_scoped_token import TokenManager
from accounts.models import User
print(
TokenManager(
user=User.objects.get(username='<YOURUSERNAME>'),
endpoints={'GET': [
reverse(
'api:v1:organization:project_detail',
kwargs={
'organization': '<ORG_SLUG>', 
'project': '<PRJ_SLUG>'
}
)
]}
).generate_token()
)
```
1. Populate the following script and run in your terminal:
```sh
curl "http://localhost:8000/api/v1/organizations/<ORG_SLUG>/projects/<PRJ_SLUG>/?TOKEN=<MYTOKEN>"
```
With the …
=> Use new release of drf-tmp-scoped-token (fixes #2017) [branch ch92]

cadasta/config/settings/production.py
We are getting many errors regarding not allowed hosts requesting from our webserver.  These are the healthchecks coming from AWS' load balancer.  It seems that the tooling to automatically add the local IP address to the `ALLOWED_HOSTS` settings is timing out too due to its short timeout window.
Being that the only time that we run the platform with production settings is on AWS, I'm removing the try/catch of the tooling to add our local IP address to the `ALLOWED_HOSTS` settings. …
=> Ensure local_ip_url added to ALLOWED_HOSTS

CHANGELOG.md
Changelogs were missing for recent releases
Add changelogs for 1.17.x releases
N/A
environments.]
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible …
=> Add 1.17.x changelogs

requirements/common.txt
Fix Katrina's bug
Update django buckets to new version, which contains the neccessary fix (https://github.com/Cadasta/django-buckets/pull/52).
The only way test this is to get this branch on staging. The dev is not affected by this. 
Soon, so we can close the ticket. 
environments.]
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be …
=> Update django-buckets (0.1.25)

requirements/common.txt
If you add or edit a party on the platform and leave non-required fields blank, number and date fields , which are blank, are displayed as None. The bug has been fixed in https://github.com/Cadasta/django-jsonattrs/pull/41, the changes need to be applied to the platform
Upgrade django-jsonattrs to apply the changes of https://github.com/Cadasta/django-jsonattrs/pull/41 to the platform
Create a project using [this form](https://github.com/Cadasta/django-jsonattrs/files/2062655/e2i5dpffikimw5eggv9dftyq.xlsx). The form contains an `integer` field called `number_children` and a `date` field called `dob`. 
Create a party, choose the party type "Individual" leave both `number_children` and `dob` blank. After saving you should check on the party detail page that no value is displayed for both …
=> Upgrade jsonattrs to 0.1.26

cadasta/tasks/management/commands/sync_tasks.py
The update to kombu 2.4.1 introduced an error when running the `sync_tasks` command. They renamed the `async` package to `asynchronous`, hence the [`ImportError`](https://sentry.io/cadasta/cadasta-platform/issues/572280582/).
Fix the import statement
I've deployed this to staging and we didn't see any errors since the deplyment. Exports are working so I'm assuming the change is good. 
ASAP, so we can release the bug fixes for Deameter. 
None
None
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we …
=> kombu.async --> kombu.asynchronous

CHANGELOG.md
Adds changelog entries for v1.17.6 and v1.17.7
=> Add changes for 1.17.6 and 1.17.7

CHANGELOG.md
=> Changelog 1.17.8

cadasta/xforms/management/commands/fix_zoa.py
The questionnaire used to collect data for ZOA projects contained used incorrect field names for location and party resources. The files are uploaded to the server and attached to the project but weren't attached to the corresponding location or parties. 
The original submissions are available, which we use in the script to attach the resources to the corresponding locations and parties. 
Submissions are stored on `XFormSubmission`; the `json_submission` field contains the raw data of the original submission. 
Field names used in the form are:
- `renco_resource_photo` for location photos
- `id_resource_photo` for party photos
The mappings of submissions to locations and parties are in `XFormSubmission.spatial_units` and `XFormSubmission.parties`
I implemented a one-off command to that we …
=> Adds ZOA data cleanup command

requirements/common.txt
Need to upgrade Django and requests for security
Upgraded the requirements in common.txt
Both are minor upgrades, exisiting tests should be sufficient
When it's ready
None
Deploy to prod
**Does the UI …
=> Uprade Django and requests

requirements/common.txt
There's new Django release, which contains a security patch.
Update the requirements to the leates 1.11.x version
If the tests pass, that should do it. 
ASAP
None
make deployment
**Does the UI work as …
=> Django security update

requirements/common.txt, requirements/dev.txt
Django released a security patch
- Upgrades dependencies to Django 1.11.20
- Upgrades pytest-django to make the tests pass. 
Travis build should be sufficient
ASAP
None
Make deployment to `platform` …
=> Upgrade to Django 1.11.20

.travis.yml, cadasta/party/views/default.py, cadasta/party/views/mixins.py, cadasta/resources/views/default.py, cadasta/resources/views/mixins.py, cadasta/spatial/views/default.py, cadasta/templates/organization/project_wrapper.html, cadasta/templates/party/party_detail.html, cadasta/templates/party/relationship_detail.html, cadasta/templates/resources/modal_add_lib.html, cadasta/templates/resources/modal_upload.html, cadasta/templates/resources/project_list.html, cadasta/templates/spatial/location_detail.html
Removes ability to attach existing resources
We agreed to deactivate the functionality for performance reasons
- Removes the ability to attach existing resources from templates
- Removes `HasUnattachedResourcesMixin` as it is now no longer needed
- Deactivates the functional tests in CI – they are now broken, fixing them would be to cumbersome
=> Removes functionality to attach existing resources from templates
